import type{ReactNode}from"react";import type{BoothExperience,GuestMode}from"../types";
export function AttractScreen({experience,onStart}:{experience:BoothExperience;onStart:()=>void}){return <button className="guest-attract"onClick={onStart}aria-label="Start photo booth"><div className="guest-orb">✦</div><small>{experience.eventName}</small><h1>Make a moment.</h1><p>Tap anywhere to start</p><i>●</i></button>}
export function WelcomeScreen({experience,onStart,onLanguage}:{experience:BoothExperience;onStart:()=>void;onLanguage:()=>void}){return <Screen><div className="guest-mark">✦</div><small>WELCOME TO</small><h1>{experience.eventName}</h1><p>{experience.configuration.welcomeMessage}</p><button className="guest-primary"onClick={onStart}>Start experience <b>→</b></button><button className="guest-secondary"onClick={onLanguage}>文 · EN Language</button></Screen>}
const modes:{id:GuestMode;icon:string;title:string;description:string;duration:string}[]=[{id:"Photo",icon:"◉",title:"Photo",description:"A timeless portrait",duration:"About 20 sec"},{id:"GIF",icon:"▦",title:"GIF",description:"A playful animation",duration:"About 15 sec"},{id:"Boomerang",icon:"↔",title:"Boomerang",description:"Motion that loops",duration:"About 12 sec"},{id:"Video",icon:"▶",title:"Video",description:"A short video moment",duration:"About 20 sec"}];
export function ModeSelectionScreen({selected,onSelect,onContinue}:{selected?:GuestMode;onSelect:(x:GuestMode)=>void;onContinue:()=>void}){return <Screen><small>CHOOSE YOUR MOMENT</small><h1>How do you want to shine?</h1><div className="guest-modes">{modes.map(x=><button className={selected===x.id?"selected":""}onClick={()=>onSelect(x.id)}key={x.id}><i>{x.icon}</i><b>{x.title}</b><span>{x.description}</span><em>{x.duration}</em></button>)}</div><button className="guest-primary"disabled={!selected}onClick={onContinue}>Continue <b>→</b></button></Screen>}
export function PreparationScreen({onReady}:{onReady:()=>void}){return <Screen><div className="guest-ring"><span>◎</span></div><small>GET READY</small><h1>Find your best angle.</h1><p>Stand inside the frame and look at the camera.</p><button className="guest-primary"onClick={onReady}>I’m ready</button></Screen>}
export function GuestCountdown({count}:{count:number}){return <Screen><small>CAMERA READY</small><div className="guest-countdown"aria-live="assertive">{count||"Smile!"}</div><div className="guest-progress"><span style={{width:`${(4-count)*25}%`}}/></div></Screen>}
export function CaptureScreen({video,photo,total}:{video:(x:HTMLVideoElement|null)=>void;photo:number;total:number}){return <div className="guest-camera"><video ref={video}muted playsInline/><div className="guest-capture-status"><span>● LIVE</span><b>Photo {photo} of {total}</b></div><div className="guest-flash"/></div>}
export function PreviewScreen({urls,onRetake,onContinue,onCancel}:{urls:string[];onRetake:()=>void;onContinue:()=>void;onCancel:()=>void}){return <Screen><small>LOOKING GREAT</small><h1>Keep these moments?</h1><div className="guest-previews">{urls.map((x,i)=><img src={x}alt={`Captured photo ${i+1}`}key={x}/>)}</div><div className="guest-actions"><button onClick={onRetake}>↻ Retake</button><button className="guest-primary"onClick={onContinue}>Continue →</button><button onClick={onCancel}>Cancel</button></div></Screen>}
export function TemplateSelectionScreen({onChoose}:{onChoose:()=>void}){return <Screen><small>CHOOSE YOUR STYLE</small><h1>One final touch.</h1><div className="guest-template-card"><div>✦</div><b>Event signature</b><span>Branded for this moment</span></div><button className="guest-primary"onClick={onChoose}>Use this style →</button></Screen>}
export function CompletionScreen({onFinish}:{onFinish:()=>void}){return <Screen><div className="guest-success">✓</div><small>ALL DONE</small><h1>Your moment is ready.</h1><p>Thank you for being part of the experience.</p><button className="guest-primary"onClick={onFinish}>Finish</button></Screen>}
export function ErrorRecoveryScreen({message,onRetry,onRestart}:{message:string;onRetry:()=>void;onRestart:()=>void}){return <Screen><div className="guest-error-icon">!</div><small>LET’S TRY THAT AGAIN</small><h1>We hit a small pause.</h1><p>{message}</p><div className="guest-actions"><button className="guest-primary"onClick={onRetry}>Try again</button><button onClick={onRestart}>Start over</button></div></Screen>}
function Screen({children}:{children:ReactNode}){return <main className="guest-screen">{children}</main>}
