import type{CameraCapability,CameraDevice,CameraError,CameraState}from"./types";import{resolutionProfiles}from"./types";
export interface ICameraManager{
 initialize():Promise<CameraDevice[]>;startPreview(video:HTMLVideoElement,deviceId?:string,resolution?:string):Promise<MediaTrackSettings>;
 stopPreview():void;pausePreview():void;resumePreview():Promise<void>;releaseCamera():void;restartCamera(video:HTMLVideoElement):Promise<MediaTrackSettings>;
 switchCamera(video:HTMLVideoElement,deviceId:string):Promise<MediaTrackSettings>;getCapabilities():CameraCapability[];getState():CameraState;onChange(listener:(state:CameraState,error?:CameraError)=>void):()=>void;
}
const friendly=(error:unknown):CameraError=>{const name=(error as DOMException)?.name;const map:Record<string,CameraError>={NotAllowedError:{code:"PermissionDenied",message:"Camera access is blocked.",recovery:"Allow camera access in browser settings, then retry."},NotFoundError:{code:"NoCameraFound",message:"No available camera was found.",recovery:"Connect a camera and refresh devices."},NotReadableError:{code:"CameraBusy",message:"The camera is being used by another application.",recovery:"Close other camera applications, then retry."},OverconstrainedError:{code:"StreamFailure",message:"The selected resolution is unavailable.",recovery:"Choose a lower resolution; EventLens will also try a safe fallback."},AbortError:{code:"StreamFailure",message:"The camera could not start.",recovery:"Retry the preview or reconnect the device."}};return map[name]??{code:"UnknownError",message:"The camera encountered an unexpected error.",recovery:"Restart the preview. If it continues, reconnect the camera.",technical:error instanceof Error?error.message:String(error)}};
export class BrowserCameraManager implements ICameraManager{
 private stream:MediaStream|null=null;private video:HTMLVideoElement|null=null;private state:CameraState="Stopped";private listeners=new Set<(s:CameraState,e?:CameraError)=>void>();private current={deviceId:"",resolution:"1280x720"};
 constructor(){navigator.mediaDevices?.addEventListener?.("devicechange",this.deviceChanged);document.addEventListener("visibilitychange",this.visibilityChanged);}
 async initialize(){if(!navigator.mediaDevices?.getUserMedia){this.emit("Error",{code:"BrowserUnsupported",message:"This browser cannot provide a camera preview.",recovery:"Use a current Chrome, Edge, Safari, or Firefox browser."});return[]}this.emit("Initializing");const devices=await this.discover();this.emit(devices.length?"Ready":"Disconnected",devices.length?undefined:{code:"NoCameraFound",message:"No camera is connected.",recovery:"Connect a camera and select Refresh cameras."});return devices}
 async discover():Promise<CameraDevice[]>{const list=await navigator.mediaDevices.enumerateDevices();return list.filter(x=>x.kind==="videoinput").map((x,i)=>({deviceId:x.deviceId,label:x.label||`Camera ${i+1}`,kind:x.kind,groupId:x.groupId,facingMode:/back|rear|environment/i.test(x.label)?"environment":/front|user/i.test(x.label)?"user":undefined,isDefault:i===0,isAvailable:true}))}
 async startPreview(video:HTMLVideoElement,deviceId=this.current.deviceId,resolution=this.current.resolution){this.video=video;this.current={deviceId,resolution};this.stopTracks();this.emit("Initializing");let last:unknown;for(const profile of this.fallbacks(resolution)){try{const[w,h]=profile.split("x").map(Number);this.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{deviceId:deviceId?{exact:deviceId}:undefined,width:{ideal:w},height:{ideal:h}}});const track=this.stream.getVideoTracks()[0];track.addEventListener("ended",()=>this.emit("Disconnected",{code:"CameraDisconnected",message:"The camera was disconnected.",recovery:"Reconnect it and choose Restart preview."}),{once:true});video.srcObject=this.stream;await video.play();this.current.resolution=profile;this.emit("Streaming");return track.getSettings()}catch(e){last=e;if((e as DOMException).name!=="OverconstrainedError")break}}const error=friendly(last);this.emit("Error",error);throw last}
 stopPreview(){this.stopTracks();if(this.video)this.video.srcObject=null;this.emit("Stopped")}
 pausePreview(){this.stream?.getVideoTracks().forEach(x=>x.enabled=false);this.video?.pause();this.emit("Paused")}
 async resumePreview(){if(!this.stream||!this.video)throw new Error("Camera is not initialized.");this.stream.getVideoTracks().forEach(x=>x.enabled=true);await this.video.play();this.emit("Streaming")}
 releaseCamera(){this.stopPreview();this.video=null}
 restartCamera(video:HTMLVideoElement){return this.startPreview(video,this.current.deviceId,this.current.resolution)}
 switchCamera(video:HTMLVideoElement,deviceId:string){return this.startPreview(video,deviceId,this.current.resolution)}
 getCapabilities(){const track=this.stream?.getVideoTracks()[0],c=track?.getCapabilities?.() as Record<string,unknown>|undefined;return["width","height","frameRate","zoom","focusMode","torch","exposureMode","whiteBalanceMode","brightness","contrast"].map(name=>{const v=c?.[name] as {min?:number;max?:number;step?:number}|string[]|boolean|undefined;return{name,supported:v!==undefined,minimum:Array.isArray(v)?undefined:v&&typeof v==="object"?v.min:undefined,maximum:Array.isArray(v)?undefined:v&&typeof v==="object"?v.max:undefined,step:Array.isArray(v)?undefined:v&&typeof v==="object"?v.step:undefined,values:Array.isArray(v)?v:[]}})}
 getState(){return this.state}onChange(listener:(state:CameraState,error?:CameraError)=>void){this.listeners.add(listener);return()=>this.listeners.delete(listener)}
 destroy(){this.releaseCamera();navigator.mediaDevices?.removeEventListener?.("devicechange",this.deviceChanged);document.removeEventListener("visibilitychange",this.visibilityChanged);this.listeners.clear()}
 private emit(state:CameraState,error?:CameraError){this.state=state;this.listeners.forEach(x=>x(state,error))}
 private stopTracks(){this.stream?.getTracks().forEach(x=>x.stop());this.stream=null}
 private fallbacks(preferred:string){const i=resolutionProfiles.indexOf(preferred as typeof resolutionProfiles[number]);return i<0?["1280x720","640x480"]:resolutionProfiles.slice(0,i+1).reverse()}
 private deviceChanged=()=>{void this.discover().then(d=>{if(this.current.deviceId&&!d.some(x=>x.deviceId===this.current.deviceId))this.emit("Disconnected",{code:"CameraDisconnected",message:"The selected camera is no longer connected.",recovery:"Select another camera or reconnect it."});else this.emit(this.stream?"Streaming":"Ready")})}
 private visibilityChanged=()=>{if(document.hidden&&this.state==="Streaming")this.pausePreview();else if(!document.hidden&&this.state==="Paused")void this.resumePreview().catch(()=>this.emit("Disconnected"))}
}
