using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Photos.Templates;
public sealed record TemplateElementDto(Guid Id,TemplateElementType ElementType,double PositionX,double PositionY,double Width,double Height,double Rotation,int LayerOrder,string StyleConfiguration);
public sealed record TemplateLayoutDto(Guid Id,TemplateLayoutType LayoutType,int CanvasWidth,int CanvasHeight,string BackgroundColor,string?BackgroundImage);
public sealed record PhotoTemplateDto(Guid Id,Guid OrganizationId,string Name,string Description,PhotoTemplateCategory Category,int Width,int Height,int Resolution,string AspectRatio,bool IsPublic,bool IsActive,TemplateLayoutDto Layout,IReadOnlyList<TemplateElementDto>Elements,DateTime CreatedAt);
public sealed record UpsertPhotoTemplateRequest(Guid OrganizationId,string Name,string Description,PhotoTemplateCategory Category,int Width,int Height,int Resolution,string AspectRatio,bool IsPublic,bool IsActive,TemplateLayoutType LayoutType,string BackgroundColor,string?BackgroundImage,IReadOnlyList<UpsertTemplateElement>Elements);
public sealed record UpsertTemplateElement(TemplateElementType ElementType,double PositionX,double PositionY,double Width,double Height,double Rotation,int LayerOrder,string StyleConfiguration);
public sealed record RenderTemplateRequest(Guid OrganizationId,IReadOnlyList<string>PhotoDataUrls,string EventName,string?GuestName,DateTime EventDate,string?QrContent,bool Preview);
public sealed record RenderedPhotoDto(Guid TemplateId,string MimeType,int Width,int Height,long FileSize,string DataUrl,bool Preview);
public interface IPhotoTemplateService{Task<IReadOnlyList<PhotoTemplateDto>>ListAsync(Guid organizationId,CancellationToken ct);Task<PhotoTemplateDto>GetAsync(Guid id,CancellationToken ct);Task<PhotoTemplateDto>CreateAsync(UpsertPhotoTemplateRequest request,CancellationToken ct);Task<PhotoTemplateDto>UpdateAsync(Guid id,UpsertPhotoTemplateRequest request,CancellationToken ct);Task DeleteAsync(Guid id,CancellationToken ct);Task<PhotoTemplateDto>DuplicateAsync(Guid id,CancellationToken ct);Task<PhotoTemplateDto>SetActiveAsync(Guid id,bool active,CancellationToken ct);}
public interface ITemplateRendererService{Task<RenderedPhotoDto>RenderAsync(Guid id,RenderTemplateRequest request,CancellationToken ct);}
public interface IPhotoComposerService{Task<byte[]>ComposeAsync(PhotoTemplate template,TemplateLayout layout,IReadOnlyList<TemplateElement>elements,RenderTemplateRequest request,CancellationToken ct);}
public interface IStickerService{Task<IReadOnlyList<StickerDto>>ListAsync(Guid organizationId,CancellationToken ct);}
public sealed record StickerDto(Guid Id,string Name,StickerCategory Category,bool IsPublic);
public interface IPhotoTemplateRepository{Task<PhotoTemplate?>GetAsync(Guid id,CancellationToken ct);Task<IReadOnlyList<PhotoTemplate>>ListAsync(Guid organizationId,CancellationToken ct);Task<TemplateLayout?>LayoutAsync(Guid id,CancellationToken ct);Task<IReadOnlyList<TemplateElement>>ElementsAsync(Guid id,CancellationToken ct);Task AddAsync(PhotoTemplate value,CancellationToken ct);Task AddLayoutAsync(TemplateLayout value,CancellationToken ct);Task AddElementsAsync(IEnumerable<TemplateElement>values,CancellationToken ct);void RemoveLayout(TemplateLayout value);void RemoveElements(IEnumerable<TemplateElement>values);Task<IReadOnlyList<Sticker>>StickersAsync(Guid organizationId,CancellationToken ct);}
