using EventLensAI.Domain.Common;
using EventLensAI.Domain.Enums;
namespace EventLensAI.Domain.Entities;
public sealed class PlanDefinition:BaseEntity
{
 private PlanDefinition(){}
 public PlanDefinition(Guid id,SubscriptionPlan plan,string name,decimal monthlyPrice,decimal yearlyPrice,int organizations,int events,int members,int aiCredits,long storage,int galleries,string templateAccess,bool customBranding,bool whiteLabel,bool apiAccess,bool customDomains,bool prioritySupport){Id=id;Plan=plan;Name=name;MonthlyPrice=monthlyPrice;YearlyPrice=yearlyPrice;MaximumOrganizations=organizations;MaximumEvents=events;MaximumTeamMembers=members;MonthlyAICredits=aiCredits;StorageLimit=storage;GalleryLimit=galleries;TemplateAccess=templateAccess;CustomBranding=customBranding;WhiteLabel=whiteLabel;ApiAccess=apiAccess;CustomDomains=customDomains;PrioritySupport=prioritySupport;}
 public SubscriptionPlan Plan{get;private set;} public string Name{get;private set;}="" ;public decimal MonthlyPrice{get;private set;} public decimal YearlyPrice{get;private set;} public string Currency{get;private set;}="USD";public int MaximumOrganizations{get;private set;} public int MaximumEvents{get;private set;} public int MaximumTeamMembers{get;private set;} public int MonthlyAICredits{get;private set;} public long StorageLimit{get;private set;} public int GalleryLimit{get;private set;} public string TemplateAccess{get;private set;}="Standard";public bool CustomBranding{get;private set;} public bool WhiteLabel{get;private set;} public bool ApiAccess{get;private set;} public bool CustomDomains{get;private set;} public bool PrioritySupport{get;private set;} public bool IsActive{get;private set;}=true;
}
public sealed class UsageCounter:BaseEntity{private UsageCounter(){}public UsageCounter(Guid organizationId,UsageMetric metric,DateOnly periodStart,long quantity){OrganizationId=organizationId;Metric=metric;PeriodStart=periodStart;Quantity=quantity;}public Guid OrganizationId{get;private set;}public UsageMetric Metric{get;private set;}public DateOnly PeriodStart{get;private set;}public long Quantity{get;private set;}public void Add(long value)=>Quantity=checked(Quantity+value);public void Set(long value)=>Quantity=Math.Max(0,value);}
public sealed class Invoice:BaseEntity{private Invoice(){}public Invoice(Guid organizationId,Guid subscriptionId,string number,string customer,SubscriptionPlan plan,decimal subtotal,decimal tax,decimal discount,string currency,DateTime issue,DateTime due){OrganizationId=organizationId;SubscriptionId=subscriptionId;InvoiceNumber=number;Customer=customer;Plan=plan;Subtotal=subtotal;Tax=tax;Discount=discount;Amount=Math.Max(0,subtotal+tax-discount);Currency=currency;IssueDate=issue;DueDate=due;Status=InvoiceStatus.Open;}public Guid OrganizationId{get;private set;}public Guid SubscriptionId{get;private set;}public string InvoiceNumber{get;private set;}="";public string Customer{get;private set;}="";public SubscriptionPlan Plan{get;private set;}public decimal Subtotal{get;private set;}public decimal Amount{get;private set;}public decimal Tax{get;private set;}public decimal Discount{get;private set;}public string Currency{get;private set;}="USD";public InvoiceStatus Status{get;private set;}public DateTime IssueDate{get;private set;}public DateTime DueDate{get;private set;}public void MarkPaid()=>Status=InvoiceStatus.Paid;public void Refund()=>Status=InvoiceStatus.Refunded;}
public sealed class PaymentTransaction:BaseEntity{private PaymentTransaction(){}public PaymentTransaction(Guid organizationId,Guid? invoiceId,string provider,string providerReference,decimal amount,string currency){OrganizationId=organizationId;InvoiceId=invoiceId;Provider=provider;ProviderReference=providerReference;Amount=amount;Currency=currency;Status=PaymentStatus.Pending;}public Guid OrganizationId{get;private set;}public Guid? InvoiceId{get;private set;}public string Provider{get;private set;}="";public string ProviderReference{get;private set;}="";public decimal Amount{get;private set;}public string Currency{get;private set;}="USD";public PaymentStatus Status{get;private set;}public decimal RefundedAmount{get;private set;}public void Succeed()=>Status=PaymentStatus.Succeeded;public void Fail()=>Status=PaymentStatus.Failed;public void Refund(decimal amount){RefundedAmount+=amount;Status=RefundedAmount>=Amount?PaymentStatus.Refunded:PaymentStatus.PartiallyRefunded;}}
public sealed class BillingCoupon:BaseEntity{private BillingCoupon(){}public BillingCoupon(string code,DiscountType type,decimal value,DateTime expiry,int limit,Guid? organizationId=null,bool referral=false){Code=code.ToUpperInvariant();DiscountType=type;Value=value;Expiry=expiry;UsageLimit=limit;OrganizationId=organizationId;IsReferral=referral;}public Guid? OrganizationId{get;private set;}public string Code{get;private set;}="";public DiscountType DiscountType{get;private set;}public decimal Value{get;private set;}public DateTime Expiry{get;private set;}public int UsageLimit{get;private set;}public int UsageCount{get;private set;}public bool IsReferral{get;private set;}public bool CanUse(Guid org)=>!IsDeleted&&Expiry>DateTime.UtcNow&&UsageCount<UsageLimit&&(!OrganizationId.HasValue||OrganizationId==org);public decimal Discount(decimal amount)=>DiscountType==DiscountType.Percentage?amount*Math.Clamp(Value,0,100)/100:Math.Min(amount,Value);public void Redeem()=>UsageCount++;}
public sealed class BillingWebhook:BaseEntity{private BillingWebhook(){}public BillingWebhook(string provider,string externalId,BillingWebhookType type,string payloadHash){Provider=provider;ExternalId=externalId;Type=type;PayloadHash=payloadHash;ReceivedAt=DateTime.UtcNow;}public string Provider{get;private set;}="";public string ExternalId{get;private set;}="";public BillingWebhookType Type{get;private set;}public string PayloadHash{get;private set;}="";public DateTime ReceivedAt{get;private set;}public DateTime? ProcessedAt{get;private set;}public string? Error{get;private set;}public void Complete()=>ProcessedAt=DateTime.UtcNow;public void Fail(string error){Error=error[..Math.Min(1000,error.Length)];ProcessedAt=DateTime.UtcNow;}}
