using EventLensAI.Domain.Common;using EventLensAI.Domain.Enums;
namespace EventLensAI.Domain.Entities;
public sealed class EventChecklist:BaseEntity{private EventChecklist(){}public EventChecklist(Guid eventId,string name){EventId=eventId;Name=Req(name);}public Guid EventId{get;private set;}public Event Event{get;private set;}=null!;public string Name{get;private set;}=string.Empty;public ICollection<EventChecklistItem>Items{get;private set;}=[];static string Req(string x)=>string.IsNullOrWhiteSpace(x)?throw new ArgumentException("Checklist name required."):x.Trim();}
public sealed class EventChecklistItem:BaseEntity
{
 private EventChecklistItem(){}public EventChecklistItem(Guid checklistId,Guid eventId,string title,string category,int order){ChecklistId=checklistId;EventId=eventId;Update(title,null,category,null,null,ChecklistPriority.Normal,ChecklistItemStatus.Pending,order);}
 public Guid ChecklistId{get;private set;}public EventChecklist Checklist{get;private set;}=null!;public Guid EventId{get;private set;}public Event Event{get;private set;}=null!;public string Title{get;private set;}=string.Empty;public string?Description{get;private set;}public string Category{get;private set;}=string.Empty;public Guid?AssignedUserId{get;private set;}public User?AssignedUser{get;private set;}public DateTime?DueDate{get;private set;}public ChecklistPriority Priority{get;private set;}public ChecklistItemStatus Status{get;private set;}public Guid?CompletedBy{get;private set;}public DateTime?CompletedAt{get;private set;}public int DisplayOrder{get;private set;}
 public void Update(string title,string?description,string category,Guid?assigned,DateTime?due,ChecklistPriority priority,ChecklistItemStatus status,int order){Title=string.IsNullOrWhiteSpace(title)?throw new ArgumentException("Task title required."):title.Trim();Category=string.IsNullOrWhiteSpace(category)?"Other":category.Trim();Description=C(description);AssignedUserId=assigned;DueDate=due?.ToUniversalTime();Priority=priority;Status=status;DisplayOrder=order;if(status!=ChecklistItemStatus.Completed){CompletedBy=null;CompletedAt=null;}}public void Complete(Guid user){Status=ChecklistItemStatus.Completed;CompletedBy=user;CompletedAt=DateTime.UtcNow;}public void Archive(Guid actor)=>SoftDelete(actor);static string?C(string?x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();
}
public sealed class EventStaffAssignment:BaseEntity
{
 private EventStaffAssignment(){}public EventStaffAssignment(Guid e,Guid u,EventStaffRole role,DateTime start,DateTime end){EventId=e;UserId=u;Update(role,start,end,StaffAssignmentStatus.Scheduled,null);}
 public Guid EventId{get;private set;}public Event Event{get;private set;}=null!;public Guid UserId{get;private set;}public User User{get;private set;}=null!;public EventStaffRole Role{get;private set;}public DateTime StartDateTime{get;private set;}public DateTime EndDateTime{get;private set;}public StaffAssignmentStatus Status{get;private set;}public string?Notes{get;private set;}
 public void Update(EventStaffRole role,DateTime start,DateTime end,StaffAssignmentStatus status,string?notes){if(end<=start)throw new ArgumentException("Shift end must be after start.");Role=role;StartDateTime=start.ToUniversalTime();EndDateTime=end.ToUniversalTime();Status=status;Notes=string.IsNullOrWhiteSpace(notes)?null:notes.Trim();}public void Archive(Guid actor)=>SoftDelete(actor);
}
public sealed class EventZone:BaseEntity{private EventZone(){}public EventZone(Guid venueId,string name,string?description,string?floor,int?capacity){VenueId=venueId;Update(name,description,floor,capacity);}public Guid VenueId{get;private set;}public Venue Venue{get;private set;}=null!;public string Name{get;private set;}=string.Empty;public string?Description{get;private set;}public string?Floor{get;private set;}public int?Capacity{get;private set;}public void Update(string name,string?description,string?floor,int?capacity){if(capacity<=0)throw new ArgumentException("Capacity must be positive.");Name=string.IsNullOrWhiteSpace(name)?throw new ArgumentException("Zone name required."):name.Trim();Description=C(description);Floor=C(floor);Capacity=capacity;}public void Archive(Guid actor)=>SoftDelete(actor);static string?C(string?x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();}
public sealed class BoothPlacement:BaseEntity{private BoothPlacement(){}public BoothPlacement(Guid e,Guid venue,Guid zone,string name){EventId=e;VenueId=venue;ZoneId=zone;Name=name.Trim();}public Guid EventId{get;private set;}public Event Event{get;private set;}=null!;public Guid VenueId{get;private set;}public Venue Venue{get;private set;}=null!;public Guid ZoneId{get;private set;}public EventZone Zone{get;private set;}=null!;public string Name{get;private set;}=string.Empty;public string?Description{get;private set;}public string?PositionNotes{get;private set;}public Guid?AssignedOperatorId{get;private set;}public User?AssignedOperator{get;private set;}public BoothPlacementStatus Status{get;private set;}=BoothPlacementStatus.Planned;public void Update(Guid venue,Guid zone,string name,string?description,string?position,Guid?op,BoothPlacementStatus status){VenueId=venue;ZoneId=zone;Name=string.IsNullOrWhiteSpace(name)?throw new ArgumentException("Placement name required."):name.Trim();Description=C(description);PositionNotes=C(position);AssignedOperatorId=op;Status=status;}public void Archive(Guid actor){Status=BoothPlacementStatus.Removed;SoftDelete(actor);}static string?C(string?x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();}
public sealed class EventNotification:BaseEntity{private EventNotification(){}public EventNotification(Guid o,Guid u,Guid?e,string title,string message,EventNotificationType type){OrganizationId=o;UserId=u;EventId=e;Title=title.Trim();Message=message.Trim();Type=type;}public Guid OrganizationId{get;private set;}public Guid UserId{get;private set;}public Guid?EventId{get;private set;}public string Title{get;private set;}=string.Empty;public string Message{get;private set;}=string.Empty;public EventNotificationType Type{get;private set;}public bool IsRead{get;private set;}public void Read()=>IsRead=true;}
