using EventLensAI.Domain.Common;using EventLensAI.Domain.Enums;
namespace EventLensAI.Domain.Entities;
public sealed class PhotoTemplate:BaseEntity
{
 private PhotoTemplate(){}public PhotoTemplate(Guid organizationId,string name,string description,PhotoTemplateCategory category,int width,int height,int resolution,string aspect,bool isPublic,Guid createdBy){OrganizationId=organizationId;CreatedBy=createdBy;Update(name,description,category,width,height,resolution,aspect,isPublic,true);}
 public Guid OrganizationId{get;private set;}public string Name{get;private set;}="";public string Description{get;private set;}="";public PhotoTemplateCategory Category{get;private set;}public int Width{get;private set;}public int Height{get;private set;}public int Resolution{get;private set;}public string AspectRatio{get;private set;}="";public bool IsPublic{get;private set;}public bool IsActive{get;private set;}
 public void Update(string name,string description,PhotoTemplateCategory category,int width,int height,int resolution,string aspect,bool isPublic,bool active){Name=name.Trim();Description=description.Trim();Category=category;Width=width;Height=height;Resolution=resolution;AspectRatio=aspect;IsPublic=isPublic;IsActive=active;}public void SetActive(bool value)=>IsActive=value;
}
public sealed class TemplateLayout:BaseEntity{private TemplateLayout(){}public TemplateLayout(Guid templateId,TemplateLayoutType type,int width,int height,string color,string?background){PhotoTemplateId=templateId;LayoutType=type;CanvasWidth=width;CanvasHeight=height;BackgroundColor=color;BackgroundImage=background;}public Guid PhotoTemplateId{get;private set;}public TemplateLayoutType LayoutType{get;private set;}public int CanvasWidth{get;private set;}public int CanvasHeight{get;private set;}public string BackgroundColor{get;private set;}="#FFFFFF";public string?BackgroundImage{get;private set;}}
public sealed class TemplateElement:BaseEntity{private TemplateElement(){}public TemplateElement(Guid templateId,TemplateElementType type,double x,double y,double width,double height,double rotation,int layer,string style){PhotoTemplateId=templateId;ElementType=type;PositionX=x;PositionY=y;Width=width;Height=height;Rotation=rotation;LayerOrder=layer;StyleConfiguration=style;}public Guid PhotoTemplateId{get;private set;}public TemplateElementType ElementType{get;private set;}public double PositionX{get;private set;}public double PositionY{get;private set;}public double Width{get;private set;}public double Height{get;private set;}public double Rotation{get;private set;}public int LayerOrder{get;private set;}public string StyleConfiguration{get;private set;}="{}";}
public sealed class Sticker:BaseEntity{private Sticker(){}public Sticker(Guid?organizationId,string name,StickerCategory category,string imagePath,bool isPublic){OrganizationId=organizationId;Name=name;Category=category;ImagePath=imagePath;IsPublic=isPublic;}public Guid?OrganizationId{get;private set;}public string Name{get;private set;}="";public StickerCategory Category{get;private set;}public string ImagePath{get;private set;}="";public bool IsPublic{get;private set;}}
public sealed class TemplateAssignment:BaseEntity{private TemplateAssignment(){}public TemplateAssignment(Guid organizationId,Guid eventId,Guid templateId){OrganizationId=organizationId;EventId=eventId;PhotoTemplateId=templateId;}public Guid OrganizationId{get;private set;}public Guid EventId{get;private set;}public Guid PhotoTemplateId{get;private set;}}
