using EventLensAI.Domain.Common;using EventLensAI.Domain.Enums;
namespace EventLensAI.Domain.Entities;
public sealed class ProfessionalCamera:BaseEntity
{
 private ProfessionalCamera(){}public ProfessionalCamera(Guid organizationId,string name,CameraProviderType provider,string model,string serialNumber,string connectionType,string?firmware){OrganizationId=organizationId;Name=name.Trim();ProviderType=provider;Model=model.Trim();SerialNumber=serialNumber.Trim();ConnectionType=connectionType;FirmwareVersion=firmware;Status=ProfessionalCameraStatus.Available;}
 public Guid OrganizationId{get;private set;}public string Name{get;private set;}="";public CameraProviderType ProviderType{get;private set;}public string Model{get;private set;}="";public string SerialNumber{get;private set;}="";public string ConnectionType{get;private set;}="";public ProfessionalCameraStatus Status{get;private set;}public string?FirmwareVersion{get;private set;}public DateTime?LastConnectedAt{get;private set;}public DateTime?LastCommunicationAt{get;private set;}public string?LastErrorCode{get;private set;}
 public void Connect(){Status=ProfessionalCameraStatus.Connected;LastConnectedAt=LastCommunicationAt=DateTime.UtcNow;LastErrorCode=null;}public void Disconnect(){Status=ProfessionalCameraStatus.Disconnected;LastCommunicationAt=DateTime.UtcNow;}public void Heartbeat(){LastCommunicationAt=DateTime.UtcNow;if(Status==ProfessionalCameraStatus.Error)Status=ProfessionalCameraStatus.Available;}public void Fail(string code){Status=ProfessionalCameraStatus.Error;LastErrorCode=code;LastCommunicationAt=DateTime.UtcNow;}
}
public sealed class CameraAdapter:BaseEntity{private CameraAdapter(){}public CameraAdapter(Guid organizationId,Guid cameraId,CameraProviderType provider,string adapterKey,string version,bool available){OrganizationId=organizationId;ProfessionalCameraId=cameraId;ProviderType=provider;AdapterKey=adapterKey;Version=version;IsAvailable=available;}public Guid OrganizationId{get;private set;}public Guid ProfessionalCameraId{get;private set;}public CameraProviderType ProviderType{get;private set;}public string AdapterKey{get;private set;}="";public string Version{get;private set;}="";public bool IsAvailable{get;private set;}}
public sealed class CameraConnectionLog:BaseEntity{private CameraConnectionLog(){}public CameraConnectionLog(Guid organizationId,Guid cameraId,string action,string status,string?error){OrganizationId=organizationId;ProfessionalCameraId=cameraId;Action=action;Status=status;ErrorCode=error;OccurredAt=DateTime.UtcNow;}public Guid OrganizationId{get;private set;}public Guid ProfessionalCameraId{get;private set;}public string Action{get;private set;}="";public string Status{get;private set;}="";public string?ErrorCode{get;private set;}public DateTime OccurredAt{get;private set;}}
public sealed class CameraCapabilityProfile:BaseEntity{private CameraCapabilityProfile(){}public CameraCapabilityProfile(Guid organizationId,Guid cameraId,string resolution,string modes,int?maxIso,string shutter,string aperture,string focus,bool flash,bool video){OrganizationId=organizationId;ProfessionalCameraId=cameraId;Resolution=resolution;SupportedModes=modes;MaxISO=maxIso;ShutterSpeed=shutter;Aperture=aperture;FocusModes=focus;FlashSupport=flash;VideoSupport=video;}public Guid OrganizationId{get;private set;}public Guid ProfessionalCameraId{get;private set;}public string Resolution{get;private set;}="";public string SupportedModes{get;private set;}="";public int?MaxISO{get;private set;}public string ShutterSpeed{get;private set;}="";public string Aperture{get;private set;}="";public string FocusModes{get;private set;}="";public bool FlashSupport{get;private set;}public bool VideoSupport{get;private set;}}
public sealed class ProfessionalCameraEvent:BaseEntity{private ProfessionalCameraEvent(){}public ProfessionalCameraEvent(Guid organizationId,Guid cameraId,Guid?sessionId,ProfessionalCameraEventType type,string metadata){OrganizationId=organizationId;ProfessionalCameraId=cameraId;BoothSessionId=sessionId;EventType=type;Metadata=metadata;OccurredAt=DateTime.UtcNow;}public Guid OrganizationId{get;private set;}public Guid ProfessionalCameraId{get;private set;}public Guid?BoothSessionId{get;private set;}public ProfessionalCameraEventType EventType{get;private set;}public string Metadata{get;private set;}="{}";public DateTime OccurredAt{get;private set;}}
