using System.Text;using System.Text.Json;using EventLensAI.Application.DTOs.Organizations;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Features.Photos.PhotoProcessing;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Services;
public sealed record BrandFile(string FileName,string ContentType,long Length,Stream Content);
public sealed record BrandDownload(Stream Content,string ContentType,string FileName);
public interface IBrandUploadPolicy{long MaxFileSizeBytes{get;}}
public sealed record BrandUploadPolicy(long MaxFileSizeBytes):IBrandUploadPolicy;
public interface IBrandKitService{Task<BrandKitDto>GetAsync(Guid organizationId,CancellationToken ct);Task<BrandKitDto>UpdateAsync(Guid organizationId,UpdateBrandKitRequest request,CancellationToken ct);Task<BrandKitDto>UploadLogoAsync(Guid organizationId,BrandLogoType type,BrandFile file,CancellationToken ct);Task RemoveLogoAsync(Guid organizationId,BrandLogoType type,CancellationToken ct);Task DeleteAsync(Guid organizationId,CancellationToken ct);}
public interface IBrandAssetService{Task<IReadOnlyList<BrandAssetDto>>ListAsync(Guid organizationId,CancellationToken ct);Task<BrandAssetDto>UploadAsync(Guid organizationId,string name,BrandAssetType type,string?tags,BrandFile file,CancellationToken ct);Task<BrandDownload>DownloadAsync(Guid organizationId,Guid id,CancellationToken ct);Task DeleteAsync(Guid organizationId,Guid id,CancellationToken ct);}
public interface IBrandThemeService{Task<IReadOnlyList<BrandThemeDto>>ListAsync(Guid organizationId,CancellationToken ct);Task<BrandThemeDto>CreateAsync(Guid organizationId,CreateBrandThemeRequest request,CancellationToken ct);Task<BrandThemeDto>UpdateAsync(Guid organizationId,Guid id,UpdateBrandThemeRequest request,CancellationToken ct);Task<BrandThemeDto>DuplicateAsync(Guid organizationId,Guid id,DuplicateBrandThemeRequest request,CancellationToken ct);Task ActivateAsync(Guid organizationId,Guid id,CancellationToken ct);Task ArchiveAsync(Guid organizationId,Guid id,CancellationToken ct);}
public abstract class BrandingServiceBase(IOrganizationRepository organizations,ICurrentUserService current)
{protected ICurrentUserService Current{get;}=current;protected Guid UserId=>Current.UserId??throw new UnauthorizedException("Authentication required.");protected async Task Read(Guid org,CancellationToken ct){if(Current.Roles.Contains(SystemRoles.SuperAdmin))return;if(await organizations.GetMemberAsync(org,UserId,ct)is null)throw new UnauthorizedException("Organization access denied.");}protected async Task Manage(Guid org,CancellationToken ct){if(Current.Roles.Contains(SystemRoles.SuperAdmin))return;var m=await organizations.GetMemberAsync(org,UserId,ct)??throw new UnauthorizedException("Organization access denied.");if(m.Role.Name is not(SystemRoles.Owner or SystemRoles.Manager))throw new UnauthorizedException("Owner or Manager permission required.");}}
public sealed class BrandKitService(IBrandingRepository repo,IOrganizationRepository organizations,IAuditRepository audits,ICurrentUserService current,IStorageService storage,IBrandUploadPolicy uploadPolicy,IUnitOfWork uow):BrandingServiceBase(organizations,current),IBrandKitService
{
 public async Task<BrandKitDto>GetAsync(Guid o,CancellationToken ct){await Read(o,ct);return Map(await Ensure(o,ct));}
 public async Task<BrandKitDto>UpdateAsync(Guid o,UpdateBrandKitRequest r,CancellationToken ct){await Manage(o,ct);var x=await Ensure(o,ct);x.UpdateColors(r.PrimaryColor,r.SecondaryColor,r.AccentColor,r.BackgroundColor,r.SurfaceColor,r.TextColor,r.SuccessColor,r.WarningColor,r.DangerColor);x.UpdateTypography(r.PrimaryFont,r.SecondaryFont,r.HeadingFont,r.BodyFont,r.FontScale);x.UpdateSettings(JsonSerializer.Serialize(r.Watermark),JsonSerializer.Serialize(r.Qr),JsonSerializer.Serialize(r.Email));x.MarkUpdated(UserId);await Audit(o,x.Id,AuditAction.Update,ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task<BrandKitDto>UploadLogoAsync(Guid o,BrandLogoType type,BrandFile f,CancellationToken ct){await Manage(o,ct);await BrandFileValidator.Validate(f,uploadPolicy.MaxFileSizeBytes,ct);var x=await Ensure(o,ct);var key=await storage.UploadAsync(f.Content,f.FileName,f.ContentType,ct);var previous=LogoKey(x,type);var versions=await repo.ListAssetsAsync(o,ct);var prior=versions.FirstOrDefault(a=>a.Type==BrandAssetType.Logo&&a.FileUrl==previous);var asset=new BrandAsset(o,$"{type} logo",BrandAssetType.Logo,key,f.ContentType,f.Length,type.ToString(),(prior?.Version??0)+1,prior?.Id);await repo.AddAssetAsync(asset,ct);x.SetLogo(type,key);await Audit(o,x.Id,AuditAction.Update,ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task RemoveLogoAsync(Guid o,BrandLogoType type,CancellationToken ct){await Manage(o,ct);var x=await Ensure(o,ct);x.SetLogo(type,null);await Audit(o,x.Id,AuditAction.Update,ct);await uow.SaveChangesAsync(ct);}
 public async Task DeleteAsync(Guid o,CancellationToken ct){await Manage(o,ct);var x=await repo.GetKitAsync(o,ct)??throw new NotFoundException("Brand kit not found.");x.SoftDelete(UserId);await Audit(o,x.Id,AuditAction.Archive,ct);await uow.SaveChangesAsync(ct);}
 private async Task<BrandKit>Ensure(Guid o,CancellationToken ct){var x=await repo.GetKitAsync(o,ct);if(x is not null)return x;x=new BrandKit(o);await repo.AddKitAsync(x,ct);await uow.SaveChangesAsync(ct);return x;}
 private Task Audit(Guid o,Guid id,AuditAction a,CancellationToken ct)=>audits.AddAsync(new AuditLog(UserId,nameof(BrandKit),id,a,Current.IPAddress),ct);
 private string?Url(string?k)=>k is null?null:storage.GetUrl(k);private BrandKitDto Map(BrandKit x)=>new(x.Id,x.OrganizationId,new Dictionary<string,string?>{{"primary",Url(x.PrimaryLogo)},{"dark",Url(x.DarkLogo)},{"light",Url(x.LightLogo)},{"icon",Url(x.IconLogo)},{"favicon",Url(x.Favicon)}},new Dictionary<string,string>{{"primary",x.PrimaryColor},{"secondary",x.SecondaryColor},{"accent",x.AccentColor},{"background",x.BackgroundColor},{"surface",x.SurfaceColor},{"text",x.TextColor},{"success",x.SuccessColor},{"warning",x.WarningColor},{"danger",x.DangerColor}},x.PrimaryFont,x.SecondaryFont,x.HeadingFont,x.BodyFont,x.FontScale,JsonSerializer.Deserialize<WatermarkSettings>(x.WatermarkSettingsJson)??new(false,null,.3m,"BottomRight",.2m,16),JsonSerializer.Deserialize<QrBrandingSettings>(x.QrBrandingJson)??new(x.PrimaryColor,"#FFFFFF",true,null,false,"M",512),JsonSerializer.Deserialize<EmailBrandingSettings>(x.EmailBrandingJson)??new("",null,x.PrimaryColor,null,null,null),x.CreatedAt,x.UpdatedAt);
 private static string?LogoKey(BrandKit x,BrandLogoType t)=>t switch{BrandLogoType.Primary=>x.PrimaryLogo,BrandLogoType.Dark=>x.DarkLogo,BrandLogoType.Light=>x.LightLogo,BrandLogoType.Icon=>x.IconLogo,_=>x.Favicon};
}
public sealed class BrandAssetService(IBrandingRepository repo,IOrganizationRepository organizations,IAuditRepository audits,ICurrentUserService current,IStorageService storage,IBrandUploadPolicy uploadPolicy,IUnitOfWork uow):BrandingServiceBase(organizations,current),IBrandAssetService
{public async Task<IReadOnlyList<BrandAssetDto>>ListAsync(Guid o,CancellationToken ct){await Read(o,ct);return(await repo.ListAssetsAsync(o,ct)).Select(Map).ToArray();}public async Task<BrandAssetDto>UploadAsync(Guid o,string n,BrandAssetType t,string?tags,BrandFile f,CancellationToken ct){await Manage(o,ct);await BrandFileValidator.Validate(f,uploadPolicy.MaxFileSizeBytes,ct);var key=await storage.UploadAsync(f.Content,f.FileName,f.ContentType,ct);var x=new BrandAsset(o,n,t,key,f.ContentType,f.Length,tags);await repo.AddAssetAsync(x,ct);await audits.AddAsync(new AuditLog(UserId,nameof(BrandAsset),x.Id,AuditAction.Create,Current.IPAddress),ct);await uow.SaveChangesAsync(ct);return Map(x);}public async Task<BrandDownload>DownloadAsync(Guid o,Guid id,CancellationToken ct){await Read(o,ct);var x=await repo.GetAssetAsync(id,ct);if(x is null||x.OrganizationId!=o)throw new NotFoundException("Asset not found.");return new(await storage.OpenReadAsync(x.FileUrl,ct),x.MimeType,x.Name+Path.GetExtension(x.FileUrl));}public async Task DeleteAsync(Guid o,Guid id,CancellationToken ct){await Manage(o,ct);var x=await repo.GetAssetAsync(id,ct);if(x is null||x.OrganizationId!=o)throw new NotFoundException("Asset not found.");x.SoftDelete(UserId);await audits.AddAsync(new AuditLog(UserId,nameof(BrandAsset),x.Id,AuditAction.Archive,Current.IPAddress),ct);await uow.SaveChangesAsync(ct);}private BrandAssetDto Map(BrandAsset x)=>new(x.Id,x.OrganizationId,x.Name,x.Type,storage.GetUrl(x.FileUrl),x.MimeType,x.FileSize,x.Tags,x.Version,x.PreviousVersionId,x.CreatedAt);}
public sealed class BrandThemeService(IBrandingRepository repo,IOrganizationRepository organizations,IAuditRepository audits,ICurrentUserService current,IUnitOfWork uow):BrandingServiceBase(organizations,current),IBrandThemeService
{public async Task<IReadOnlyList<BrandThemeDto>>ListAsync(Guid o,CancellationToken ct){await Read(o,ct);return(await repo.ListThemesAsync(o,ct)).Select(Map).ToArray();}public async Task<BrandThemeDto>CreateAsync(Guid o,CreateBrandThemeRequest r,CancellationToken ct){await Manage(o,ct);await Unique(o,r.Name,null,ct);JsonDocument.Parse(r.ConfigurationJson).Dispose();var x=new BrandTheme(o,r.Name,r.Description,r.Kind,r.ConfigurationJson);await repo.AddThemeAsync(x,ct);await Save(x,AuditAction.Create,ct);return Map(x);}public async Task<BrandThemeDto>UpdateAsync(Guid o,Guid id,UpdateBrandThemeRequest r,CancellationToken ct){await Manage(o,ct);var x=await Scoped(o,id,ct);await Unique(o,r.Name,id,ct);JsonDocument.Parse(r.ConfigurationJson).Dispose();x.Rename(r.Name,r.Description);x.UpdateConfiguration(r.ConfigurationJson);await Save(x,AuditAction.Update,ct);return Map(x);}public async Task<BrandThemeDto>DuplicateAsync(Guid o,Guid id,DuplicateBrandThemeRequest r,CancellationToken ct){await Manage(o,ct);var source=await Scoped(o,id,ct);await Unique(o,r.Name,null,ct);var x=source.Duplicate(r.Name);await repo.AddThemeAsync(x,ct);await Save(x,AuditAction.Create,ct);return Map(x);}public async Task ActivateAsync(Guid o,Guid id,CancellationToken ct){await Manage(o,ct);var target=await Scoped(o,id,ct);foreach(var x in await repo.ListThemesAsync(o,ct))x.Deactivate();target.Activate();await Save(target,AuditAction.Publish,ct);}public async Task ArchiveAsync(Guid o,Guid id,CancellationToken ct){await Manage(o,ct);var x=await Scoped(o,id,ct);if(x.IsActive)throw new ConflictException("Activate another theme before archiving the active theme.");x.SoftDelete(UserId);await Save(x,AuditAction.Archive,ct);}private async Task<BrandTheme>Scoped(Guid o,Guid id,CancellationToken ct){var x=await repo.GetThemeAsync(id,ct);return x is not null&&x.OrganizationId==o?x:throw new NotFoundException("Theme not found.");}private async Task Unique(Guid o,string n,Guid?e,CancellationToken ct){if(await repo.ThemeNameExistsAsync(o,n.Trim(),e,ct))throw new ConflictException("Theme name already exists.");}private async Task Save(BrandTheme x,AuditAction a,CancellationToken ct){await audits.AddAsync(new AuditLog(UserId,nameof(BrandTheme),x.Id,a,Current.IPAddress),ct);await uow.SaveChangesAsync(ct);}private static BrandThemeDto Map(BrandTheme x)=>new(x.Id,x.OrganizationId,x.Name,x.Description,x.Kind,x.ConfigurationJson,x.IsDefault,x.IsActive,x.CreatedAt);}
internal static class BrandFileValidator{private static readonly Dictionary<string,string[]>Allowed=new(StringComparer.OrdinalIgnoreCase){{"image/png",[".png"]},{"image/jpeg",[".jpg",".jpeg"]},{"image/webp",[".webp"]},{"image/svg+xml",[".svg"]}};public static async Task Validate(BrandFile f,long maxBytes,CancellationToken ct){if(f.Length<=0||f.Length>maxBytes)throw new ConflictException($"Image must be between 1 byte and {maxBytes/1024/1024} MB.");var ext=Path.GetExtension(f.FileName);if(!Allowed.TryGetValue(f.ContentType,out var exts)||!exts.Contains(ext,StringComparer.OrdinalIgnoreCase))throw new ConflictException("Only PNG, SVG, JPG and WEBP images are supported.");if(!f.Content.CanSeek)throw new ConflictException("Upload stream must be seekable.");var buffer=new byte[Math.Min(f.Length,4096)];var read=await f.Content.ReadAsync(buffer,ct);f.Content.Position=0;if(f.ContentType=="image/svg+xml"){var text=Encoding.UTF8.GetString(buffer,0,read);if(!text.Contains("<svg",StringComparison.OrdinalIgnoreCase)||new[]{"<script","javascript:","onload=","<!DOCTYPE","<!ENTITY"}.Any(x=>text.Contains(x,StringComparison.OrdinalIgnoreCase)))throw new ConflictException("Unsafe SVG content.");}}}
