using EventLensAI.Application.DTOs.Events;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Services;
public abstract class EventOperationsBase(IOrganizationRepository organizations,ICurrentUserService current)
{
 protected IOrganizationRepository Organizations=>organizations;protected abstract IEventRepository Repo{get;}protected async Task<Event>Access(Guid id,bool write,CancellationToken ct){var e=await Repo.GetAsync(id,ct)??throw new NotFoundException("Event not found.");if(current.Roles.Contains(SystemRoles.SuperAdmin))return e;var m=await organizations.GetMemberAsync(e.OrganizationId,UserId,ct)??throw new UnauthorizedException("Event access denied.");if(write&&m.Role.Name is not(SystemRoles.Owner or SystemRoles.Manager))throw new UnauthorizedException("Event operations permission denied.");if(!write&&m.Role.Name is SystemRoles.Photographer or SystemRoles.BoothOperator&&(await Repo.ListStaffAsync(id,ct)).All(x=>x.UserId!=UserId))throw new UnauthorizedException("You are not assigned to this event.");return e;}protected Guid UserId=>current.UserId??throw new UnauthorizedException("Authentication required.");
}
public sealed class VenueService(IEventRepository repo,IOrganizationRepository orgs,ICurrentUserService current,IUnitOfWork uow):EventOperationsBase(orgs,current),IVenueService
{
 protected override IEventRepository Repo=>repo;
 public async Task<IReadOnlyList<OperationTypeDto>>TypesAsync(Guid e,CancellationToken ct){var x=await Access(e,false,ct);return(await repo.ListVenueTypesAsync(x.OrganizationId,ct)).Select(t=>new OperationTypeDto(t.Id,t.Name,t.Description,t.IsSystemType)).ToArray();}
 public async Task<IReadOnlyList<VenueDto>>ListAsync(Guid e,bool archived,CancellationToken ct){await Access(e,false,ct);return(await repo.ListVenuesAsync(e,archived,ct)).Select(Map).ToArray();}
 public async Task<VenueDto>GetAsync(Guid e,Guid id,CancellationToken ct){await Access(e,false,ct);var x=await repo.GetVenueAsync(id,false,ct);return x is not null&&x.EventId==e?Map(x):throw new NotFoundException("Venue not found.");}
 public async Task<VenueDto>CreateAsync(Guid e,CreateVenueRequest r,CancellationToken ct){var ev=await Access(e,true,ct);await Type(ev.OrganizationId,r.VenueTypeId,ct);if(r.IsPrimary)await ClearPrimary(e,null,ct);var x=new Venue(e,r.VenueTypeId,r.Name);Apply(x,r);await repo.AddVenueAsync(x,ct);await uow.SaveChangesAsync(ct);return await GetAsync(e,x.Id,ct);}
 public async Task<VenueDto>UpdateAsync(Guid e,Guid id,UpdateVenueRequest r,CancellationToken ct){var ev=await Access(e,true,ct);await Type(ev.OrganizationId,r.VenueTypeId,ct);var x=await repo.GetVenueAsync(id,false,ct);if(x is null||x.EventId!=e)throw new NotFoundException("Venue not found.");if(r.IsPrimary)await ClearPrimary(e,id,ct);x.Update(r.VenueTypeId,r.Name,r.Description,r.AddressLine,r.City,r.State,r.Country,r.PostalCode,r.Latitude,r.Longitude,r.MapProviderReference,r.ContactPerson,r.ContactPhone,r.ContactEmail,r.Capacity,r.IsPrimary);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task ArchiveAsync(Guid e,Guid id,CancellationToken ct){await Access(e,true,ct);var x=await repo.GetVenueAsync(id,false,ct);if(x is null||x.EventId!=e)throw new NotFoundException("Venue not found.");x.Archive(UserId);await uow.SaveChangesAsync(ct);}
 public async Task<VenueDto>RestoreAsync(Guid e,Guid id,CancellationToken ct){await Access(e,true,ct);var x=await repo.GetVenueAsync(id,true,ct);if(x is null||x.EventId!=e)throw new NotFoundException("Venue not found.");x.Restore(UserId);await uow.SaveChangesAsync(ct);return Map(x);}
 async Task Type(Guid o,Guid id,CancellationToken ct){_=await repo.GetVenueTypeAsync(id,o,ct)??throw new NotFoundException("Venue type not found.");}async Task ClearPrimary(Guid e,Guid?except,CancellationToken ct){foreach(var x in await repo.ListVenuesAsync(e,false,ct))if(x.IsPrimary&&x.Id!=except){var tracked=await repo.GetVenueAsync(x.Id,false,ct);tracked!.SetPrimary(false);}}static void Apply(Venue x,CreateVenueRequest r)=>x.Update(r.VenueTypeId,r.Name,r.Description,r.AddressLine,r.City,r.State,r.Country,r.PostalCode,r.Latitude,r.Longitude,r.MapProviderReference,r.ContactPerson,r.ContactPhone,r.ContactEmail,r.Capacity,r.IsPrimary);static VenueDto Map(Venue x)=>new(x.Id,x.EventId,x.VenueTypeId,x.VenueType.Name,x.Name,x.Description,x.AddressLine,x.City,x.State,x.Country,x.PostalCode,x.Latitude,x.Longitude,x.MapProviderReference,x.ContactPerson,x.ContactPhone,x.ContactEmail,x.Capacity,x.IsPrimary,x.IsDeleted);
}
public sealed class ScheduleService(IEventRepository repo,IOrganizationRepository orgs,ICurrentUserService current,IUnitOfWork uow):EventOperationsBase(orgs,current),IScheduleService
{
 protected override IEventRepository Repo=>repo;
 public async Task<IReadOnlyList<OperationTypeDto>>TypesAsync(Guid e,CancellationToken ct){var x=await Access(e,false,ct);return(await repo.ListScheduleTypesAsync(x.OrganizationId,ct)).Select(t=>new OperationTypeDto(t.Id,t.Name,t.Description,t.IsSystemType)).ToArray();}
 public async Task<IReadOnlyList<ScheduleDto>>ListAsync(Guid e,CancellationToken ct){await Access(e,false,ct);return(await repo.ListScheduleAsync(e,ct)).Select(Map).ToArray();}
 public async Task<ScheduleDto>CreateAsync(Guid e,CreateScheduleRequest r,CancellationToken ct){var ev=await Access(e,true,ct);await Validate(ev,r.VenueId,r.ScheduleTypeId,ct);var x=new EventScheduleItem(e,r.ScheduleTypeId,r.Title,r.StartDateTime,r.EndDateTime,r.DisplayOrder);x.Update(r.VenueId,r.ScheduleTypeId,r.Title,r.Description,r.StartDateTime,r.EndDateTime,r.Status,r.DisplayOrder);await repo.AddScheduleItemAsync(x,ct);await uow.SaveChangesAsync(ct);return(await ListAsync(e,ct)).Single(y=>y.Id==x.Id);}
 public async Task<ScheduleDto>UpdateAsync(Guid e,Guid id,UpdateScheduleRequest r,CancellationToken ct){var ev=await Access(e,true,ct);await Validate(ev,r.VenueId,r.ScheduleTypeId,ct);var x=await repo.GetScheduleItemAsync(id,ct);if(x is null||x.EventId!=e)throw new NotFoundException("Schedule item not found.");x.Update(r.VenueId,r.ScheduleTypeId,r.Title,r.Description,r.StartDateTime,r.EndDateTime,r.Status,r.DisplayOrder);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task ArchiveAsync(Guid e,Guid id,CancellationToken ct){await Access(e,true,ct);var x=await repo.GetScheduleItemAsync(id,ct);if(x is null||x.EventId!=e)throw new NotFoundException("Schedule item not found.");x.Archive(UserId);await uow.SaveChangesAsync(ct);}
 public async Task ReorderAsync(Guid e,ReorderScheduleRequest r,CancellationToken ct){await Access(e,true,ct);var items=await repo.ListScheduleAsync(e,ct);if(r.ItemIds.Count!=items.Count||r.ItemIds.Distinct().Count()!=items.Count||r.ItemIds.Any(id=>items.All(x=>x.Id!=id)))throw new ConflictException("Reorder list must contain every schedule item exactly once.");for(var i=0;i<r.ItemIds.Count;i++){var x=await repo.GetScheduleItemAsync(r.ItemIds[i],ct);x!.Reorder(i);}await uow.SaveChangesAsync(ct);}
 public async Task<IReadOnlyList<CalendarEntryDto>>CalendarAsync(Guid e,DateTime?from,DateTime?to,CancellationToken ct){var q=await ListAsync(e,ct);return q.Where(x=>(!from.HasValue||x.EndDateTime>=from)&&(!to.HasValue||x.StartDateTime<=to)).Select(x=>new CalendarEntryDto(x.Id,x.Title,x.StartDateTime,x.EndDateTime,x.VenueName,x.Status.ToString())).ToArray();}
 async Task Validate(Event e,Guid?v,Guid type,CancellationToken ct){_=await repo.GetScheduleTypeAsync(type,e.OrganizationId,ct)??throw new NotFoundException("Schedule type not found.");if(v.HasValue){var venue=await repo.GetVenueAsync(v.Value,false,ct);if(venue is null||venue.EventId!=e.Id)throw new NotFoundException("Venue not found.");}}static ScheduleDto Map(EventScheduleItem x)=>new(x.Id,x.EventId,x.VenueId,x.Venue?.Name,x.ScheduleTypeId,x.ScheduleType.Name,x.Title,x.Description,x.StartDateTime,x.EndDateTime,x.Status,x.DisplayOrder);
}
