using System.Security.Cryptography;using System.Text;using System.Text.Json;
using EventLensAI.Application.DTOs.Events;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Features.Photos.PhotoProcessing;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Application.Interfaces.Services;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Services;

public abstract class EventPublicAdminBase(IEventRepository events,IOrganizationRepository organizations,ICurrentUserService current)
{
 protected IEventRepository Events=>events;protected Guid UserId=>current.UserId??throw new UnauthorizedException("Authentication required.");
 protected async Task<Event>Manage(Guid id,CancellationToken ct){var e=await events.GetAsync(id,ct)??throw new NotFoundException("Event not found.");if(current.Roles.Contains(SystemRoles.SuperAdmin))return e;var m=await organizations.GetMemberAsync(e.OrganizationId,UserId,ct)??throw new UnauthorizedException("Event access denied.");if(m.Role.Name is not(SystemRoles.Owner or SystemRoles.Manager))throw new UnauthorizedException("Event public access management permission denied.");return e;}
}
public sealed class EventQRCodeService(IEventRepository events,IOrganizationRepository organizations,ICurrentUserService current,IQrCodeService renderer,IPublicUrlService urls,IStorageService storage,IUnitOfWork uow):EventPublicAdminBase(events,organizations,current),IEventQRCodeService
{
 public async Task<IReadOnlyList<QRCodeDto>>ListAsync(Guid e,CancellationToken ct){await Manage(e,ct);return(await Events.ListQRCodesAsync(e,ct)).Select(Map).ToArray();}
 public async Task<QRCodeDto>CreateAsync(Guid e,CreateQRCodeRequest r,CancellationToken ct){await Manage(e,ct);var token=await Token(ct);var url=urls.GetPublicEventUrl(token);var json=JsonSerializer.Serialize(r.Customization);var svg=renderer.GenerateSvg(url,r.Customization.PrimaryColor,r.Customization.BackgroundColor);await using var stream=new MemoryStream(Encoding.UTF8.GetBytes(svg));var key=await storage.UploadAsync(stream,$"event-qr-{token}.svg","image/svg+xml",ct);var x=new EventQRCode(e,r.QRType,token,url,key,json,r.ExpiresAt);await Events.AddQRCodeAsync(x,ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task<QRCodeDto>UpdateAsync(Guid e,Guid id,UpdateQRCodeRequest r,CancellationToken ct){await Manage(e,ct);var x=await Events.GetQRCodeAsync(id,ct);if(x is null||x.EventId!=e)throw new NotFoundException("QR code not found.");var json=JsonSerializer.Serialize(r.Customization);var svg=renderer.GenerateSvg(x.PublicUrl,r.Customization.PrimaryColor,r.Customization.BackgroundColor);await using var stream=new MemoryStream(Encoding.UTF8.GetBytes(svg));var key=await storage.UploadAsync(stream,$"event-qr-{x.Token}.svg","image/svg+xml",ct);x.SetImage(key);x.Update(json,r.ExpiresAt,r.IsActive);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task ArchiveAsync(Guid e,Guid id,CancellationToken ct){await Manage(e,ct);var x=await Events.GetQRCodeAsync(id,ct);if(x is null||x.EventId!=e)throw new NotFoundException("QR code not found.");x.Archive(UserId);await uow.SaveChangesAsync(ct);}
 async Task<string>Token(CancellationToken ct){for(var i=0;i<5;i++){var t=Convert.ToBase64String(RandomNumberGenerator.GetBytes(24)).TrimEnd('=').Replace('+','-').Replace('/','_');if(!await Events.QRTokenExistsAsync(t,ct))return t;}throw new ConflictException("Unable to create a unique public token.");}
 QRCodeDto Map(EventQRCode x){var c=JsonSerializer.Deserialize<QRCodeCustomizationRequest>(x.CustomizationJson,new JsonSerializerOptions{PropertyNameCaseInsensitive=true})??new(null,"#111111","#FFFFFF","None","Scan to open");return new(x.Id,x.QRType,x.PublicUrl,storage.GetUrl(x.ImageStoragePath),c,x.ExpiresAt,x.IsActive,x.CreatedAt);}
}
public sealed class EventAccessSettingsService(IEventRepository events,IOrganizationRepository organizations,ICurrentUserService current,IPasswordService passwords,IUnitOfWork uow):EventPublicAdminBase(events,organizations,current),IEventAccessSettingsService
{
 public async Task<EventAccessSettingDto>GetAsync(Guid e,CancellationToken ct){await Manage(e,ct);return Map(await Events.GetAccessConfigurationAsync(e,ct));}
 public async Task<EventAccessSettingDto>UpdateAsync(Guid e,UpdateEventAccessSettingRequest r,CancellationToken ct){await Manage(e,ct);var x=await Events.GetAccessConfigurationAsync(e,ct);if(x is null){x=new(e);await Events.AddAccessConfigurationAsync(x,ct);}x.Update(r.IsPublicEnabled,r.RequirePassword,string.IsNullOrWhiteSpace(r.Password)?null:passwords.Hash(r.Password),r.AllowGuestAccess,r.AllowGalleryAccess,r.AllowDownloads,r.AllowSharing,r.ExpiryDate);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return Map(x);}
 static EventAccessSettingDto Map(EventAccessConfiguration?x)=>x is null?new(false,false,true,false,false,false,null):new(x.IsPublicEnabled,x.RequirePassword,x.AllowGuestAccess,x.AllowGalleryAccess,x.AllowDownloads,x.AllowSharing,x.ExpiryDate);
}
public sealed class PublicEventService(IEventRepository events,IBrandingRepository branding,IPasswordService passwords,IStorageService storage,IUnitOfWork uow):IPublicEventService
{
 public async Task<PublicEventDto>GetAsync(string token,string?password,string?device,CancellationToken ct){var(qr,e,c)=await Validate(token,password,ct);var brand=await events.GetBrandConfigurationAsync(e.Id,ct);var kit=await branding.GetKitAsync(e.OrganizationId,ct);var experience=await events.GetExperienceAsync(e.Id,ct);var venues=await events.ListVenuesAsync(e.Id,false,ct);var schedule=await events.ListScheduleAsync(e.Id,ct);string?logo=e.Logo,cover=e.CoverImage;if(brand?.LogoAssetId is Guid lid){var a=await events.GetEventAssetAsync(lid,ct);if(a is not null)logo=storage.GetUrl(a.StorageAssetId);}if(brand?.BackgroundAssetId is Guid bid){var a=await events.GetEventAssetAsync(bid,ct);if(a is not null)cover=storage.GetUrl(a.StorageAssetId);}await events.AddAccessLogAsync(new(e.Id,qr.Id,null,EventAccessAction.QRScan,device),ct);await events.AddAccessLogAsync(new(e.Id,qr.Id,null,EventAccessAction.PageView,device),ct);await uow.SaveChangesAsync(ct);var venue=venues.FirstOrDefault(x=>x.IsPrimary)??venues.FirstOrDefault();return new(brand?.EventDisplayName??e.Name,logo,cover,experience?.WelcomeTitle,experience?.WelcomeMessage,venue?.Name??e.Venue,venue is null?e.Address:string.Join(", ",new[]{venue.AddressLine,venue.City,venue.Country}.Where(x=>!string.IsNullOrWhiteSpace(x))),e.StartDate,e.EndDate,brand?.PrimaryColor??kit?.PrimaryColor??e.PrimaryColor,brand?.SecondaryColor??kit?.SecondaryColor??e.SecondaryColor,brand?.AccentColor??kit?.AccentColor??"#00D2D3",brand?.FontFamily??kit?.PrimaryFont??"Inter",c.AllowGuestAccess,false,false,c.AllowSharing&&experience?.EnableSharing!=false,schedule.Take(8).Select(x=>new PublicScheduleItemDto(x.Title,x.Venue?.Name,x.StartDateTime,x.EndDateTime)).ToArray());}
 internal async Task<(EventQRCode Qr,Event Event,EventAccessConfiguration Config)>Validate(string token,string?password,CancellationToken ct){if(string.IsNullOrWhiteSpace(token)||token.Length>100)throw new NotFoundException("Public event not found.");var qr=await events.GetQRCodeByTokenAsync(token,ct);if(qr is null||!qr.IsValid(DateTime.UtcNow))throw new NotFoundException("Public event not found.");var c=await events.GetAccessConfigurationAsync(qr.EventId,ct);if(c is null||!c.IsAvailable(DateTime.UtcNow))throw new NotFoundException("Public event not found.");if(c.RequirePassword&&(string.IsNullOrWhiteSpace(password)||!passwords.Verify(password,c.PasswordHash!)))throw new UnauthorizedException("A valid event password is required.");return(qr,qr.Event,c);}
}
public sealed class GuestSessionService(IEventRepository events,IPasswordService passwords,IUnitOfWork uow):IGuestSessionService
{
 public async Task<GuestSessionDto>CreateAsync(string eventToken,string?password,string?ip,string?info,string?device,CancellationToken ct){var qr=await events.GetQRCodeByTokenAsync(eventToken,ct);if(qr is null||!qr.IsValid(DateTime.UtcNow))throw new NotFoundException("Public event not found.");var c=await events.GetAccessConfigurationAsync(qr.EventId,ct);if(c is null||!c.IsAvailable(DateTime.UtcNow)||!c.AllowGuestAccess)throw new NotFoundException("Guest access is unavailable.");if(c.RequirePassword&&(string.IsNullOrWhiteSpace(password)||!passwords.Verify(password,c.PasswordHash!)))throw new UnauthorizedException("A valid event password is required.");var token=Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)).TrimEnd('=').Replace('+','-').Replace('/','_');var x=new GuestSession(qr.EventId,token,ip,info);await events.AddGuestSessionAsync(x,ct);await events.AddAccessLogAsync(new(qr.EventId,qr.Id,x.Id,EventAccessAction.SessionStart,device),ct);await uow.SaveChangesAsync(ct);return new(x.SessionToken,x.StartedAt,x.LastActivityAt);}
}
public sealed class EventAccessAnalyticsService(IEventRepository events,IOrganizationRepository organizations,ICurrentUserService current):EventPublicAdminBase(events,organizations,current),IEventAccessAnalyticsService
{
 public async Task<AccessAnalyticsDto>GetAsync(Guid e,CancellationToken ct){await Manage(e,ct);var x=await Events.ListAccessLogsAsync(e,ct);return new(x.Count(y=>y.Action==EventAccessAction.QRScan),x.Count(y=>y.Action==EventAccessAction.PageView),x.Count(y=>y.Action==EventAccessAction.SessionStart),x.Where(y=>y.GuestSessionId.HasValue).Select(y=>y.GuestSessionId).Distinct().Count(),x.GroupBy(y=>y.DeviceType).ToDictionary(y=>y.Key,y=>y.Count()));}
}
