using EventLensAI.Application.DTOs.Events;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Features.Photos.PhotoProcessing;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Services;
public abstract class EventExperienceBase(IOrganizationRepository organizations,ICurrentUserService current)
{
 protected abstract IEventRepository Repository{get;}
 protected async Task<Event>Access(Guid id,bool write,CancellationToken ct){var e=await Repository.GetAsync(id,ct)??throw new NotFoundException("Event not found.");if(current.Roles.Contains(SystemRoles.SuperAdmin))return e;var m=await organizations.GetMemberAsync(e.OrganizationId,UserId,ct)??throw new UnauthorizedException("Event access denied.");if(write&&m.Role.Name is not(SystemRoles.Owner or SystemRoles.Manager or SystemRoles.Designer))throw new UnauthorizedException("Event branding permission denied.");return e;}protected Guid UserId=>current.UserId??throw new UnauthorizedException("Authentication is required.");
}
public sealed class EventBrandService(IEventRepository repo,IOrganizationRepository orgs,IBrandingRepository branding,ICurrentUserService current,IUnitOfWork uow):EventExperienceBase(orgs,current),IEventBrandService
{
 protected override IEventRepository Repository=>repo;
 public async Task<EventBrandDto>GetAsync(Guid id,CancellationToken ct){var e=await Access(id,false,ct);var x=await repo.GetBrandConfigurationAsync(id,ct);var kit=await branding.GetKitAsync(e.OrganizationId,ct);return Map(id,x,kit);}
 public async Task<EventBrandDto>UpdateAsync(Guid id,UpdateEventBrandRequest r,CancellationToken ct){var e=await Access(id,true,ct);if(r.BrandProfileId.HasValue){var t=await branding.GetThemeAsync(r.BrandProfileId.Value,ct);if(t is null||t.OrganizationId!=e.OrganizationId)throw new NotFoundException("Brand profile not found.");}foreach(var a in new[]{r.LogoAssetId,r.BackgroundAssetId,r.WatermarkAssetId}.Where(x=>x.HasValue)){var asset=await repo.GetEventAssetAsync(a!.Value,ct);if(asset is null||asset.EventId!=id)throw new NotFoundException("Event asset not found.");}var x=await repo.GetBrandConfigurationAsync(id,ct);if(x is null){x=new(id);await repo.AddBrandConfigurationAsync(x,ct);}x.Update(r.BrandProfileId,r.LogoAssetId,r.BackgroundAssetId,r.WatermarkAssetId,r.EventDisplayName,r.PrimaryColor,r.SecondaryColor,r.AccentColor,r.FontFamily,r.ThemeMode,r.ThemeOverridesJson);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return await GetAsync(id,ct);}
 static EventBrandDto Map(Guid id,EventBrandConfiguration?x,BrandKit?k)=>new(id,x?.BrandProfileId,x?.LogoAssetId,x?.BackgroundAssetId,x?.WatermarkAssetId,x?.EventDisplayName,x?.PrimaryColor??k?.PrimaryColor??"#6C5CE7",x?.SecondaryColor??k?.SecondaryColor??"#15152C",x?.AccentColor??k?.AccentColor??"#00D2D3",x?.FontFamily??k?.PrimaryFont??"Inter",x?.ThemeMode??EventThemeMode.Inherit,x?.ThemeOverridesJson,x is null||x.BrandProfileId is null);
}
public sealed class EventExperienceService(IEventRepository repo,IOrganizationRepository orgs,ICurrentUserService current,IUnitOfWork uow):EventExperienceBase(orgs,current),IEventExperienceService
{
 protected override IEventRepository Repository=>repo;
 public async Task<EventExperienceDto>GetAsync(Guid id,CancellationToken ct){await Access(id,false,ct);var x=await repo.GetExperienceAsync(id,ct);return x is null?new(id,null,null,null,null,null,null,null,true,true,"{}"):Map(x);}
 public async Task<EventExperienceDto>UpdateAsync(Guid id,UpdateExperienceRequest r,CancellationToken ct){await Access(id,true,ct);if(r.WelcomeImageAssetId.HasValue){var a=await repo.GetEventAssetAsync(r.WelcomeImageAssetId.Value,ct);if(a is null||a.EventId!=id)throw new NotFoundException("Welcome image asset not found.");}var x=await repo.GetExperienceAsync(id,ct);if(x is null){x=new(id);await repo.AddExperienceAsync(x,ct);}x.Update(r.WelcomeTitle,r.WelcomeMessage,r.WelcomeImageAssetId,r.CaptureMessage,r.CompletionMessage,r.GalleryTitle,r.GalleryDescription,r.EnableDownload,r.EnableSharing,r.ConfigurationJson);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return Map(x);}static EventExperienceDto Map(EventExperienceSettings x)=>new(x.EventId,x.WelcomeTitle,x.WelcomeMessage,x.WelcomeImageAssetId,x.CaptureMessage,x.CompletionMessage,x.GalleryTitle,x.GalleryDescription,x.EnableDownload,x.EnableSharing,x.ConfigurationJson);
}
public sealed class EventAssetService(IEventRepository repo,IOrganizationRepository orgs,ICurrentUserService current,IStorageService storage,IUnitOfWork uow):EventExperienceBase(orgs,current),IEventAssetService
{
 protected override IEventRepository Repository=>repo;
 public async Task<IReadOnlyList<EventAssetDto>>ListAsync(Guid id,CancellationToken ct){await Access(id,false,ct);return(await repo.ListEventAssetsAsync(id,ct)).Select(Map).ToArray();}
 public async Task<EventAssetDto>UploadAsync(Guid id,EventAssetUpload r,CancellationToken ct){await Access(id,true,ct);if(r.Length<=0||r.Length>20*1024*1024)throw new ConflictException("Event assets must be between 1 byte and 20 MB.");if(!r.ContentType.StartsWith("image/",StringComparison.OrdinalIgnoreCase))throw new ConflictException("Only image event assets are supported.");var key=await storage.UploadAsync(r.Content,r.FileName,r.ContentType,ct);var x=new EventAsset(id,key,r.AssetType,r.DisplayName,r.ContentType,r.Length,r.DisplayOrder);await repo.AddEventAssetAsync(x,ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task ArchiveAsync(Guid id,Guid assetId,CancellationToken ct){await Access(id,true,ct);var x=await repo.GetEventAssetAsync(assetId,ct);if(x is null||x.EventId!=id)throw new NotFoundException("Event asset not found.");x.Archive(UserId);await uow.SaveChangesAsync(ct);}EventAssetDto Map(EventAsset x)=>new(x.Id,x.EventId,x.StorageAssetId,storage.GetUrl(x.StorageAssetId),x.AssetType,x.DisplayName,x.ContentType,x.FileSize,x.DisplayOrder,x.IsActive);
}
public sealed class EventSponsorService(IEventRepository repo,IOrganizationRepository orgs,ICurrentUserService current,IUnitOfWork uow):EventExperienceBase(orgs,current),IEventSponsorService
{
 protected override IEventRepository Repository=>repo;
 public async Task<IReadOnlyList<SponsorDto>>ListAsync(Guid id,CancellationToken ct){await Access(id,false,ct);return(await repo.ListSponsorsAsync(id,ct)).Select(Map).ToArray();}
 public async Task<SponsorDto>CreateAsync(Guid id,CreateSponsorRequest r,CancellationToken ct){await Access(id,true,ct);await Logo(id,r.LogoAssetId,ct);var x=new EventSponsor(id,r.Name,r.LogoAssetId,r.Website,r.DisplayOrder);await repo.AddSponsorAsync(x,ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task<SponsorDto>UpdateAsync(Guid id,Guid sid,UpdateSponsorRequest r,CancellationToken ct){await Access(id,true,ct);await Logo(id,r.LogoAssetId,ct);var x=await repo.GetSponsorAsync(sid,ct);if(x is null||x.EventId!=id)throw new NotFoundException("Sponsor not found.");x.Update(r.Name,r.LogoAssetId,r.Website,r.DisplayOrder,r.IsActive);x.MarkUpdated(UserId);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task ArchiveAsync(Guid id,Guid sid,CancellationToken ct){await Access(id,true,ct);var x=await repo.GetSponsorAsync(sid,ct);if(x is null||x.EventId!=id)throw new NotFoundException("Sponsor not found.");x.Archive(UserId);await uow.SaveChangesAsync(ct);}
 async Task Logo(Guid e,Guid id,CancellationToken ct){var a=await repo.GetEventAssetAsync(id,ct);if(a is null||a.EventId!=e||a.AssetType is not(EventAssetType.Logo or EventAssetType.SponsorLogo))throw new NotFoundException("Sponsor logo asset not found.");}static SponsorDto Map(EventSponsor x)=>new(x.Id,x.EventId,x.Name,x.LogoAssetId,x.Website,x.DisplayOrder,x.IsActive);
}
