#pragma warning disable CS9107
using System.Security.Cryptography;using EventLensAI.Application.Common;using EventLensAI.Application.DTOs.Storage;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Features.Photos.PhotoProcessing;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Services;
public interface IFileScanner{Task<FileScanResult>ScanAsync(Stream content,string fileName,CancellationToken ct);}public sealed record FileScanResult(bool Clean,string Scanner,string?Reason);
public interface IFileService{Task<PagedResult<StorageFileDto>>SearchAsync(StorageSearchRequest r,CancellationToken ct);Task<StorageFileDto>UploadAsync(StorageUpload upload,CancellationToken ct);Task<IReadOnlyList<StorageFileDto>>UploadManyAsync(IReadOnlyList<StorageUpload>uploads,CancellationToken ct);Task<StorageDownload>DownloadAsync(Guid org,Guid id,CancellationToken ct);Task<StorageDownload>PreviewAsync(Guid org,Guid id,CancellationToken ct);Task<StorageFileDto>UpdateAsync(Guid org,Guid id,UpdateStorageFileRequest r,CancellationToken ct);Task<StorageFileDto>CopyAsync(Guid org,Guid id,Guid?folderId,CancellationToken ct);Task ArchiveAsync(Guid org,Guid id,CancellationToken ct);Task RestoreAsync(Guid org,Guid id,CancellationToken ct);}
public interface IFolderService{Task<IReadOnlyList<StorageFolderDto>>ListAsync(Guid org,bool trash,CancellationToken ct);Task<StorageFolderDto>CreateAsync(Guid org,CreateStorageFolderRequest r,CancellationToken ct);Task<StorageFolderDto>RenameAsync(Guid org,Guid id,RenameStorageFolderRequest r,CancellationToken ct);Task<StorageFolderDto>MoveAsync(Guid org,Guid id,MoveStorageFolderRequest r,CancellationToken ct);Task ArchiveAsync(Guid org,Guid id,CancellationToken ct);Task RestoreAsync(Guid org,Guid id,CancellationToken ct);}
public interface IStorageQuotaService{Task<StorageDashboardDto>DashboardAsync(Guid org,CancellationToken ct);Task<IReadOnlyList<StorageCategoryDto>>CategoriesAsync(Guid org,CancellationToken ct);}
public abstract class StorageBase(IOrganizationRepository organizations,ICurrentUserService current){protected ICurrentUserService Current=>current;protected Guid UserId=>current.UserId??throw new UnauthorizedException("Authentication required.");protected async Task Read(Guid o,CancellationToken ct){if(current.Roles.Contains(SystemRoles.SuperAdmin))return;if(await organizations.GetMemberAsync(o,UserId,ct)is null)throw new UnauthorizedException("Organization access denied.");}protected async Task Write(Guid o,CancellationToken ct){if(current.Roles.Contains(SystemRoles.SuperAdmin))return;var m=await organizations.GetMemberAsync(o,UserId,ct)??throw new UnauthorizedException("Organization access denied.");if(m.Role.Name is not(SystemRoles.Owner or SystemRoles.Manager or SystemRoles.Photographer or SystemRoles.Designer))throw new UnauthorizedException("Storage write permission denied.");}}
public sealed class FileService(IStorageRepository repo,IOrganizationRepository organizations,ICurrentUserService current,IStorageService provider,IFileScanner scanner,IAuditRepository audits,IUnitOfWork uow):StorageBase(organizations,current),IFileService
{
 private const long MaxFile=250L*1024*1024;
 public async Task<PagedResult<StorageFileDto>>SearchAsync(StorageSearchRequest r,CancellationToken ct){await Read(r.OrganizationId,ct);var page=await repo.SearchAsync(r,ct);var items=new List<StorageFileDto>();foreach(var x in page.Items)items.Add(await Map(x,ct));return new(items,page.Page,page.PageSize,page.TotalCount);}
 public async Task<StorageFileDto>UploadAsync(StorageUpload r,CancellationToken ct){await Write(r.OrganizationId,ct);if(r.Length<=0||r.Length>MaxFile)throw new ConflictException("File must be between 1 byte and 250 MB.");var org=await repo.GetOrganizationAsync(r.OrganizationId,ct)??throw new NotFoundException("Organization not found.");await ValidateFolder(r.OrganizationId,r.FolderId,ct);var category=await repo.CategoryAsync(r.CategoryId,ct)??throw new NotFoundException("Category not found.");if(!r.Content.CanSeek)throw new ConflictException("Upload stream must be seekable.");var hash=Convert.ToHexString(await SHA256.HashDataAsync(r.Content,ct));r.Content.Position=0;if(await repo.ChecksumExistsAsync(r.OrganizationId,hash,ct))throw new ConflictException("This file already exists in the organization.");var scan=await scanner.ScanAsync(r.Content,r.FileName,ct);r.Content.Position=0;if(!scan.Clean)throw new ConflictException($"Upload rejected by {scan.Scanner}: {scan.Reason}");var totals=await repo.FileTotalsAsync(r.OrganizationId,ct);if(totals.Size+r.Length>org.StorageLimit)throw new ConflictException("Organization storage quota exceeded.");var key=await provider.UploadAsync(r.Content,r.FileName,r.ContentType,ct);var ext=Path.GetExtension(r.FileName).ToLowerInvariant();var x=new StorageFile(r.OrganizationId,r.FolderId,category.Id,Path.GetFileNameWithoutExtension(r.FileName),r.FileName,ext,r.ContentType,r.Length,key,hash,UserId,r.Visibility);x.MarkClean();await repo.AddFileAsync(x,ct);foreach(var tag in ParseTags(r.Tags))await repo.AddTagAsync(new FileTag(x.Id,tag),ct);org.AddStorage(r.Length);var usage=await Usage(org,ct);usage.Add(r.Length);await audits.AddAsync(new AuditLog(UserId,nameof(StorageFile),x.Id,AuditAction.Create,current.IPAddress),ct);await uow.SaveChangesAsync(ct);return await Map(x,ct);}
 public async Task<IReadOnlyList<StorageFileDto>>UploadManyAsync(IReadOnlyList<StorageUpload>r,CancellationToken ct){if(r.Count>20)throw new ConflictException("A maximum of 20 files is allowed per batch.");var result=new List<StorageFileDto>();foreach(var x in r)result.Add(await UploadAsync(x,ct));return result;}
 public async Task<StorageDownload>DownloadAsync(Guid o,Guid id,CancellationToken ct){await Read(o,ct);var x=await Scoped(o,id,false,ct);return new(await provider.OpenReadAsync(x.StorageKey,ct),x.MimeType,x.OriginalFileName);}
 public async Task<StorageDownload>PreviewAsync(Guid o,Guid id,CancellationToken ct){var x=await DownloadAsync(o,id,ct);if(!x.ContentType.StartsWith("image/")&&!x.ContentType.StartsWith("video/")&&x.ContentType!="application/pdf")throw new ConflictException("Preview is unavailable for this file type.");return x;}
 public async Task<StorageFileDto>UpdateAsync(Guid o,Guid id,UpdateStorageFileRequest r,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,false,ct);await ValidateFolder(o,r.FolderId,ct);if(await repo.CategoryAsync(r.CategoryId,ct)is null)throw new NotFoundException("Category not found.");x.Rename(r.FileName);x.Move(r.FolderId);x.SetCategory(r.CategoryId);x.SetDetails(r.Notes,r.Visibility);x.Favourite(r.IsFavourite);foreach(var tag in r.Tags.Distinct(StringComparer.OrdinalIgnoreCase))if(!(await repo.TagsAsync(id,ct)).Any(t=>t.Tag==tag.ToLowerInvariant()))await repo.AddTagAsync(new FileTag(id,tag),ct);await Save(x.Id,AuditAction.Update,ct);return await Map(x,ct);}
 public async Task<StorageFileDto>CopyAsync(Guid o,Guid id,Guid?folder,CancellationToken ct){await Write(o,ct);var source=await Scoped(o,id,false,ct);await ValidateFolder(o,folder,ct);var org=(await repo.GetOrganizationAsync(o,ct))!;var totals=await repo.FileTotalsAsync(o,ct);if(totals.Size+source.Size>org.StorageLimit)throw new ConflictException("Organization storage quota exceeded.");await using var input=await provider.OpenReadAsync(source.StorageKey,ct);var key=await provider.UploadAsync(input,source.OriginalFileName,source.MimeType,ct);var x=new StorageFile(o,folder,source.CategoryId,$"{source.FileName} Copy",source.OriginalFileName,source.Extension,source.MimeType,source.Size,key,source.Checksum+"-"+Guid.NewGuid().ToString("N"),UserId,source.Visibility);x.MarkClean();await repo.AddFileAsync(x,ct);org.AddStorage(source.Size);(await Usage(org,ct)).Add(source.Size);await Save(x.Id,AuditAction.Create,ct);return await Map(x,ct);}
 public async Task ArchiveAsync(Guid o,Guid id,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,false,ct);x.SoftDelete(UserId);var org=(await repo.GetOrganizationAsync(o,ct))!;org.AddStorage(-x.Size);(await Usage(org,ct)).Add(-x.Size);await Save(id,AuditAction.Archive,ct);}
 public async Task RestoreAsync(Guid o,Guid id,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,true,ct);if(!x.IsDeleted)return;var org=(await repo.GetOrganizationAsync(o,ct))!;var totals=await repo.FileTotalsAsync(o,ct);if(totals.Size+x.Size>org.StorageLimit)throw new ConflictException("Storage quota is insufficient to restore this file.");x.Restore(UserId);org.AddStorage(x.Size);(await Usage(org,ct)).Add(x.Size);await Save(id,AuditAction.Update,ct);}
 private async Task<StorageFile>Scoped(Guid o,Guid id,bool deleted,CancellationToken ct){var x=await repo.FileAsync(id,deleted,ct);return x is not null&&x.OrganizationId==o?x:throw new NotFoundException("File not found.");}
 private async Task ValidateFolder(Guid o,Guid?id,CancellationToken ct){if(id.HasValue){var x=await repo.FolderAsync(id.Value,false,ct);if(x is null||x.OrganizationId!=o)throw new NotFoundException("Folder not found.");}}
 private async Task<StorageUsage>Usage(Organization o,CancellationToken ct){var x=await repo.GetUsageAsync(o.Id,ct);if(x is not null){x.Allocate(o.StorageLimit);return x;}x=new StorageUsage(o.Id,o.StorageLimit);await repo.AddUsageAsync(x,ct);return x;}
 private async Task Save(Guid id,AuditAction action,CancellationToken ct){await audits.AddAsync(new AuditLog(UserId,nameof(StorageFile),id,action,Current.IPAddress),ct);await uow.SaveChangesAsync(ct);}
 private async Task<StorageFileDto>Map(StorageFile x,CancellationToken ct){var tags=(await repo.TagsAsync(x.Id,ct)).Select(t=>t.Tag).ToArray();return new(x.Id,x.OrganizationId,x.FolderId,x.FileName,x.OriginalFileName,x.Extension,x.MimeType,x.Size,x.Width,x.Height,x.Duration,x.Checksum,x.Category?.Name??"",x.Uploader is null?"":$"{x.Uploader.FirstName} {x.Uploader.LastName}",x.Visibility,x.IsFavourite,x.Notes,tags,x.CreatedAt,x.IsDeleted);}
 private static IEnumerable<string>ParseTags(string?x)=>string.IsNullOrWhiteSpace(x)?[]:x.Split(',',StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries).Distinct(StringComparer.OrdinalIgnoreCase);}
public sealed class FolderService(IStorageRepository repo,IOrganizationRepository organizations,ICurrentUserService current,IAuditRepository audits,IUnitOfWork uow):StorageBase(organizations,current),IFolderService
{public async Task<IReadOnlyList<StorageFolderDto>>ListAsync(Guid o,bool trash,CancellationToken ct){await Read(o,ct);return(await repo.FoldersAsync(o,trash,ct)).Select(Map).ToArray();}public async Task<StorageFolderDto>CreateAsync(Guid o,CreateStorageFolderRequest r,CancellationToken ct){await Write(o,ct);await Parent(o,r.ParentFolderId,null,ct);if(await repo.FolderNameExistsAsync(o,r.ParentFolderId,r.Name.Trim(),null,ct))throw new ConflictException("Folder name already exists.");var x=new StorageFolder(o,r.Name,r.ParentFolderId);await repo.AddFolderAsync(x,ct);await Save(x.Id,AuditAction.Create,ct);return Map(x);}public async Task<StorageFolderDto>RenameAsync(Guid o,Guid id,RenameStorageFolderRequest r,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,false,ct);if(await repo.FolderNameExistsAsync(o,x.ParentFolderId,r.Name.Trim(),id,ct))throw new ConflictException("Folder name already exists.");x.Rename(r.Name);await Save(id,AuditAction.Update,ct);return Map(x);}public async Task<StorageFolderDto>MoveAsync(Guid o,Guid id,MoveStorageFolderRequest r,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,false,ct);if(r.ParentFolderId==id)throw new ConflictException("A folder cannot contain itself.");await Parent(o,r.ParentFolderId,id,ct);x.Move(r.ParentFolderId);await Save(id,AuditAction.Update,ct);return Map(x);}public async Task ArchiveAsync(Guid o,Guid id,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,false,ct);if(await repo.HasChildrenAsync(id,ct))throw new ConflictException("Archive or move child folders first.");x.SoftDelete(UserId);await Save(id,AuditAction.Archive,ct);}public async Task RestoreAsync(Guid o,Guid id,CancellationToken ct){await Write(o,ct);var x=await Scoped(o,id,true,ct);x.Restore(UserId);await Save(id,AuditAction.Update,ct);}private async Task Parent(Guid o,Guid?p,Guid?moving,CancellationToken ct){var visited=new HashSet<Guid>();while(p.HasValue){if(!visited.Add(p.Value)||p==moving)throw new ConflictException("Folder cycle detected.");var x=await repo.FolderAsync(p.Value,false,ct);if(x is null||x.OrganizationId!=o)throw new NotFoundException("Parent folder not found.");p=x.ParentFolderId;}}private async Task<StorageFolder>Scoped(Guid o,Guid id,bool trash,CancellationToken ct){var x=await repo.FolderAsync(id,trash,ct);return x is not null&&x.OrganizationId==o?x:throw new NotFoundException("Folder not found.");}private async Task Save(Guid id,AuditAction a,CancellationToken ct){await audits.AddAsync(new AuditLog(UserId,nameof(StorageFolder),id,a,Current.IPAddress),ct);await uow.SaveChangesAsync(ct);}private static StorageFolderDto Map(StorageFolder x)=>new(x.Id,x.OrganizationId,x.ParentFolderId,x.Name,x.CreatedAt,x.IsDeleted);}
public sealed class StorageQuotaService(IStorageRepository repo,IBrandingRepository branding,IOrganizationRepository organizations,ICurrentUserService current):StorageBase(organizations,current),IStorageQuotaService
{public async Task<StorageDashboardDto>DashboardAsync(Guid o,CancellationToken ct){await Read(o,ct);var org=await repo.GetOrganizationAsync(o,ct)??throw new NotFoundException("Organization not found.");var totals=await repo.FileTotalsAsync(o,ct);var brandAssets=await branding.ListAssetsAsync(o,ct);var brandSize=brandAssets.Sum(x=>x.FileSize);var totalSize=totals.Size+brandSize;var totalCount=totals.Count+brandAssets.Count;var folders=(await repo.FoldersAsync(o,false,ct)).Count;var page=await repo.SearchAsync(new(o,null,null,null,null,null,null,null,null,false,1,100),ct);var rows=new List<StorageFileDto>();foreach(var x in page.Items){var tags=(await repo.TagsAsync(x.Id,ct)).Select(t=>t.Tag).ToArray();rows.Add(new(x.Id,x.OrganizationId,x.FolderId,x.FileName,x.OriginalFileName,x.Extension,x.MimeType,x.Size,x.Width,x.Height,x.Duration,x.Checksum,x.Category.Name,$"{x.Uploader.FirstName} {x.Uploader.LastName}",x.Visibility,x.IsFavourite,x.Notes,tags,x.CreatedAt,x.IsDeleted));}var by=(await repo.CategoryTotalsAsync(o,ct)).ToDictionary(x=>x.Category,x=>x.Size);if(brandSize>0)by["Brand Kit"]=brandSize;return new(org.StorageLimit,totalSize,Math.Max(0,org.StorageLimit-totalSize),totalCount,folders,by,rows.Take(10).ToArray(),rows.OrderByDescending(x=>x.Size).Take(10).ToArray());}public async Task<IReadOnlyList<StorageCategoryDto>>CategoriesAsync(Guid o,CancellationToken ct){await Read(o,ct);return(await repo.CategoriesAsync(ct)).Select(x=>new StorageCategoryDto(x.Id,x.Name,x.Type)).ToArray();}}
