"use client";
import{useEffect,useMemo,useRef}from"react";import{useMutation,useQuery}from"@tanstack/react-query";import{AppShell}from"../components/layout/AppShell";import{BrowserCameraManager}from"../features/camera-foundation/CameraManager";import{cameraFoundationApi}from"../features/camera-foundation/api";import{CameraCapabilities,CameraDiagnostics,CameraPreview,CameraSelector,CameraStatus,MirrorToggle,ResolutionSelector}from"../features/camera-foundation/components";import{useCameraFoundationStore}from"../features/camera-foundation/store";import{useAppStore}from"../store/useAppStore";import"../camera-foundation.css";
export default function BoothCamera(){
 const organizationId=useAppStore(s=>s.activeOrganizationId),runtime=useCameraFoundationStore(),videoRef=useRef<HTMLVideoElement|null>(null),manager=useMemo(()=>new BrowserCameraManager(),[]);
 const preference=useQuery({queryKey:["camera-preference",organizationId],queryFn:()=>cameraFoundationApi.preferences(organizationId),enabled:!!organizationId});
 const save=useMutation({mutationFn:cameraFoundationApi.save});
 useEffect(()=>manager.onChange((state,error)=>runtime.set({state,error:error??null})),[manager]);
 useEffect(()=>{void manager.initialize().then(devices=>runtime.set({devices}));},[manager]);
 useEffect(()=>{if(preference.data)runtime.set({selectedDeviceId:preference.data.preferredCameraId??"",resolution:preference.data.preferredResolution,mirror:preference.data.mirrorPreview,aspectRatio:preference.data.aspectRatio})},[preference.data]);
 useEffect(()=>()=>manager.destroy(),[manager]);
 async function refresh(){try{const devices=await manager.initialize();runtime.set({devices});await cameraFoundationApi.refresh(organizationId)}catch(error){runtime.set({state:"Error",error:{code:"UnknownError",message:"Camera discovery failed.",recovery:"Check browser permissions and retry.",technical:String(error)}})}}
 async function start(){if(!videoRef.current)return;try{const settings=await manager.startPreview(videoRef.current,runtime.selectedDeviceId,runtime.resolution);const devices=await manager.discover();runtime.set({settings,devices,capabilities:manager.getCapabilities(),state:"Streaming"});persist()}catch{}}
 async function switchCamera(id:string){runtime.set({selectedDeviceId:id});if(videoRef.current&&runtime.state==="Streaming")try{const settings=await manager.switchCamera(videoRef.current,id);runtime.set({settings,capabilities:manager.getCapabilities()})}catch{}persist({...runtime,selectedDeviceId:id})}
 function persist(value=runtime){if(!organizationId)return;save.mutate({organizationId,preferredCameraId:value.selectedDeviceId||null,preferredResolution:value.resolution,mirrorPreview:value.mirror,aspectRatio:value.aspectRatio})}
 async function fullscreen(){await videoRef.current?.parentElement?.requestFullscreen?.()}
 if(!organizationId)return <AppShell title="Camera foundation"><div className="camera-warning">Select an organization before configuring a camera.</div></AppShell>;
 return <AppShell title="Camera foundation"eyebrow="Booth engine · Phase 1"><div className="camera-page-head"><div><span>LIVE CAMERA MANAGEMENT</span><h2>Preview with confidence.</h2><p>Discover, test, and recover cameras before an event. This workspace never captures or uploads a frame.</p></div><CameraStatus state={runtime.state}settings={runtime.settings}/></div><div className="camera-workspace"><div><CameraPreview videoRef={videoRef}mirror={runtime.mirror}aspectRatio={runtime.aspectRatio}state={runtime.state}onStart={start}onPause={()=>manager.pausePreview()}onResume={()=>void manager.resumePreview()}onStop={()=>manager.stopPreview()}onRestart={start}onFullscreen={fullscreen}/><CameraCapabilities capabilities={runtime.capabilities}/></div><aside className="camera-control-panel"><header><span>PREVIEW SETUP</span><h2>Camera controls</h2><p>Changes are remembered for this organization.</p></header><CameraSelector devices={runtime.devices}value={runtime.selectedDeviceId}onChange={switchCamera}onRefresh={refresh}/><ResolutionSelector value={runtime.resolution}onChange={value=>{runtime.set({resolution:value});persist({...runtime,resolution:value})}}/><label className="camera-field"><span>Aspect ratio</span><select value={runtime.aspectRatio}onChange={e=>{runtime.set({aspectRatio:e.target.value});persist({...runtime,aspectRatio:e.target.value})}}><option>16:9</option><option>4:3</option><option>1:1</option></select></label><MirrorToggle checked={runtime.mirror}onChange={value=>{runtime.set({mirror:value});persist({...runtime,mirror:value})}}/><CameraDiagnostics devices={runtime.devices}state={runtime.state}error={runtime.error}/></aside></div></AppShell>
}
