"use client";
import{useEffect,useState}from"react";import{useMutation,useQuery,useQueryClient}from"@tanstack/react-query";import{AppShell}from"../components/layout/AppShell";import{eventApi}from"../features/events/api";import{boothFoundationApi}from"../features/booth-foundation/api";import{sessionEngineApi}from"../features/session-engine/api";import{IdleScreen,OperatorPanel,RecoveryDialog,SessionController,SessionStatus,SessionTimer}from"../features/session-engine/components";import{restoreSessionToken,useSessionEngineStore}from"../features/session-engine/store";import type{SessionType}from"../features/session-engine/types";import{useAppStore}from"../store/useAppStore";import"../session-engine.css";
export default function BoothSessionEngine(){
 const organizationId=useAppStore(s=>s.activeOrganizationId),store=useSessionEngineStore(),qc=useQueryClient(),[eventId,setEventId]=useState(""),[sessionType,setSessionType]=useState<SessionType>("Guest"),[,tick]=useState(0);
 const events=useQuery({queryKey:["session-events",organizationId],queryFn:()=>eventApi.list(`organizationId=${organizationId}&page=1&pageSize=100`),enabled:!!organizationId});
 const booth=useQuery({queryKey:["booth-configuration",organizationId],queryFn:()=>boothFoundationApi.configuration(organizationId),enabled:!!organizationId});
 const runtime=useQuery({queryKey:["booth-runtime",organizationId],queryFn:()=>sessionEngineApi.runtime(organizationId),enabled:!!organizationId,refetchInterval:15_000});
 const action=useMutation({mutationFn:({id,name}:{id:string;name:"start"|"pause"|"resume"|"complete"|"cancel"})=>sessionEngineApi[name](id),onSuccess:s=>store.setSession(s)});
 useEffect(()=>{if(runtime.data)store.setRuntime(runtime.data)},[runtime.data]);
 useEffect(()=>{if(!eventId&&events.data?.items[0])setEventId(events.data.items[0].id)},[events.data,eventId]);
 useEffect(()=>{const token=restoreSessionToken();if(token&&organizationId)void sessionEngineApi.recover(organizationId,token).then(s=>s&&store.setRecovery(s)).catch(()=>store.clear())},[organizationId]);
 useEffect(()=>{const activity=()=>store.touch();for(const name of["pointerdown","keydown","touchstart"]as const)window.addEventListener(name,activity,{passive:true});const timer=setInterval(()=>{tick(x=>x+1);const current=useSessionEngineStore.getState();if(current.session&&Date.now()-current.lastActivity>current.timeoutSeconds*1000){void sessionEngineApi.cancel(current.session.sessionId).catch(()=>{});void sessionEngineApi.reset(organizationId).catch(()=>{});current.clear();qc.invalidateQueries({queryKey:["booth-runtime",organizationId]})}},1000);return()=>{clearInterval(timer);for(const name of["pointerdown","keydown","touchstart"]as const)window.removeEventListener(name,activity)}},[organizationId,qc]);
 async function create(){if(!eventId||!booth.data)return;const created=await sessionEngineApi.create({organizationId,eventId,boothId:booth.data.id,sessionType,deviceInformation:JSON.stringify({platform:navigator.platform,language:navigator.language,online:navigator.onLine}),metadataJson:"{}"});store.setSession(await sessionEngineApi.start(created.sessionId));qc.invalidateQueries({queryKey:["booth-runtime",organizationId]})}
 async function reset(){if(store.session)await sessionEngineApi.cancel(store.session.sessionId).catch(()=>{});store.clear();store.setRuntime(await sessionEngineApi.reset(organizationId));}
 const activeEvent=events.data?.items.find(x=>x.id===eventId);
 if(!organizationId)return <AppShell title="Booth sessions"><div className="session-error">Select an organization first.</div></AppShell>;
 return <AppShell title="Booth sessions"eyebrow="Booth engine · Phase 2"><div className="session-page-head"><div><span>SESSION ORCHESTRATION</span><h2>One guest. One secure workflow.</h2><p>Control booth readiness, inactivity, recovery, and operator handoff without collecting media.</p></div><SessionStatus session={store.session}runtime={store.runtime}/></div><div className="session-layout"><main>{store.idle&&!store.session?<IdleScreen eventName={activeEvent?.name}onStart={create}/>:store.session&&<><SessionController session={store.session}onPause={()=>action.mutate({id:store.session!.sessionId,name:"pause"})}onResume={()=>action.mutate({id:store.session!.sessionId,name:"resume"})}onComplete={()=>action.mutate({id:store.session!.sessionId,name:"complete"})}/><section className="session-live"><div className="session-pulse"><span>✦</span><i/><b>Session workspace active</b><p>Future capture experiences will attach here.</p></div><SessionTimer startedAt={store.session.startedAt}lastActivityAt={store.session.lastActivityAt}/></section></>}<section className="session-foundation"><article><span>60s</span><div><b>Idle timeout</b><small>Returns to attract mode automatically</small></div></article><article><span>↻</span><div><b>Recovery ready</b><small>Secure token stored on this device</small></div></article><article><span>◎</span><div><b>Runtime synchronized</b><small>{store.runtime?.state||"Checking status"}</small></div></article></section></main><OperatorPanel sessionType={sessionType}setSessionType={setSessionType}status={store.session?.status}disabled={!eventId||!booth.data}onStart={create}onPause={()=>store.session&&action.mutate({id:store.session.sessionId,name:"pause"})}onResume={()=>store.session&&action.mutate({id:store.session.sessionId,name:"resume"})}onComplete={()=>store.session&&action.mutate({id:store.session.sessionId,name:"complete"})}onReset={reset}/><div className="session-event-select"><label>Active event<select value={eventId}onChange={e=>setEventId(e.target.value)}>{events.data?.items.map(x=><option key={x.id}value={x.id}>{x.name}</option>)}</select></label></div></div>{store.recovery&&<RecoveryDialog session={store.recovery}onRecover={()=>{store.setSession(store.recovery);store.setRecovery(null)}}onDiscard={store.clear}/>}</AppShell>
}
