"use client";
import{useEffect,useMemo,useRef,useState}from"react";import{useQuery}from"@tanstack/react-query";import{Link}from"react-router-dom";import{AppShell}from"../components/layout/AppShell";import{BrowserCameraManager}from"../features/camera-foundation/CameraManager";import{captureApi}from"../features/capture-engine/api";import{captureFrame,countdown,shutterSound,wait}from"../features/capture-engine/CaptureEngine";import{localCaptureStorage}from"../features/capture-engine/IndexedDbCaptureStorage";import{useCaptureStore}from"../features/capture-engine/store";import type{LocalCapture}from"../features/capture-engine/types";import{useSessionEngineStore}from"../features/session-engine/store";import"../capture-engine.css";
export default function BoothCapture(){
 const session=useSessionEngineStore(s=>s.session),store=useCaptureStore(),video=useRef<HTMLVideoElement>(null),manager=useMemo(()=>new BrowserCameraManager(),[]),abort=useRef<AbortController|null>(null),[ready,setReady]=useState(false),[burst,setBurst]=useState(false);
 const config=useQuery({queryKey:["capture-config",session?.organizationId,session?.eventId],queryFn:()=>captureApi.configuration(session!.organizationId,session!.eventId),enabled:!!session});
 useEffect(()=>{if(!session)return;void localCaptureStorage.list(session.sessionId).then(items=>useCaptureStore.setState({captures:items}));return()=>abort.current?.abort()},[session?.sessionId]);
 useEffect(()=>{if(!session||!video.current)return;manager.startPreview(video.current).then(()=>setReady(true)).catch(e=>store.setError(e instanceof Error?e.message:"Camera could not start."));return()=>manager.destroy()},[manager,session?.sessionId]);
 const save=async(n:number):Promise<LocalCapture>=>{const c=config.data!,frame=await captureFrame(video.current!,Number(c.imageQuality),c.mirrorImage);shutterSound();const key=`capture:${session!.sessionId}:${crypto.randomUUID()}`,item={key,sessionId:session!.sessionId,captureNumber:n,blob:frame.blob,capturedAt:new Date().toISOString(),metadataSaved:false};await localCaptureStorage.put(item);store.replace(n,item);try{await captureApi.register({organizationId:session!.organizationId,eventId:session!.eventId,sessionId:session!.sessionId,captureNumber:n,fileName:`capture-${n}.jpg`,localStorageKey:key,width:frame.width,height:frame.height,fileSize:frame.blob.size,mimeType:frame.blob.type});store.markSaved(key);return{...item,metadataSaved:true}}catch{return item}};
 const retry=async(item:LocalCapture)=>{try{const bitmap=await createImageBitmap(item.blob);await captureApi.register({organizationId:session.organizationId,eventId:session.eventId,sessionId:session.sessionId,captureNumber:item.captureNumber,fileName:`capture-${item.captureNumber}.jpg`,localStorageKey:item.key,width:bitmap.width,height:bitmap.height,fileSize:item.blob.size,mimeType:item.blob.type});bitmap.close();store.markSaved(item.key);await localCaptureStorage.put({...item,metadataSaved:true})}catch(e){store.setError(e instanceof Error?e.message:"Metadata retry failed.")}};
 const start=async()=>{if(!config.data||!ready)return;abort.current=new AbortController();store.setError(null);store.setState("preparing");try{for(let n=1;n<=config.data.numberOfPhotos;n++){store.setState("countdown");await countdown(n===1?config.data.countdownDuration:(burst?0:config.data.captureInterval),store.setCountdown,abort.current.signal);store.setState("capturing");await save(n);if(burst&&n<config.data.numberOfPhotos)await wait(350,abort.current.signal)}store.setCountdown(null);store.setState("completed")}catch(e){if((e as DOMException).name==="AbortError")store.setState("cancelled");else store.setError(e instanceof Error?e.message:"Capture failed. Retry when the camera is ready.")}};
 const cancel=()=>{abort.current?.abort();if(session)void captureApi.cancel({organizationId:session.organizationId,eventId:session.eventId,sessionId:session.sessionId}).catch(()=>{})};
 if(!session)return <AppShell eyebrow="PHOTO CAPTURE ENGINE" title="Capture photos"><section className="capture-empty"><h2>Start a booth session first</h2><p>Photo capture is attached to a secure, active event session.</p><Link to="/booth/session">Open booth sessions →</Link></section></AppShell>;
 return <AppShell eyebrow="PHOTO CAPTURE ENGINE" title="Capture photos"><div className="capture-layout"><section className="capture-stage"><video ref={video} playsInline muted className={config.data?.mirrorImage?"mirrored":""}/>{store.countdown!==null&&store.state==="countdown"&&<div className="countdown-overlay">{store.countdown||"Smile!"}</div>}<div className="capture-state">{ready?"CAMERA READY":"STARTING CAMERA"} · {store.state.toUpperCase()}</div></section><aside className="capture-controls"><small>SESSION {session.sessionToken.slice(0,8)}</small><h2>{burst?"Burst capture":"Guided capture"}</h2><p>{config.data?.numberOfPhotos??"—"} photos · {config.data?.countdownDuration??"—"} second countdown</p><label><input type="checkbox" checked={burst} onChange={e=>setBurst(e.target.checked)}/> Burst mode</label><button className="capture-primary" disabled={!ready||config.isLoading||["countdown","capturing","saving"].includes(store.state)} onClick={start}>Start capture</button><button onClick={cancel} disabled={!["countdown","capturing","saving"].includes(store.state)}>Cancel</button>{store.error&&<div className="form-error">{store.error}</div>}</aside></div><section className="capture-gallery"><header><div><small>LOCAL SESSION GALLERY</small><h2>Captured photos</h2></div><span>{store.captures.length} saved on this device</span></header><div>{store.captures.map(x=><article key={x.key}><img src={URL.createObjectURL(x.blob)} alt={`Capture ${x.captureNumber}`}/><footer><span>Photo {x.captureNumber}</span><i className={x.metadataSaved?"synced":"pending"}>{x.metadataSaved?"Metadata saved":"Metadata pending"}</i>{!x.metadataSaved&&<button onClick={()=>void retry(x)}>Retry metadata</button>}<button onClick={()=>{void localCaptureStorage.remove(x.key);useCaptureStore.setState(s=>({captures:s.captures.filter(y=>y.key!==x.key)}))}}>Retake</button></footer></article>)}</div></section></AppShell>
}
