"use client";
import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { AppShell } from "../components/layout/AppShell";
import { useAppStore } from "../store/useAppStore";

export default function Camera() {
  const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const [permission, setPermission] = useState<"idle"|"ready"|"error">("idle"); const [countdown, setCountdown] = useState(0);
  const [timer, setTimer] = useState(3); const [shots, setShots] = useState(4); const [captured, setCaptured] = useState<string[]>([]); const [shooting, setShooting] = useState(false);
  const [mirror, setMirror] = useState(true); const [style, setStyle] = useState("Natural");
  const setCaptures = useAppStore(state => state.setCaptures); const navigate = useNavigate();
  async function startCamera() { try { const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "user", width: { ideal: 1280 }, height: { ideal: 960 } }, audio: false }); streamRef.current = stream; if (videoRef.current) videoRef.current.srcObject = stream; setPermission("ready"); } catch { setPermission("error"); } }
  useEffect(() => () => streamRef.current?.getTracks().forEach(track => track.stop()), []);
  function snap() { const video = videoRef.current; if (!video) return ""; const canvas = document.createElement("canvas"); canvas.width = video.videoWidth || 960; canvas.height = video.videoHeight || 720; const ctx = canvas.getContext("2d")!; if (mirror) { ctx.translate(canvas.width, 0); ctx.scale(-1, 1); } ctx.filter = style === "Noir" ? "grayscale(1) contrast(1.25)" : style === "Vintage" ? "sepia(.55) saturate(.8)" : style === "Neon" ? "saturate(1.7) contrast(1.1)" : style === "Dreamy" ? "saturate(.8) brightness(1.12)" : "none"; ctx.drawImage(video, 0, 0, canvas.width, canvas.height); return canvas.toDataURL("image/jpeg", .9); }
  async function sequence() { if (permission !== "ready" || shooting) return; setShooting(true); const results: string[] = []; for (let shot = 0; shot < shots; shot++) { for (let left = timer; left > 0; left--) { setCountdown(left); await new Promise(resolve => setTimeout(resolve, 1000)); } setCountdown(0); const photo = snap(); if (photo) { results.push(photo); setCaptured([...results]); } await new Promise(resolve => setTimeout(resolve, 400)); } setCaptures(results); setShooting(false); }
  return <AppShell eyebrow="LIVE CAPTURE STUDIO" title="Camera"><div className="camera-layout"><section className="camera-stage"><div className="camera-feed"><video ref={videoRef} autoPlay playsInline muted className={mirror ? "mirrored" : ""} />{permission !== "ready" && <div className="camera-gate"><span>◉</span><h2>{permission === "error" ? "Camera access blocked" : "Ready when you are"}</h2><p>{permission === "error" ? "Allow camera access in your browser settings, then try again." : "Prism uses your camera only while this booth is open."}</p><button onClick={startCamera}>{permission === "error" ? "Try again" : "Enable camera"}</button></div>}{countdown > 0 && <div className="countdown">{countdown}</div>}<span className="camera-ready"><i /> {permission === "ready" ? "CAMERA READY" : "CAMERA OFF"}</span><div className="camera-bottom"><button onClick={() => setMirror(value => !value)}>↔</button><button className="shutter" onClick={sequence} disabled={permission !== "ready" || shooting} aria-label="Start photo sequence"><span /></button><button>{captured.length}/{shots}</button></div></div>{captured.length > 0 && <div className="capture-tray">{captured.map((photo, index) => <img src={photo} alt={`Capture ${index + 1}`} key={index} />)}<button onClick={() => navigate("/editor")}>Edit strip →</button></div>}</section><aside className="control-panel"><div className="panel-heading"><span>✦</span><div><h2>Set the mood</h2><p>Choose a live Canvas treatment.</p></div></div><div className="style-grid">{["Natural","Editorial","Neon","Noir","Dreamy","Vintage"].map((name,index)=><button className={style===name?"selected":""} onClick={()=>setStyle(name)} key={name}><span className={`style-preview s${index}`} />{name}</button>)}</div><div className="control-row"><span>Countdown</span><div>{[0,3,5].map(value=><button className={timer===value?"active":""} onClick={()=>setTimer(value)} key={value}>{value ? `${value}s` : "Off"}</button>)}</div></div><div className="control-row"><span>Multi-shot</span><div>{[1,3,4].map(value=><button className={shots===value?"active":""} onClick={()=>setShots(value)} key={value}>{value}</button>)}</div></div><div className="control-row"><span>Mirror preview</span><button className={`toggle ${mirror?"active":""}`} onClick={()=>setMirror(value=>!value)}><i /></button></div><div className="tip"><span>◎</span><p><strong>Photo-strip mode</strong>Each sequence becomes a print-ready vertical strip in the editor.</p></div></aside></div></AppShell>;
}
