"use client";
import { FormEvent, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { AppShell } from "../components/layout/AppShell";
import { teamApi, teamRoles } from "../features/organizations/teamApi";
import "../team.css";
import "../team-credentials.css";

const initials=(name:string)=>name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join("").toUpperCase();
export default function OrganizationTeam(){
 const {id=""}=useParams(),client=useQueryClient(); const [open,setOpen]=useState(false),[error,setError]=useState(""),[credentials,setCredentials]=useState<{email:string;password:string}|null>(null),[creating,setCreating]=useState(false);
 const members=useQuery({queryKey:["team",id],queryFn:()=>teamApi.members(id),enabled:!!id}); const invites=useQuery({queryKey:["invitations",id],queryFn:()=>teamApi.invitations(id),enabled:!!id}); const pending=invites.data?.filter(x=>x.status==="Pending")??[];
 const refresh=()=>Promise.all([client.invalidateQueries({queryKey:["team",id]}),client.invalidateQueries({queryKey:["invitations",id]})]); const close=()=>{setOpen(false);setCredentials(null);setError("");};
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");setCreating(true);const f=new FormData(e.currentTarget),email=String(f.get("email")),password=String(f.get("temporaryPassword"));try{await teamApi.createAccount(id,{firstName:String(f.get("firstName")),lastName:String(f.get("lastName")),email,temporaryPassword:password,role:String(f.get("role"))});setCredentials({email,password});await refresh();}catch(x){setError(x instanceof Error?x.message:"Account creation failed.");}finally{setCreating(false);}}
 async function changeRole(userId:string,role:string){try{await teamApi.role(id,userId,role);await refresh();}catch(x){setError(x instanceof Error?x.message:"Role update failed.");}} async function remove(userId:string){if(!confirm("Remove this member from the organization?"))return;try{await teamApi.remove(id,userId);await refresh();}catch(x){setError(x instanceof Error?x.message:"Remove failed.");}}
 return <AppShell title="Team management" eyebrow="Members · Roles · Invitations"><section className="team-hero"><div><span>Organization access</span><h2>Build the team behind every moment.</h2><p>Create secure member accounts, assign the appropriate role, and hand over a temporary password privately.</p></div><button className="team-invite-primary" onClick={()=>{setOpen(true);setError("");}}><span>＋</span>Create member</button></section><section className="team-stats"><article><span>Members</span><strong>{members.data?.length??0}</strong><small>Active collaborators</small></article><article><span>Pending</span><strong>{pending.length}</strong><small>Open invitations</small></article><article><span>Roles</span><strong>{new Set(members.data?.map(x=>x.role)).size}</strong><small>Access levels in use</small></article></section>{error&&!open&&<div className="form-error team-page-error">{error}</div>}
 <section className="team-panel"><header className="team-panel-heading"><div><span>People</span><h2>Organization members</h2></div><small>{members.data?.length??0} total</small></header>{members.isLoading&&<div className="team-loading">Loading team…</div>}<div className="team-member-list">{members.data?.map(m=>{const owner=m.role==="Owner";return <article className="team-member" key={m.id}><div className="team-person"><span className="team-avatar">{initials(m.name)}</span><div><strong>{m.name}</strong><small>{m.email}</small></div></div><div className="team-role"><label>Role</label><select value={m.role} disabled={owner} onChange={e=>void changeRole(m.userId,e.target.value)}>{[m.role,...teamRoles.filter(x=>x!==m.role)].map(x=><option key={x}>{x}</option>)}</select></div><div className="team-state"><label>Status</label><span><i/> {m.status}</span></div><div className="team-activity"><label>Last activity</label><span>{m.lastActivity?new Date(m.lastActivity).toLocaleDateString():"Never"}</span></div><button className="team-remove" disabled={owner} onClick={()=>void remove(m.userId)}>⋯</button></article>})}</div></section>
 <section className="team-panel team-invitations"><header className="team-panel-heading"><div><span>Onboarding</span><h2>Pending invitations</h2></div><small>{pending.length} pending</small></header>{pending.map(x=><article className="team-invite-row" key={x.id}><span className="team-mail">✉</span><div><strong>{x.email}</strong><small>Expires {new Date(x.expiresAt).toLocaleDateString()}</small></div><span className="team-role-pill">{x.role}</span><button onClick={async()=>{await teamApi.cancel(x.id);await refresh();}}>Cancel invite</button></article>)}{!invites.isLoading&&!pending.length&&<div className="team-empty"><span>✓</span><div><strong>No pending invitations</strong><p>New staff can be created directly with a temporary password.</p></div><button onClick={()=>setOpen(true)}>Create a member</button></div>}</section>
 {open&&<div className="modal-backdrop team-modal-backdrop" onClick={close}><form className="event-modal team-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><header><span>＋</span><div><small>New teammate</small><h2>Create member account</h2></div></header>{credentials?<div className="team-credentials"><div className="team-credentials-heading"><div><strong>Account ready</strong><p>Share these credentials securely. The member must replace the temporary password at first login.</p></div><button className="team-copy" type="button" onClick={()=>void navigator.clipboard.writeText(`Username: ${credentials.email}\nTemporary password: ${credentials.password}`)}>Copy credentials</button></div><div className="team-credential-grid"><label>Username<input readOnly value={credentials.email}/></label><label>Temporary password<input readOnly value={credentials.password}/></label></div></div>:<><p>Create their login and assign only the access they need.</p><div className="team-name-fields"><label>First name<input name="firstName" autoFocus required/></label><label>Last name<input name="lastName" required/></label></div><label>Email / username<input name="email" type="email" placeholder="name@company.com" required/></label><label>Temporary password<input name="temporaryPassword" type="text" minLength={12} placeholder="At least 12 characters" required/></label><small>Use uppercase, lowercase, number, and special character.</small><label>Organization role<select name="role">{teamRoles.map(x=><option key={x}>{x}</option>)}</select></label></>}{error&&<div className="form-error">{error}</div>}<div className="team-modal-actions"><button type="button" onClick={close}>{credentials?"Done":"Cancel"}</button>{!credentials&&<button disabled={creating}>{creating?"Creating…":"Create account"}</button>}</div></form></div>}</AppShell>;
}
