"use client";
import { useEffect, useRef, useState } from "react";
import { NavLink } from "react-router-dom";
import { AppShell } from "../components/layout/AppShell";
import { useAppStore } from "../store/useAppStore";

export default function PhotoEditor() {
  const captures = useAppStore(state => state.captures); const setActivePhoto = useAppStore(state => state.setActivePhoto);
  const canvasRef = useRef<HTMLCanvasElement>(null); const [brightness, setBrightness] = useState(100); const [contrast, setContrast] = useState(100); const [saturation, setSaturation] = useState(100); const [warmth, setWarmth] = useState(0); const [frame, setFrame] = useState("#f6efe5"); const [ai, setAi] = useState(false); const [busy, setBusy] = useState(false);
  const sources = captures.length ? captures : ["https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=1000&q=90"];
  useEffect(() => { const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d")!; const width=660, margin=30, photoH=380, gap=18; canvas.width=width; canvas.height=margin*2+sources.length*photoH+(sources.length-1)*gap+80; ctx.fillStyle=frame; ctx.fillRect(0,0,canvas.width,canvas.height); let loaded=0; sources.forEach((source,index)=>{ const image=new Image(); image.crossOrigin="anonymous"; image.onload=()=>{ ctx.save(); ctx.filter=`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%) sepia(${Math.max(0,warmth)}%) hue-rotate(${warmth<0?-12:0}deg)`; const ratio=Math.max((width-margin*2)/image.width,photoH/image.height); const w=image.width*ratio,h=image.height*ratio; ctx.drawImage(image,margin+(width-margin*2-w)/2,margin+index*(photoH+gap)+(photoH-h)/2,w,h); ctx.restore(); loaded++; if(loaded===sources.length){ ctx.fillStyle=frame==="#111111"?"#fff":"#241e2d"; ctx.font="700 22px sans-serif"; ctx.textAlign="center"; ctx.fillText("PRISM AI  •  KEEP THE MOMENT",width/2,canvas.height-34); setActivePhoto(canvas.toDataURL("image/jpeg",.92)); }}; image.src=source; }); }, [brightness,contrast,saturation,warmth,frame,captures]);
  function enhance(){ setBusy(true); setTimeout(()=>{setBrightness(106);setContrast(108);setSaturation(112);setWarmth(8);setAi(true);setBusy(false)},900); }
  function download(){ const link=document.createElement("a"); link.download="prism-photo-strip.jpg"; link.href=canvasRef.current?.toDataURL("image/jpeg",.95) ?? ""; link.click(); }
  return <AppShell eyebrow="CANVAS STRIP STUDIO" title="Photo Editor"><div className="editor-layout"><section className="editor-canvas"><canvas ref={canvasRef} className="strip-canvas" aria-label="Generated photo strip" />{captures.length===0&&<p className="editor-empty">Demo portrait shown. <NavLink to="/camera">Capture your own sequence.</NavLink></p>}</section><aside className="edit-panel"><div className="tabs"><button className="active">Enhance</button><button>Strip</button><button>Export</button></div><button className={`magic-box ai-action ${ai?"enhanced":""}`} onClick={enhance}><span>✦</span><div><strong>{busy?"Analyzing portrait…":ai?"AI enhancement applied":"Magic enhance"}</strong><p>Balances light, color, detail, and skin tone.</p></div><b>{ai?"✓":"→"}</b></button>{[["Brightness",brightness,setBrightness],["Contrast",contrast,setContrast],["Color",saturation,setSaturation],["Warmth",warmth,setWarmth]].map(([label,value,setter])=><label className="slider-row" key={String(label)}><span>{String(label)}<b>{String(value)}</b></span><input type="range" min={label==="Warmth"?-30:50} max={label==="Warmth"?30:150} value={Number(value)} onChange={event=>(setter as (n:number)=>void)(Number(event.target.value))} /></label>)}<div className="frame-picker"><span>Strip paper</span><div>{["#f6efe5","#ffffff","#ecc3d8","#a9d7ce","#111111"].map(color=><button key={color} className={frame===color?"selected":""} style={{background:color}} onClick={()=>setFrame(color)} aria-label={`Select ${color} strip`} />)}</div></div><div className="editor-actions"><button onClick={()=>{setBrightness(100);setContrast(100);setSaturation(100);setWarmth(0);setAi(false)}}>Reset</button><button className="export-btn" onClick={download}>Download strip <span>↓</span></button></div></aside></div></AppShell>;
}
