"use client";
import {FormEvent,useState} from "react";
import {Navigate,NavLink,useNavigate} from "react-router-dom";
import {Brand} from "../components/layout/AppShell";
import {apiRequest,type AuthSession} from "../lib/api";
import {useAppStore,type Organization} from "../store/useAppStore";
export default function Register(){
 const store=useAppStore(),navigate=useNavigate();const[error,setError]=useState(""),[busy,setBusy]=useState(false);
 if(store.authenticated)return <Navigate to="/dashboard" replace/>;
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=new FormData(event.currentTarget),password=String(form.get("password")),confirmPassword=String(form.get("confirmPassword"));if(password!==confirmPassword){setError("Passwords do not match.");setBusy(false);return}try{const session=await apiRequest<AuthSession>("/api/auth/register",{method:"POST",body:JSON.stringify({firstName:form.get("firstName"),lastName:form.get("lastName"),email:form.get("email"),phone:form.get("phone")||null,password,confirmPassword,acceptTerms:form.get("acceptTerms")==="on"})});store.setSession(session);const organization=await apiRequest<Organization>("/api/organizations",{method:"POST",body:JSON.stringify({name:form.get("organization"),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,primaryColor:"#7c3aed",secondaryColor:"#06b6d4"})});store.setOrganizations([organization]);navigate("/dashboard")}catch(reason){setError(reason instanceof Error?reason.message:"Registration failed.")}finally{setBusy(false)}}
 return <main className="auth-page dark"><div className="auth-brand"><Brand/></div><section className="auth-card"><span className="pill">CREATE YOUR STUDIO</span><h1>Start with EventLens.</h1><form onSubmit={submit}><label>First name<input name="firstName" required/></label><label>Last name<input name="lastName" required/></label><label>Organization<input name="organization" required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Phone<input name="phone" type="tel"/></label><label>Password<input name="password" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><small>At least 12 characters with uppercase, lowercase, number, and special character.</small><label>Confirm password<input name="confirmPassword" type="password" minLength={12} maxLength={128} autoComplete="new-password" required/></label><label className="terms-check"><input name="acceptTerms" type="checkbox" required/> I accept the Terms of Service and Privacy Policy.</label>{error&&<div className="form-error" role="alert">{error}</div>}<button disabled={busy}>{busy?"Creating…":"Create account →"}</button></form><NavLink to="/login">Already have an account?</NavLink></section></main>
}
