using EventLensAI.Domain.Entities;
using EventLensAI.Domain.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
namespace EventLensAI.Infrastructure.Persistence.Configurations;
internal static class BillingPlanIds{public static readonly Guid Free=Guid.Parse("20000000-0000-0000-0000-000000000001");public static readonly Guid Creator=Guid.Parse("20000000-0000-0000-0000-000000000002");public static readonly Guid Business=Guid.Parse("20000000-0000-0000-0000-000000000003");public static readonly Guid Enterprise=Guid.Parse("20000000-0000-0000-0000-000000000004");}
internal sealed class PlanDefinitionConfiguration:IEntityTypeConfiguration<PlanDefinition>{public void Configure(EntityTypeBuilder<PlanDefinition>b){b.ToTable("billing_plans");b.ConfigureBase();b.Property(x=>x.Plan).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Name).HasMaxLength(80);b.Property(x=>x.Currency).HasMaxLength(3);b.Property(x=>x.TemplateAccess).HasMaxLength(30);b.Property(x=>x.MonthlyPrice).HasPrecision(18,2);b.Property(x=>x.YearlyPrice).HasPrecision(18,2);b.HasIndex(x=>x.Plan).IsUnique();var created=new DateTime(2026,7,28,0,0,0,DateTimeKind.Utc);b.HasData(
 new{Id=BillingPlanIds.Free,Plan=SubscriptionPlan.Free,Name="Free",MonthlyPrice=0m,YearlyPrice=0m,Currency="USD",MaximumOrganizations=1,MaximumEvents=3,MaximumTeamMembers=1,MonthlyAICredits=10,StorageLimit=1_073_741_824L,GalleryLimit=1,TemplateAccess="Standard",CustomBranding=false,WhiteLabel=false,ApiAccess=false,CustomDomains=false,PrioritySupport=false,IsActive=true,CreatedAt=created,UpdatedAt=(DateTime?)null,CreatedBy=(Guid?)null,UpdatedBy=(Guid?)null,IsDeleted=false},
 new{Id=BillingPlanIds.Creator,Plan=SubscriptionPlan.Creator,Name="Creator",MonthlyPrice=19m,YearlyPrice=190m,Currency="USD",MaximumOrganizations=2,MaximumEvents=25,MaximumTeamMembers=3,MonthlyAICredits=250,StorageLimit=53_687_091_200L,GalleryLimit=25,TemplateAccess="Premium",CustomBranding=true,WhiteLabel=false,ApiAccess=false,CustomDomains=false,PrioritySupport=false,IsActive=true,CreatedAt=created,UpdatedAt=(DateTime?)null,CreatedBy=(Guid?)null,UpdatedBy=(Guid?)null,IsDeleted=false},
 new{Id=BillingPlanIds.Business,Plan=SubscriptionPlan.Business,Name="Business",MonthlyPrice=79m,YearlyPrice=790m,Currency="USD",MaximumOrganizations=10,MaximumEvents=200,MaximumTeamMembers=25,MonthlyAICredits=2500,StorageLimit=536_870_912_000L,GalleryLimit=1000,TemplateAccess="All",CustomBranding=true,WhiteLabel=false,ApiAccess=true,CustomDomains=false,PrioritySupport=true,IsActive=true,CreatedAt=created,UpdatedAt=(DateTime?)null,CreatedBy=(Guid?)null,UpdatedBy=(Guid?)null,IsDeleted=false},
 new{Id=BillingPlanIds.Enterprise,Plan=SubscriptionPlan.Enterprise,Name="Enterprise",MonthlyPrice=299m,YearlyPrice=2990m,Currency="USD",MaximumOrganizations=100,MaximumEvents=10000,MaximumTeamMembers=1000,MonthlyAICredits=25000,StorageLimit=2_199_023_255_552L,GalleryLimit=100000,TemplateAccess="All",CustomBranding=true,WhiteLabel=true,ApiAccess=true,CustomDomains=true,PrioritySupport=true,IsActive=true,CreatedAt=created,UpdatedAt=(DateTime?)null,CreatedBy=(Guid?)null,UpdatedBy=(Guid?)null,IsDeleted=false});}}
internal sealed class UsageCounterConfiguration:IEntityTypeConfiguration<UsageCounter>{public void Configure(EntityTypeBuilder<UsageCounter>b){b.ToTable("usage_counters");b.ConfigureBase();b.Property(x=>x.Metric).HasConversion<string>().HasMaxLength(40);b.HasIndex(x=>new{x.OrganizationId,x.PeriodStart,x.Metric}).IsUnique();}}
internal sealed class InvoiceConfiguration:IEntityTypeConfiguration<Invoice>{public void Configure(EntityTypeBuilder<Invoice>b){b.ToTable("invoices");b.ConfigureBase();b.Property(x=>x.InvoiceNumber).HasMaxLength(50);b.Property(x=>x.Customer).HasMaxLength(200);b.Property(x=>x.Plan).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Currency).HasMaxLength(3);b.Property(x=>x.Subtotal).HasPrecision(18,2);b.Property(x=>x.Amount).HasPrecision(18,2);b.Property(x=>x.Tax).HasPrecision(18,2);b.Property(x=>x.Discount).HasPrecision(18,2);b.HasIndex(x=>x.InvoiceNumber).IsUnique();b.HasIndex(x=>new{x.OrganizationId,x.IssueDate});}}
internal sealed class PaymentTransactionConfiguration:IEntityTypeConfiguration<PaymentTransaction>{public void Configure(EntityTypeBuilder<PaymentTransaction>b){b.ToTable("payment_transactions");b.ConfigureBase();b.Property(x=>x.Provider).HasMaxLength(50);b.Property(x=>x.ProviderReference).HasMaxLength(200);b.Property(x=>x.Currency).HasMaxLength(3);b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Amount).HasPrecision(18,2);b.Property(x=>x.RefundedAmount).HasPrecision(18,2);b.HasIndex(x=>new{x.Provider,x.ProviderReference}).IsUnique();b.HasIndex(x=>new{x.OrganizationId,x.CreatedAt});}}
internal sealed class BillingCouponConfiguration:IEntityTypeConfiguration<BillingCoupon>{public void Configure(EntityTypeBuilder<BillingCoupon>b){b.ToTable("billing_coupons");b.ConfigureBase();b.Property(x=>x.Code).HasMaxLength(50);b.Property(x=>x.DiscountType).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Value).HasPrecision(18,2);b.HasIndex(x=>new{x.Code,x.OrganizationId}).IsUnique();}}
internal sealed class BillingWebhookConfiguration:IEntityTypeConfiguration<BillingWebhook>{public void Configure(EntityTypeBuilder<BillingWebhook>b){b.ToTable("billing_webhooks");b.ConfigureBase();b.Property(x=>x.Provider).HasMaxLength(50);b.Property(x=>x.ExternalId).HasMaxLength(200);b.Property(x=>x.Type).HasConversion<string>().HasMaxLength(50);b.Property(x=>x.PayloadHash).HasMaxLength(64);b.Property(x=>x.Error).HasMaxLength(1000);b.HasIndex(x=>new{x.Provider,x.ExternalId}).IsUnique();}}
