using EventLensAI.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EventLensAI.Infrastructure.Persistence.Configurations;

internal sealed class GuestConfiguration : IEntityTypeConfiguration<Guest>
{
 public void Configure(EntityTypeBuilder<Guest>b){b.ToTable("guests");b.ConfigureBase();b.Property(x=>x.FirstName).HasMaxLength(100);b.Property(x=>x.LastName).HasMaxLength(100);b.Property(x=>x.Email).HasMaxLength(320);b.Property(x=>x.Phone).HasMaxLength(50);b.Property(x=>x.Company).HasMaxLength(200);b.Property(x=>x.JobTitle).HasMaxLength(150);b.Property(x=>x.Country).HasMaxLength(100);b.Property(x=>x.City).HasMaxLength(100);b.Property(x=>x.CustomFieldsJson).HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.OrganizationId,x.Email});b.HasQueryFilter(x=>!x.IsDeleted);}
}
internal sealed class LeadFormConfiguration:IEntityTypeConfiguration<LeadForm>{public void Configure(EntityTypeBuilder<LeadForm>b){b.ToTable("lead_forms");b.ConfigureBase();b.Property(x=>x.Name).HasMaxLength(200);b.Property(x=>x.SchemaJson).HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.OrganizationId,x.EventId});}}
internal sealed class LeadResponseConfiguration:IEntityTypeConfiguration<LeadResponse>{public void Configure(EntityTypeBuilder<LeadResponse>b){b.ToTable("lead_responses");b.ConfigureBase();b.Property(x=>x.ValuesJson).HasColumnType("nvarchar(max)");b.HasOne<LeadForm>().WithMany().HasForeignKey(x=>x.LeadFormId).OnDelete(DeleteBehavior.NoAction);b.HasOne<Guest>().WithMany().HasForeignKey(x=>x.GuestId).OnDelete(DeleteBehavior.NoAction);}}
internal sealed class GuestCheckInConfiguration:IEntityTypeConfiguration<GuestCheckIn>{public void Configure(EntityTypeBuilder<GuestCheckIn>b){b.ToTable("guest_check_ins");b.ConfigureBase();b.HasIndex(x=>new{x.EventId,x.GuestId}).IsUnique();b.HasOne<Guest>().WithMany().HasForeignKey(x=>x.GuestId).OnDelete(DeleteBehavior.NoAction);b.HasOne<Event>().WithMany().HasForeignKey(x=>x.EventId).OnDelete(DeleteBehavior.NoAction);}}
internal sealed class GuestActivityConfiguration:IEntityTypeConfiguration<GuestActivity>{public void Configure(EntityTypeBuilder<GuestActivity>b){b.ToTable("guest_activities");b.ConfigureBase();b.Property(x=>x.DataJson).HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.GuestId,x.CreatedAt});b.HasOne<Guest>().WithMany().HasForeignKey(x=>x.GuestId).OnDelete(DeleteBehavior.NoAction);}}
internal sealed class TagConfiguration:IEntityTypeConfiguration<Tag>{public void Configure(EntityTypeBuilder<Tag>b){b.ToTable("crm_tags");b.ConfigureBase();b.Property(x=>x.Name).HasMaxLength(100);b.HasIndex(x=>new{x.OrganizationId,x.Name}).IsUnique();}}
internal sealed class GuestTagConfiguration:IEntityTypeConfiguration<GuestTag>{public void Configure(EntityTypeBuilder<GuestTag>b){b.ToTable("guest_tags");b.HasKey(x=>new{x.GuestId,x.TagId});b.HasOne(x=>x.Guest).WithMany(x=>x.GuestTags).HasForeignKey(x=>x.GuestId).OnDelete(DeleteBehavior.Cascade);b.HasOne(x=>x.Tag).WithMany().HasForeignKey(x=>x.TagId).OnDelete(DeleteBehavior.Cascade);}}
internal sealed class SegmentConfiguration:IEntityTypeConfiguration<Segment>{public void Configure(EntityTypeBuilder<Segment>b){b.ToTable("segments");b.ConfigureBase();b.Property(x=>x.RulesJson).HasColumnType("nvarchar(max)");}}
internal sealed class CampaignConfiguration:IEntityTypeConfiguration<Campaign>{public void Configure(EntityTypeBuilder<Campaign>b){b.ToTable("campaigns");b.ConfigureBase();b.Property(x=>x.ContentJson).HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.OrganizationId,x.Status});}}
internal sealed class CampaignLogConfiguration:IEntityTypeConfiguration<CampaignLog>{public void Configure(EntityTypeBuilder<CampaignLog>b){b.ToTable("campaign_logs");b.ConfigureBase();b.HasIndex(x=>new{x.CampaignId,x.GuestId});}}
internal abstract class MessageConfiguration<T>:IEntityTypeConfiguration<T> where T:MarketingMessage{protected abstract string Table{get;} public void Configure(EntityTypeBuilder<T>b){b.ToTable(Table);b.ConfigureBase();b.Property(x=>x.Destination).HasMaxLength(320);b.Property(x=>x.Content).HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.OrganizationId,x.Status});}}
internal sealed class EmailConfiguration:MessageConfiguration<EmailMessage>{protected override string Table=>"emails";}
internal sealed class SmsConfiguration:MessageConfiguration<SmsMessage>{protected override string Table=>"sms";}
internal sealed class WhatsAppConfiguration:MessageConfiguration<WhatsAppMessage>{protected override string Table=>"whatsapp_messages";}
internal sealed class AutomationConfiguration:IEntityTypeConfiguration<Automation>{public void Configure(EntityTypeBuilder<Automation>b){b.ToTable("automations");b.ConfigureBase();b.Property(x=>x.ConditionsJson).HasColumnType("nvarchar(max)");}}
internal sealed class WorkflowStepConfiguration:IEntityTypeConfiguration<WorkflowStep>{public void Configure(EntityTypeBuilder<WorkflowStep>b){b.ToTable("workflow_steps");b.ConfigureBase();b.Property(x=>x.ConfigurationJson).HasColumnType("nvarchar(max)");b.HasIndex(x=>new{x.AutomationId,x.Order}).IsUnique();}}
internal sealed class SurveyConfiguration:IEntityTypeConfiguration<Survey>{public void Configure(EntityTypeBuilder<Survey>b){b.ToTable("surveys");b.ConfigureBase();b.Property(x=>x.QuestionsJson).HasColumnType("nvarchar(max)");}}
internal sealed class SurveyResponseConfiguration:IEntityTypeConfiguration<SurveyResponse>{public void Configure(EntityTypeBuilder<SurveyResponse>b){b.ToTable("survey_responses");b.ConfigureBase();b.Property(x=>x.AnswersJson).HasColumnType("nvarchar(max)");}}
internal sealed class CouponConfiguration:IEntityTypeConfiguration<Coupon>{public void Configure(EntityTypeBuilder<Coupon>b){b.ToTable("coupons");b.ConfigureBase();b.HasIndex(x=>new{x.OrganizationId,x.Code}).IsUnique();b.Property(x=>x.Value).HasPrecision(18,2);}}
internal sealed class ReferralConfiguration:IEntityTypeConfiguration<Referral>{public void Configure(EntityTypeBuilder<Referral>b){b.ToTable("referrals");b.ConfigureBase();b.HasIndex(x=>x.Code).IsUnique();b.Property(x=>x.RewardJson).HasColumnType("nvarchar(max)");}}
