using EventLensAI.Application.Common;using EventLensAI.Application.DTOs.Organizations;using EventLensAI.Application.Services;using EventLensAI.Domain.Enums;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace EventLensAI.API.Controllers;
[ApiController,Authorize(Policy="OrganizationRead"),Route("api/organizations/{organizationId:guid}/branding"),Produces("application/json")]
public sealed class BrandingController(IBrandKitService kit,IBrandAssetService assets,IBrandThemeService themes):ControllerBase
{
 [HttpGet]public async Task<ActionResult<ApiResponse<BrandKitDto>>>Get(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<BrandKitDto>.Ok(await kit.GetAsync(organizationId,ct)));
 [HttpPost]public async Task<ActionResult<ApiResponse<BrandKitDto>>>Create(Guid organizationId,UpdateBrandKitRequest r,CancellationToken ct)=>Ok(ApiResponse<BrandKitDto>.Ok(await kit.UpdateAsync(organizationId,r,ct),"Brand kit saved."));
 [HttpPut]public async Task<ActionResult<ApiResponse<BrandKitDto>>>Update(Guid organizationId,UpdateBrandKitRequest r,CancellationToken ct)=>Ok(ApiResponse<BrandKitDto>.Ok(await kit.UpdateAsync(organizationId,r,ct),"Brand kit updated."));
 [HttpDelete]public async Task<ActionResult<ApiResponse<object>>>Delete(Guid organizationId,CancellationToken ct){await kit.DeleteAsync(organizationId,ct);return Ok(ApiResponse<object>.Ok(new{},"Brand kit archived."));}
 [HttpPost("logos/{type}"),Consumes("multipart/form-data")]public async Task<ActionResult<ApiResponse<BrandKitDto>>>Logo(Guid organizationId,BrandLogoType type,IFormFile file,CancellationToken ct){await using var stream=file.OpenReadStream();return Ok(ApiResponse<BrandKitDto>.Ok(await kit.UploadLogoAsync(organizationId,type,new(file.FileName,file.ContentType,file.Length,stream),ct),"Logo uploaded."));}
 [HttpDelete("logos/{type}")]public async Task<ActionResult<ApiResponse<object>>>RemoveLogo(Guid organizationId,BrandLogoType type,CancellationToken ct){await kit.RemoveLogoAsync(organizationId,type,ct);return Ok(ApiResponse<object>.Ok(new{},"Logo removed."));}
 [HttpGet("assets")]public async Task<ActionResult<ApiResponse<IReadOnlyList<BrandAssetDto>>>>Assets(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<BrandAssetDto>>.Ok(await assets.ListAsync(organizationId,ct)));
 [HttpPost("assets"),Consumes("multipart/form-data")]public async Task<ActionResult<ApiResponse<BrandAssetDto>>>Upload(Guid organizationId,[FromForm]string name,[FromForm]BrandAssetType type,[FromForm]string?tags,IFormFile file,CancellationToken ct){await using var stream=file.OpenReadStream();return Ok(ApiResponse<BrandAssetDto>.Ok(await assets.UploadAsync(organizationId,name,type,tags,new(file.FileName,file.ContentType,file.Length,stream),ct),"Asset uploaded."));}
 [HttpGet("assets/{id:guid}/download")]public async Task<IActionResult>Download(Guid organizationId,Guid id,CancellationToken ct){var x=await assets.DownloadAsync(organizationId,id,ct);return File(x.Content,x.ContentType,x.FileName);}
 [HttpDelete("assets/{id:guid}")]public async Task<ActionResult<ApiResponse<object>>>DeleteAsset(Guid organizationId,Guid id,CancellationToken ct){await assets.DeleteAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"Asset archived."));}
 [HttpGet("themes")]public async Task<ActionResult<ApiResponse<IReadOnlyList<BrandThemeDto>>>>Themes(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<BrandThemeDto>>.Ok(await themes.ListAsync(organizationId,ct)));
 [HttpPost("themes")]public async Task<ActionResult<ApiResponse<BrandThemeDto>>>CreateTheme(Guid organizationId,CreateBrandThemeRequest r,CancellationToken ct)=>Ok(ApiResponse<BrandThemeDto>.Ok(await themes.CreateAsync(organizationId,r,ct),"Theme created."));
 [HttpPut("themes/{id:guid}")]public async Task<ActionResult<ApiResponse<BrandThemeDto>>>UpdateTheme(Guid organizationId,Guid id,UpdateBrandThemeRequest r,CancellationToken ct)=>Ok(ApiResponse<BrandThemeDto>.Ok(await themes.UpdateAsync(organizationId,id,r,ct),"Theme updated."));
 [HttpPost("themes/{id:guid}/duplicate")]public async Task<ActionResult<ApiResponse<BrandThemeDto>>>Duplicate(Guid organizationId,Guid id,DuplicateBrandThemeRequest r,CancellationToken ct)=>Ok(ApiResponse<BrandThemeDto>.Ok(await themes.DuplicateAsync(organizationId,id,r,ct),"Theme duplicated."));
 [HttpPost("themes/{id:guid}/activate")]public async Task<ActionResult<ApiResponse<object>>>Activate(Guid organizationId,Guid id,CancellationToken ct){await themes.ActivateAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"Theme activated."));}
 [HttpDelete("themes/{id:guid}")]public async Task<ActionResult<ApiResponse<object>>>ArchiveTheme(Guid organizationId,Guid id,CancellationToken ct){await themes.ArchiveAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"Theme archived."));}
}
