using EventLensAI.Application.Common;using EventLensAI.Application.Features.Entitlements;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace EventLensAI.API.Controllers;
[ApiController,Authorize,Route("api/entitlements"),Produces("application/json")]
public sealed class EntitlementsController(ISubscriptionService subscriptions,IEntitlementService entitlements,IUsageTrackingService usage):ControllerBase
{
 [AllowAnonymous,HttpGet("plans")]public async Task<ActionResult<ApiResponse<IReadOnlyList<EntitlementPlanDto>>>>Plans(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<EntitlementPlanDto>>.Ok(await subscriptions.PlansAsync(false,ct)));
 [AllowAnonymous,HttpGet("plans/{id:guid}")]public async Task<ActionResult<ApiResponse<EntitlementPlanDto>>>Plan(Guid id,CancellationToken ct)=>Ok(ApiResponse<EntitlementPlanDto>.Ok(await subscriptions.PlanAsync(id,ct)));
 [Authorize(Policy="SuperAdminOnly"),HttpGet("admin/plans")]public async Task<ActionResult<ApiResponse<IReadOnlyList<EntitlementPlanDto>>>>AdminPlans(CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<EntitlementPlanDto>>.Ok(await subscriptions.PlansAsync(true,ct)));
 [Authorize(Policy="SuperAdminOnly"),HttpPost("admin/plans")]public async Task<ActionResult<ApiResponse<EntitlementPlanDto>>>Create(SaveEntitlementPlanRequest r,CancellationToken ct)=>Ok(ApiResponse<EntitlementPlanDto>.Ok(await subscriptions.CreatePlanAsync(r,ct),"Plan created."));
 [Authorize(Policy="SuperAdminOnly"),HttpPut("admin/plans/{id:guid}")]public async Task<ActionResult<ApiResponse<EntitlementPlanDto>>>Update(Guid id,SaveEntitlementPlanRequest r,CancellationToken ct)=>Ok(ApiResponse<EntitlementPlanDto>.Ok(await subscriptions.UpdatePlanAsync(id,r,ct),"Plan updated."));
 [Authorize(Policy="SuperAdminOnly"),HttpDelete("admin/plans/{id:guid}")]public async Task<ActionResult<ApiResponse<object>>>Archive(Guid id,CancellationToken ct){await subscriptions.ArchivePlanAsync(id,ct);return Ok(ApiResponse<object>.Ok(new{},"Plan archived."));}
 [HttpGet("organizations/{organizationId:guid}/subscription")]public async Task<ActionResult<ApiResponse<OrganizationSubscriptionDto>>>Subscription(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<OrganizationSubscriptionDto>.Ok(await subscriptions.CurrentAsync(organizationId,ct)));
 [HttpPost("organizations/{organizationId:guid}/change-plan")]public async Task<ActionResult<ApiResponse<OrganizationSubscriptionDto>>>Change(Guid organizationId,ChangeEntitlementPlanRequest r,CancellationToken ct)=>Ok(ApiResponse<OrganizationSubscriptionDto>.Ok(await subscriptions.ChangePlanAsync(organizationId,r,ct),"Plan changed. No payment was processed."));
 [Authorize(Policy="SuperAdminOnly"),HttpPost("admin/organizations/{organizationId:guid}/assign-plan")]public async Task<ActionResult<ApiResponse<OrganizationSubscriptionDto>>>Assign(Guid organizationId,ChangeEntitlementPlanRequest r,CancellationToken ct)=>Ok(ApiResponse<OrganizationSubscriptionDto>.Ok(await subscriptions.AssignPlanAsync(organizationId,r,ct),"Plan assigned."));
 [HttpGet("organizations/{organizationId:guid}/usage")]public async Task<ActionResult<ApiResponse<UsageSummaryDto>>>Usage(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<UsageSummaryDto>.Ok(await usage.SummaryAsync(organizationId,ct)));
 [HttpPost("organizations/{organizationId:guid}/usage")]public async Task<ActionResult<ApiResponse<object>>>Track(Guid organizationId,TrackUsageRequest r,CancellationToken ct){await usage.TrackAsync(organizationId,r,ct);return Ok(ApiResponse<object>.Ok(new{},"Usage tracked."));}
 [HttpGet("organizations/{organizationId:guid}/check/{feature}")]public async Task<ActionResult<ApiResponse<EntitlementCheckDto>>>Check(Guid organizationId,string feature,CancellationToken ct)=>Ok(ApiResponse<EntitlementCheckDto>.Ok(await entitlements.CheckAsync(organizationId,feature,ct)));
}
