using EventLensAI.Application.Common;using EventLensAI.Application.DTOs.Storage;using EventLensAI.Application.Services;using EventLensAI.Domain.Enums;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace EventLensAI.API.Controllers;
[ApiController,Authorize,Route("api/storage"),Produces("application/json")]
public sealed class StorageController(IFileService files,IFolderService folders,IStorageQuotaService quota):ControllerBase
{
 [HttpGet("dashboard/{organizationId:guid}")]public async Task<ActionResult<ApiResponse<StorageDashboardDto>>>Dashboard(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<StorageDashboardDto>.Ok(await quota.DashboardAsync(organizationId,ct)));
 [HttpGet("categories/{organizationId:guid}")]public async Task<ActionResult<ApiResponse<IReadOnlyList<StorageCategoryDto>>>>Categories(Guid organizationId,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<StorageCategoryDto>>.Ok(await quota.CategoriesAsync(organizationId,ct)));
 [HttpGet("files")]public async Task<ActionResult<ApiResponse<PagedResult<StorageFileDto>>>>Search([FromQuery]StorageSearchRequest request,CancellationToken ct)=>Ok(ApiResponse<PagedResult<StorageFileDto>>.Ok(await files.SearchAsync(request,ct)));
 [HttpPost("files/upload"),Consumes("multipart/form-data")]public async Task<ActionResult<ApiResponse<StorageFileDto>>>Upload([FromForm]Guid organizationId,[FromForm]Guid?folderId,[FromForm]Guid categoryId,[FromForm]StorageVisibility visibility,[FromForm]string?tags,IFormFile file,CancellationToken ct){await using var stream=file.OpenReadStream();return Ok(ApiResponse<StorageFileDto>.Ok(await files.UploadAsync(new(organizationId,folderId,categoryId,visibility,tags,file.FileName,file.ContentType,file.Length,stream),ct),"File uploaded."));}
 [HttpPost("files/upload-multiple"),Consumes("multipart/form-data")]public async Task<ActionResult<ApiResponse<IReadOnlyList<StorageFileDto>>>>UploadMany([FromForm]Guid organizationId,[FromForm]Guid?folderId,[FromForm]Guid categoryId,[FromForm]StorageVisibility visibility,[FromForm]string?tags,List<IFormFile>uploads,CancellationToken ct){var results=new List<StorageFileDto>();foreach(var file in uploads){await using var stream=file.OpenReadStream();results.Add(await files.UploadAsync(new(organizationId,folderId,categoryId,visibility,tags,file.FileName,file.ContentType,file.Length,stream),ct));}return Ok(ApiResponse<IReadOnlyList<StorageFileDto>>.Ok(results,"Files uploaded."));}
 [HttpGet("files/{id:guid}/download")]public async Task<IActionResult>Download(Guid id,[FromQuery]Guid organizationId,CancellationToken ct){var x=await files.DownloadAsync(organizationId,id,ct);return File(x.Content,x.ContentType,x.FileName);}
 [HttpGet("files/{id:guid}/preview")]public async Task<IActionResult>Preview(Guid id,[FromQuery]Guid organizationId,CancellationToken ct){var x=await files.PreviewAsync(organizationId,id,ct);return File(x.Content,x.ContentType,enableRangeProcessing:true);}
 [HttpPut("files/{id:guid}")]public async Task<ActionResult<ApiResponse<StorageFileDto>>>Update(Guid id,[FromQuery]Guid organizationId,UpdateStorageFileRequest r,CancellationToken ct)=>Ok(ApiResponse<StorageFileDto>.Ok(await files.UpdateAsync(organizationId,id,r,ct),"File updated."));
 [HttpPost("files/{id:guid}/copy")]public async Task<ActionResult<ApiResponse<StorageFileDto>>>Copy(Guid id,[FromQuery]Guid organizationId,[FromBody]MoveStorageFolderRequest r,CancellationToken ct)=>Ok(ApiResponse<StorageFileDto>.Ok(await files.CopyAsync(organizationId,id,r.ParentFolderId,ct),"File copied."));
 [HttpDelete("files/{id:guid}")]public async Task<ActionResult<ApiResponse<object>>>Archive(Guid id,[FromQuery]Guid organizationId,CancellationToken ct){await files.ArchiveAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"File moved to trash."));}
 [HttpPost("files/{id:guid}/restore")]public async Task<ActionResult<ApiResponse<object>>>Restore(Guid id,[FromQuery]Guid organizationId,CancellationToken ct){await files.RestoreAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"File restored."));}
 [HttpGet("folders/{organizationId:guid}")]public async Task<ActionResult<ApiResponse<IReadOnlyList<StorageFolderDto>>>>Folders(Guid organizationId,[FromQuery]bool trash,CancellationToken ct)=>Ok(ApiResponse<IReadOnlyList<StorageFolderDto>>.Ok(await folders.ListAsync(organizationId,trash,ct)));
 [HttpPost("folders/{organizationId:guid}")]public async Task<ActionResult<ApiResponse<StorageFolderDto>>>CreateFolder(Guid organizationId,CreateStorageFolderRequest r,CancellationToken ct)=>Ok(ApiResponse<StorageFolderDto>.Ok(await folders.CreateAsync(organizationId,r,ct),"Folder created."));
 [HttpPut("folders/{id:guid}/rename")]public async Task<ActionResult<ApiResponse<StorageFolderDto>>>RenameFolder(Guid id,[FromQuery]Guid organizationId,RenameStorageFolderRequest r,CancellationToken ct)=>Ok(ApiResponse<StorageFolderDto>.Ok(await folders.RenameAsync(organizationId,id,r,ct),"Folder renamed."));
 [HttpPut("folders/{id:guid}/move")]public async Task<ActionResult<ApiResponse<StorageFolderDto>>>MoveFolder(Guid id,[FromQuery]Guid organizationId,MoveStorageFolderRequest r,CancellationToken ct)=>Ok(ApiResponse<StorageFolderDto>.Ok(await folders.MoveAsync(organizationId,id,r,ct),"Folder moved."));
 [HttpDelete("folders/{id:guid}")]public async Task<ActionResult<ApiResponse<object>>>ArchiveFolder(Guid id,[FromQuery]Guid organizationId,CancellationToken ct){await folders.ArchiveAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"Folder moved to trash."));}
 [HttpPost("folders/{id:guid}/restore")]public async Task<ActionResult<ApiResponse<object>>>RestoreFolder(Guid id,[FromQuery]Guid organizationId,CancellationToken ct){await folders.RestoreAsync(organizationId,id,ct);return Ok(ApiResponse<object>.Ok(new{},"Folder restored."));}
}
