using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Entitlements;
public sealed record EntitlementPlanDto(Guid Id,SubscriptionPlan Code,string Name,decimal MonthlyPrice,decimal YearlyPrice,string Description,bool IsActive,int DisplayOrder,IReadOnlyDictionary<string,bool>Features,IReadOnlyDictionary<string,long>Limits);
public sealed record SaveEntitlementPlanRequest(SubscriptionPlan Code,string Name,decimal MonthlyPrice,decimal YearlyPrice,string Description,int DisplayOrder,IReadOnlyDictionary<string,bool>Features,int MaximumEvents,int MaximumTeamMembers,long MaximumStorage,int MaximumGalleries,int MaximumAIJobs,int MaximumTemplates,int MaximumUploads,int MaximumMonthlyCaptures,int MaximumApiRequests);
public sealed record OrganizationSubscriptionDto(Guid Id,Guid OrganizationId,Guid PlanId,string PlanName,SubscriptionPlan Plan,EntitlementSubscriptionStatus Status,DateTime StartDate,DateTime?ExpiryDate,DateTime?TrialEnd,DateTime?RenewalDate);
public sealed record ChangeEntitlementPlanRequest(Guid PlanId,bool StartTrial=false,int?TrialDays=null);
public sealed record EntitlementCheckDto(string Feature,bool Allowed,long?Used,long?Limit,string?Reason);
public sealed record UsageSummaryDto(Guid OrganizationId,DateTime From,DateTime To,IReadOnlyDictionary<UsageMetric,long>Usage,IReadOnlyDictionary<UsageMetric,long>Limits);
public sealed record TrackUsageRequest(UsageMetric Metric,long Quantity,string?Reference);
public interface ISubscriptionService{Task<IReadOnlyList<EntitlementPlanDto>>PlansAsync(bool includeArchived,CancellationToken ct);Task<EntitlementPlanDto>PlanAsync(Guid id,CancellationToken ct);Task<EntitlementPlanDto>CreatePlanAsync(SaveEntitlementPlanRequest request,CancellationToken ct);Task<EntitlementPlanDto>UpdatePlanAsync(Guid id,SaveEntitlementPlanRequest request,CancellationToken ct);Task ArchivePlanAsync(Guid id,CancellationToken ct);Task<OrganizationSubscriptionDto>CurrentAsync(Guid organizationId,CancellationToken ct);Task<OrganizationSubscriptionDto>ChangePlanAsync(Guid organizationId,ChangeEntitlementPlanRequest request,CancellationToken ct);Task<OrganizationSubscriptionDto>AssignPlanAsync(Guid organizationId,ChangeEntitlementPlanRequest request,CancellationToken ct);}
public interface IEntitlementService{Task<EntitlementCheckDto>CheckAsync(Guid organizationId,string feature,CancellationToken ct);Task EnsureAsync(Guid organizationId,string feature,CancellationToken ct);Task EnsureUsageAsync(Guid organizationId,UsageMetric metric,long amount,CancellationToken ct);}
public interface IUsageTrackingService{Task TrackAsync(Guid organizationId,TrackUsageRequest request,CancellationToken ct);Task<UsageSummaryDto>SummaryAsync(Guid organizationId,CancellationToken ct);}
