using System.Collections.Concurrent;using AutoMapper;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Booth;
public sealed class MediaProcessingQueue:IMediaProcessingQueue
{
 readonly ConcurrentDictionary<Guid,MediaProcessingStatusDto>states=new();public MediaProcessingStatusDto Queue(Guid id)=>Set(new(id,MediaProcessingJobStatus.Queued,0,0,null));public MediaProcessingStatusDto Start(Guid id)=>Move(id,MediaProcessingJobStatus.Processing,10);public MediaProcessingStatusDto Complete(Guid id)=>Move(id,MediaProcessingJobStatus.Completed,100);public MediaProcessingStatusDto Fail(Guid id,string code)=>Set(Get(id)with{State=MediaProcessingJobStatus.Failed,ErrorCode=code});public MediaProcessingStatusDto Retry(Guid id)=>Set(Get(id)with{State=MediaProcessingJobStatus.Queued,Progress=0,Attempts=Get(id).Attempts+1,ErrorCode=null});public MediaProcessingStatusDto Cancel(Guid id)=>Set(Get(id)with{State=MediaProcessingJobStatus.Cancelled});public MediaProcessingStatusDto Get(Guid id)=>states.GetOrAdd(id,x=>new(x,MediaProcessingJobStatus.Queued,0,0,null));MediaProcessingStatusDto Move(Guid id,MediaProcessingJobStatus s,int progress)=>Set(Get(id)with{State=s,Progress=progress});MediaProcessingStatusDto Set(MediaProcessingStatusDto x){states[x.MediaId]=x;return x;}
}
public sealed class GifCaptureService:IGifCaptureService{public CaptureMode Mode=>CaptureMode.Gif;}public sealed class VideoCaptureService:IVideoCaptureService{public CaptureMode Mode=>CaptureMode.Video;}public sealed class BoomerangService:IBoomerangService{public CaptureMode Mode=>CaptureMode.Boomerang;}public sealed class TimeLapseService:ITimeLapseService{public CaptureMode Mode=>CaptureMode.TimeLapse;}
public sealed class MediaCaptureService(IMediaCaptureRepository repository,IBoothSessionEngineRepository sessions,IEventRepository events,IOrganizationRepository organizations,ICurrentUserService current,IUnitOfWork unit,IMapper mapper,IMediaProcessingQueue queue):BoothTenantService(organizations,current),IMediaCaptureService
{
 public async Task<CapturedMediaDto>StartAsync(MediaCaptureRequest r,CancellationToken ct){await Validate(r.OrganizationId,r.EventId,r.SessionId,ct);var x=new CapturedMedia(r.OrganizationId,r.EventId,r.SessionId,r.CaptureMode,r.FileName,r.LocalStorageKey,r.MimeType,r.Width,r.Height);await repository.AddAsync(x,ct);await repository.AddJobAsync(new(r.OrganizationId,x.Id),ct);queue.Queue(x.Id);await unit.SaveChangesAsync(ct);return mapper.Map<CapturedMediaDto>(x);}
 public async Task<CapturedMediaDto>StopAsync(Guid id,StopMediaRequest r,CancellationToken ct){var x=await Load(id,ct);x.Stop(r.Duration,r.FrameCount,r.FileSize);queue.Start(id);x.Complete();queue.Complete(id);await unit.SaveChangesAsync(ct);return mapper.Map<CapturedMediaDto>(x);}
 public async Task<CapturedMediaDto>CancelAsync(Guid id,CancellationToken ct){var x=await Load(id,ct);x.Cancel();queue.Cancel(id);await unit.SaveChangesAsync(ct);return mapper.Map<CapturedMediaDto>(x);}
 public async Task<IReadOnlyList<CapturedMediaDto>>ListAsync(Guid sessionId,CancellationToken ct){var s=await sessions.GetAsync(sessionId,ct)??throw new NotFoundException("Session was not found.");await Authorize(s.OrganizationId??Guid.Empty,false,ct);return(await repository.ListAsync(sessionId,ct)).Select(x=>mapper.Map<CapturedMediaDto>(x)).ToArray();}
 public async Task<MediaProcessingStatusDto>StatusAsync(Guid id,CancellationToken ct){await Load(id,ct);return queue.Get(id);}
 async Task<CapturedMedia>Load(Guid id,CancellationToken ct){var x=await repository.GetAsync(id,ct)??throw new NotFoundException("Captured media was not found.");await Validate(x.OrganizationId,x.EventId,x.SessionId,ct);return x;}
 async Task Validate(Guid org,Guid eventId,Guid sessionId,CancellationToken ct){await Authorize(org,true,ct);var e=await events.GetAsync(eventId,ct)??throw new NotFoundException("Event was not found.");var s=await sessions.GetAsync(sessionId,ct)??throw new NotFoundException("Session was not found.");if(e.OrganizationId!=org||s.EventId!=eventId||(s.OrganizationId.HasValue&&s.OrganizationId!=org))throw new UnauthorizedException("Media capture access denied.");}
}
