using System.Collections.Concurrent;using System.Text.Json;using AutoMapper;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;
namespace EventLensAI.Application.Features.Booth;
public sealed class CameraSettingsAuditService(ICameraControlRepository repository,ICurrentUserService current):ICameraSettingsAuditService{public Task RecordAsync(Guid org,Guid?profile,string previous,string next,CancellationToken ct)=>repository.AddHistoryAsync(new(org,profile,current.UserId??throw new UnauthorizedException("Operator identity is required."),previous,next),ct);}
public sealed class CameraControlService(IOrganizationRepository organizations,ICurrentUserService current,ICameraSettingsAuditService audit,IUnitOfWork unit):BoothTenantService(organizations,current),ICameraControlService
{
 static readonly ConcurrentDictionary<Guid,CameraControlSettingsDto>States=new();static CameraControlSettingsDto Default(Guid id)=>new(id,"1920x1080",null,"continuous",null,null,0,null,"Medium","Auto","Off",30);
 public async Task<IReadOnlyList<ProfessionalCameraCapabilityDto>>CapabilitiesAsync(Guid id,CancellationToken ct){await Authorize(id,false,ct);var s=States.GetOrAdd(id,Default);return[new("resolution",true,null,640,3840,1,["640x480","1280x720","1920x1080","3840x2160"]),new("frameRate",true,s.FrameRate,1,60,1,[]),new("zoom",false,s.Zoom,null,null,null,[]),new("focus",false,s.Focus,null,null,null,["continuous","manual"]),new("exposure",false,s.Exposure,null,null,null,["continuous","manual"]),new("brightness",false,s.Brightness,null,null,null,[]),new("contrast",false,null,null,null,null,["Low","Medium","High"]),new("whiteBalance",false,null,null,null,null,["Auto","Daylight","Cloudy","Fluorescent","Incandescent"]),new("torch",false,null,null,null,null,["Off","On","Auto"])];}
 public async Task<CameraControlSettingsDto>GetAsync(Guid id,CancellationToken ct){await Authorize(id,false,ct);return States.GetOrAdd(id,Default);}
 public async Task<CameraControlSettingsDto>UpdateAsync(UpdateCameraControlSettingsRequest r,Guid?profileId,CancellationToken ct){await Authorize(r.OrganizationId,true,ct);var old=States.GetOrAdd(r.OrganizationId,Default);var next=new CameraControlSettingsDto(r.OrganizationId,r.Resolution,r.Zoom,r.FocusMode,r.Focus,r.Exposure,r.ExposureCompensation,r.Brightness,r.Contrast,r.WhiteBalance,r.TorchMode,r.FrameRate);States[r.OrganizationId]=next;await audit.RecordAsync(r.OrganizationId,profileId,JsonSerializer.Serialize(old),JsonSerializer.Serialize(next),ct);await unit.SaveChangesAsync(ct);return next;}
 public Task<CameraControlSettingsDto>ResetAsync(Guid id,CancellationToken ct){var d=Default(id);return UpdateAsync(new(id,d.Resolution,d.Zoom,d.FocusMode,d.Focus,d.Exposure,d.ExposureCompensation,d.Brightness,d.Contrast,d.WhiteBalance,d.TorchMode,d.FrameRate),null,ct);}
}
public sealed class CameraProfileService(ICameraControlRepository repository,IOrganizationRepository organizations,ICurrentUserService currentUser,IUnitOfWork unit,IMapper mapper,ICameraControlService controls):BoothTenantService(organizations,currentUser),ICameraProfileService
{
 public async Task<IReadOnlyList<CameraProfileDto>>ListAsync(Guid org,CancellationToken ct){await Authorize(org,false,ct);return(await repository.ListAsync(org,ct)).Select(mapper.Map<CameraProfileDto>).ToArray();}
 public async Task<CameraProfileDto>CreateAsync(CreateCameraProfileRequest r,CancellationToken ct){await Authorize(r.OrganizationId,true,ct);var x=new CameraProfile(r.OrganizationId,r.Name,r.CameraType,r.Resolution,r.Zoom,r.Focus,r.Exposure,r.Brightness,r.Contrast,r.WhiteBalance,r.TorchEnabled);await repository.AddAsync(x,ct);await unit.SaveChangesAsync(ct);return mapper.Map<CameraProfileDto>(x);}
 public async Task<CameraProfileDto>UpdateAsync(Guid id,CreateCameraProfileRequest r,CancellationToken ct){var x=await Load(id,ct);if(x.OrganizationId!=r.OrganizationId)throw new UnauthorizedException("Profile access denied.");x.Update(r.Name,r.CameraType,r.Resolution,r.Zoom,r.Focus,r.Exposure,r.Brightness,r.Contrast,r.WhiteBalance,r.TorchEnabled);await unit.SaveChangesAsync(ct);return mapper.Map<CameraProfileDto>(x);}
 public async Task DeleteAsync(Guid id,CancellationToken ct){var x=await Load(id,ct);x.SoftDelete(null);await unit.SaveChangesAsync(ct);}
 public async Task<CameraControlSettingsDto>ApplyAsync(Guid id,CancellationToken ct){var x=await Load(id,ct);return await controls.UpdateAsync(new(x.OrganizationId,x.Resolution,x.Zoom,x.Focus.HasValue?"manual":"continuous",x.Focus,x.Exposure,0,x.Brightness,x.Contrast,x.WhiteBalance,x.TorchEnabled?"On":"Off",30),x.Id,ct);}
 async Task<CameraProfile>Load(Guid id,CancellationToken ct){var x=await repository.GetAsync(id,ct)??throw new NotFoundException("Camera profile was not found.");await Authorize(x.OrganizationId,true,ct);return x;}
}
