using EventLensAI.Domain.Entities;
namespace EventLensAI.Application.Features.Booth;
public sealed record ProfessionalCameraCapabilityDto(string Name,bool Supported,double?CurrentValue,double?Minimum,double?Maximum,double?Step,IReadOnlyList<string>Values);
public sealed record CameraControlSettingsDto(Guid OrganizationId,string Resolution,double?Zoom,string FocusMode,double?Focus,double?Exposure,double?ExposureCompensation,double?Brightness,string Contrast,string WhiteBalance,string TorchMode,double?FrameRate);
public sealed record UpdateCameraControlSettingsRequest(Guid OrganizationId,string Resolution,double?Zoom,string FocusMode,double?Focus,double?Exposure,double?ExposureCompensation,double?Brightness,string Contrast,string WhiteBalance,string TorchMode,double?FrameRate);
public sealed record CameraProfileDto(Guid Id,Guid OrganizationId,string Name,string CameraType,string Resolution,double?Zoom,double?Focus,double?Exposure,double?Brightness,string Contrast,string WhiteBalance,bool TorchEnabled,DateTime CreatedAt,DateTime?UpdatedAt);
public sealed record CreateCameraProfileRequest(Guid OrganizationId,string Name,string CameraType,string Resolution,double?Zoom,double?Focus,double?Exposure,double?Brightness,string Contrast,string WhiteBalance,bool TorchEnabled);
public interface ICameraControlService{Task<IReadOnlyList<ProfessionalCameraCapabilityDto>>CapabilitiesAsync(Guid organizationId,CancellationToken ct);Task<CameraControlSettingsDto>GetAsync(Guid organizationId,CancellationToken ct);Task<CameraControlSettingsDto>UpdateAsync(UpdateCameraControlSettingsRequest request,Guid?profileId,CancellationToken ct);Task<CameraControlSettingsDto>ResetAsync(Guid organizationId,CancellationToken ct);}
public interface ICameraProfileService{Task<IReadOnlyList<CameraProfileDto>>ListAsync(Guid organizationId,CancellationToken ct);Task<CameraProfileDto>CreateAsync(CreateCameraProfileRequest request,CancellationToken ct);Task<CameraProfileDto>UpdateAsync(Guid id,CreateCameraProfileRequest request,CancellationToken ct);Task DeleteAsync(Guid id,CancellationToken ct);Task<CameraControlSettingsDto>ApplyAsync(Guid id,CancellationToken ct);}
public interface ICameraSettingsAuditService{Task RecordAsync(Guid organizationId,Guid?profileId,string previousValue,string newValue,CancellationToken ct);}
public interface ICameraControlRepository{Task<IReadOnlyList<CameraProfile>>ListAsync(Guid organizationId,CancellationToken ct);Task<CameraProfile?>GetAsync(Guid id,CancellationToken ct);Task AddAsync(CameraProfile value,CancellationToken ct);Task AddHistoryAsync(CameraSettingsHistory value,CancellationToken ct);}
