using System.Collections.Concurrent;using AutoMapper;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Booth;
public sealed class CountdownService:ICountdownService
{public IReadOnlyList<CountdownEventDto>Create(int seconds){if(seconds is<0 or>30)throw new ConflictException("Countdown must be between 0 and 30 seconds.");var now=DateTime.UtcNow;var values=new List<CountdownEventDto>{new("CountdownStarted",seconds,now)};for(var i=seconds;i>0;i--)values.Add(new("CountdownTick",i,now.AddSeconds(seconds-i)));values.Add(new("CountdownCompleted",null,now.AddSeconds(seconds)));return values;}}
public sealed class CaptureQueueService:ICaptureQueueService
{
 private readonly ConcurrentDictionary<Guid,CaptureStatusDto>states=new();
 public CaptureStatusDto Prepare(Guid id,int target)=>Move(id,CaptureWorkflowState.Preparing,0,target,null,CaptureWorkflowState.Idle);
 public CaptureStatusDto Countdown(Guid id)=>Transition(id,CaptureWorkflowState.Countdown,CaptureWorkflowState.Preparing);
 public CaptureStatusDto Capturing(Guid id)=>Transition(id,CaptureWorkflowState.Capturing,CaptureWorkflowState.Countdown,CaptureWorkflowState.Preparing);
 public CaptureStatusDto Saved(Guid id){var c=Get(id);if(c.State!=CaptureWorkflowState.Capturing)throw new ConflictException("Capture queue is not capturing.");var count=c.CapturedCount+1;return Set(c with{CapturedCount=count,State=count>=c.TargetCount?CaptureWorkflowState.Completed:CaptureWorkflowState.Preparing,ChangedAt=DateTime.UtcNow});}
 public CaptureStatusDto Fail(Guid id,string error)=>Set(Get(id)with{State=CaptureWorkflowState.Failed,ErrorCode=error,ChangedAt=DateTime.UtcNow});
 public CaptureStatusDto Cancel(Guid id)=>Set(Get(id)with{State=CaptureWorkflowState.Cancelled,ChangedAt=DateTime.UtcNow});
 public CaptureStatusDto Get(Guid id)=>states.GetOrAdd(id,x=>new(x,CaptureWorkflowState.Idle,0,0,null,DateTime.UtcNow));
 private CaptureStatusDto Transition(Guid id,CaptureWorkflowState next,params CaptureWorkflowState[]allowed){var c=Get(id);if(!allowed.Contains(c.State))throw new ConflictException($"Cannot move capture from {c.State} to {next}.");return Set(c with{State=next,ChangedAt=DateTime.UtcNow});}
 private CaptureStatusDto Move(Guid id,CaptureWorkflowState next,int count,int target,string?error,params CaptureWorkflowState[]allowed){var c=Get(id);if(!allowed.Contains(c.State)&&c.State is not(CaptureWorkflowState.Completed or CaptureWorkflowState.Cancelled or CaptureWorkflowState.Failed))throw new ConflictException($"Cannot move capture from {c.State} to {next}.");return Set(new(id,next,count,target,error,DateTime.UtcNow));}
 private CaptureStatusDto Set(CaptureStatusDto value){states[value.SessionId]=value;return value;}
}
public sealed class LocalCaptureStorageService:ILocalCaptureStorageService{public string Provider=>"Browser IndexedDB";public bool UploadEnabled=>false;}
public sealed class CaptureService(ICaptureEngineRepository repository,IBoothSessionEngineRepository sessions,IEventRepository events,IOrganizationRepository organizations,ICurrentUserService current,IUnitOfWork unitOfWork,IMapper mapper,ICaptureQueueService queue):BoothTenantService(organizations,current),ICaptureService
{
 public async Task<CaptureConfigurationDto>GetConfigurationAsync(Guid org,Guid eventId,CancellationToken ct){await Validate(org,eventId,null,false,ct);var value=await repository.GetConfigurationAsync(org,eventId,ct)??new CaptureConfiguration(org,eventId);return mapper.Map<CaptureConfigurationDto>(value);}
 public async Task<CaptureConfigurationDto>UpdateConfigurationAsync(UpdateCaptureConfigurationRequest r,CancellationToken ct){await Validate(r.OrganizationId,r.EventId,null,true,ct);var value=await repository.GetConfigurationAsync(r.OrganizationId,r.EventId,ct);if(value is null){value=new CaptureConfiguration(r.OrganizationId,r.EventId);await repository.AddConfigurationAsync(value,ct);}value.Update(r.CountdownDuration,r.NumberOfPhotos,r.CaptureInterval,r.ImageQuality,r.Resolution,r.MirrorImage,r.AutoCaptureEnabled);await unitOfWork.SaveChangesAsync(ct);return mapper.Map<CaptureConfigurationDto>(value);}
 public async Task<CapturedPhotoDto>RegisterAsync(StartCaptureRequest r,CancellationToken ct){await Validate(r.OrganizationId,r.EventId,r.SessionId,true,ct);var status=queue.Get(r.SessionId);if(status.State==CaptureWorkflowState.Idle){var config=await repository.GetConfigurationAsync(r.OrganizationId,r.EventId,ct)??new CaptureConfiguration(r.OrganizationId,r.EventId);queue.Prepare(r.SessionId,config.NumberOfPhotos);queue.Capturing(r.SessionId);}else if(status.State==CaptureWorkflowState.Preparing)queue.Capturing(r.SessionId);var photo=new CapturedPhoto(r.OrganizationId,r.EventId,r.SessionId,r.CaptureNumber,r.FileName,r.LocalStorageKey,r.Width,r.Height,r.FileSize,r.MimeType);await repository.AddPhotoAsync(photo,ct);await unitOfWork.SaveChangesAsync(ct);queue.Saved(r.SessionId);return mapper.Map<CapturedPhotoDto>(photo);}
 public async Task<CaptureStatusDto>CancelAsync(CancelCaptureRequest r,CancellationToken ct){await Validate(r.OrganizationId,r.EventId,r.SessionId,true,ct);return queue.Cancel(r.SessionId);}
 public async Task<CaptureStatusDto>GetStatusAsync(Guid org,Guid sessionId,CancellationToken ct){var session=await sessions.GetAsync(sessionId,ct)??throw new NotFoundException("Session was not found.");await Validate(org,session.EventId,sessionId,false,ct);return queue.Get(sessionId);}
 public async Task<IReadOnlyList<CapturedPhotoDto>>ListAsync(Guid sessionId,CancellationToken ct){var session=await sessions.GetAsync(sessionId,ct)??throw new NotFoundException("Session was not found.");await Validate(session.OrganizationId??Guid.Empty,session.EventId,sessionId,false,ct);return(await repository.ListAsync(sessionId,ct)).Select(x=>mapper.Map<CapturedPhotoDto>(x)).ToArray();}
 private async Task Validate(Guid org,Guid eventId,Guid?sessionId,bool write,CancellationToken ct){await Authorize(org,write,ct);var e=await events.GetAsync(eventId,ct)??throw new NotFoundException("Event was not found.");if(e.OrganizationId!=org)throw new UnauthorizedException("Event access denied.");if(sessionId.HasValue){var s=await sessions.GetAsync(sessionId.Value,ct)??throw new NotFoundException("Session was not found.");if(s.EventId!=eventId||(s.OrganizationId.HasValue&&s.OrganizationId!=org))throw new UnauthorizedException("Session access denied.");}}
}
