using EventLensAI.Application.Exceptions;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Booth;
public sealed class BoothExperienceService(IGuestExperienceRepository repo,IEventRepository events,IOrganizationRepository orgs,ICurrentUserService current,IUnitOfWork uow):IBoothExperienceService
{
 public async Task<BoothExperienceDto>GetAsync(Guid eventId,CancellationToken ct){var e=await events.GetAsync(eventId,ct)??throw new NotFoundException("Event not found.");var c=await repo.ConfigurationAsync(eventId,ct)??new BoothExperienceConfiguration(e.OrganizationId,eventId,$"Welcome to {e.Name}",60,"Corporate","en",true,true,BoothAnimationType.Gradient,null);return new(eventId,e.Name,Map(c));}
 public async Task<GuestBoothConfigurationDto>UpdateAsync(Guid eventId,SaveBoothExperienceConfigurationRequest r,CancellationToken ct){var e=await events.GetAsync(eventId,ct)??throw new NotFoundException("Event not found.");var uid=current.UserId??throw new UnauthorizedException("Authentication required.");if(await orgs.GetMemberAsync(e.OrganizationId,uid,ct)is null)throw new UnauthorizedException("Event access denied.");var c=await repo.ConfigurationAsync(eventId,ct);if(c is null){c=new BoothExperienceConfiguration(e.OrganizationId,eventId,r.WelcomeMessage,r.AttractTimeout,r.Theme,r.Language,r.SoundEnabled,r.FullscreenEnabled,r.AnimationType,r.BackgroundMedia);await repo.AddConfigurationAsync(c,ct);}else c.Update(r.WelcomeMessage,r.AttractTimeout,r.Theme,r.Language,r.SoundEnabled,r.FullscreenEnabled,r.AnimationType,r.BackgroundMedia);await uow.SaveChangesAsync(ct);return Map(c);}
 static GuestBoothConfigurationDto Map(BoothExperienceConfiguration x)=>new(x.EventId,x.WelcomeMessage,x.AttractTimeout,x.Theme,x.Language,x.SoundEnabled,x.FullscreenEnabled,x.AnimationType,x.BackgroundMedia);
}
public sealed class GuestJourneyService(IGuestExperienceRepository repo,IEventRepository events,IUnitOfWork uow):IGuestJourneyService,IBoothRecoveryService
{
 public async Task<GuestJourneyStateDto>StartAsync(StartGuestJourneyRequest r,CancellationToken ct){var e=await events.GetAsync(r.EventId,ct)??throw new NotFoundException("Event not found.");if(e.Status is EventStatus.Cancelled or EventStatus.Archived)throw new ConflictException("This booth experience is unavailable.");var x=new GuestBoothSession(e.OrganizationId,e.Id,r.BoothSessionId);await repo.AddSessionAsync(x,ct);await repo.AddLogAsync(new(e.OrganizationId,e.Id,x.Id,GuestBoothState.Attract,GuestBoothState.Attract,"Journey started"),ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task<GuestJourneyStateDto>TransitionAsync(TransitionGuestJourneyRequest r,CancellationToken ct){var x=await Secure(r.SessionId,r.RecoveryToken,ct);var from=x.State;if(r.SelectedMode.HasValue)x.SelectMode(r.SelectedMode.Value);try{x.Transition(r.NextState);}catch(InvalidOperationException ex){throw new ConflictException(ex.Message);}await repo.AddLogAsync(new(x.OrganizationId,x.EventId,x.Id,from,r.NextState,r.Reason??"Guest transition"),ct);await uow.SaveChangesAsync(ct);return Map(x);}
 public async Task<GuestJourneyStateDto>StateAsync(Guid id,string token,CancellationToken ct)=>Map(await Secure(id,token,ct));
 public async Task<GuestJourneyStateDto?>RecoverAsync(RecoverGuestJourneyRequest r,CancellationToken ct){var x=await repo.SessionAsync(r.SessionId,ct);if(x is null||!FixedTimeEquals(x.RecoveryToken,r.RecoveryToken))return null;return Map(x);}
 async Task<GuestBoothSession>Secure(Guid id,string token,CancellationToken ct){var x=await repo.SessionAsync(id,ct)??throw new NotFoundException("Guest session not found.");if(!FixedTimeEquals(x.RecoveryToken,token))throw new UnauthorizedException("Guest session access denied.");return x;}
 static bool FixedTimeEquals(string a,string b)=>a.Length==b.Length&&System.Security.Cryptography.CryptographicOperations.FixedTimeEquals(System.Text.Encoding.UTF8.GetBytes(a),System.Text.Encoding.UTF8.GetBytes(b));
 static GuestJourneyStateDto Map(GuestBoothSession x)=>new(x.Id,x.EventId,x.State,x.SelectedMode,x.RecoveryToken,x.LastActivityAt);
}
