using AutoMapper;using EventLensAI.Application.Exceptions;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Application.Interfaces.Persistence;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Booth;
public sealed class ProfessionalCameraService(IProfessionalCameraRepository repository,IOrganizationRepository organizations,ICurrentUserService current,IUnitOfWork unit,IMapper mapper,ICameraAdapterFactory factory):BoothTenantService(organizations,current),IProfessionalCameraService
{
 public IReadOnlyList<CameraProviderDto>Providers()=>[new(CameraProviderType.Browser,"Browser camera",true,"Built in"),new(CameraProviderType.Canon,"Canon DSLR",false,"Canon bridge required"),new(CameraProviderType.Nikon,"Nikon DSLR",false,"Nikon bridge required"),new(CameraProviderType.Sony,"Sony mirrorless",false,"Sony bridge required"),new(CameraProviderType.GenericDSLR,"Generic DSLR",false,"Signed DSLR bridge required"),new(CameraProviderType.GenericMirrorless,"Generic mirrorless",false,"Signed mirrorless bridge required")];
 public async Task<IReadOnlyList<ProfessionalCameraDto>>ListAsync(Guid org,CancellationToken ct){await Authorize(org,false,ct);return(await repository.ListAsync(org,ct)).Select(x=>mapper.Map<ProfessionalCameraDto>(x)).ToArray();}
 public async Task<ProfessionalCameraDto>RegisterAsync(RegisterProfessionalCameraRequest r,CancellationToken ct){await Authorize(r.OrganizationId,true,ct);var x=new ProfessionalCamera(r.OrganizationId,r.Name,r.ProviderType,r.Model,r.SerialNumber,r.ConnectionType,r.FirmwareVersion);await repository.AddAsync(x,ct);var adapter=factory.Create(r.ProviderType);await repository.AddAdapterAsync(new(r.OrganizationId,x.Id,r.ProviderType,$"{r.ProviderType.ToString().ToLowerInvariant()}-adapter","1.0",adapter.Available),ct);await repository.AddCapabilitiesAsync(new(r.OrganizationId,x.Id,adapter.Available?"Runtime detection":"Adapter required","Photo",null,"","","Auto",false,r.ProviderType==CameraProviderType.Browser),ct);await unit.SaveChangesAsync(ct);return mapper.Map<ProfessionalCameraDto>(x);}
 public Task<CameraConnectionDto>ConnectAsync(Guid id,CancellationToken ct)=>Change(id,true,ct);public Task<CameraConnectionDto>DisconnectAsync(Guid id,CancellationToken ct)=>Change(id,false,ct);
 public async Task<CameraConnectionDto>StatusAsync(Guid id,CancellationToken ct){var x=await Load(id,false,ct);return await factory.Create(x.ProviderType).GetStatusAsync(x,ct);}
 public async Task<CameraCapabilityProfileDto>CapabilitiesAsync(Guid id,CancellationToken ct){var x=await Load(id,false,ct);var adapter=factory.Create(x.ProviderType);return await adapter.GetCapabilitiesAsync(x,ct);}
 async Task<CameraConnectionDto>Change(Guid id,bool connect,CancellationToken ct){var x=await Load(id,true,ct);var adapter=factory.Create(x.ProviderType);try{if(connect)await adapter.ConnectAsync(x,ct);else await adapter.DisconnectAsync(x,ct);await repository.AddLogAsync(new(x.OrganizationId,x.Id,connect?"Connect":"Disconnect",x.Status.ToString(),null),ct);await repository.AddEventAsync(new(x.OrganizationId,x.Id,null,connect?ProfessionalCameraEventType.CameraConnected:ProfessionalCameraEventType.CameraDisconnected,"{}"),ct);await unit.SaveChangesAsync(ct);return await adapter.GetStatusAsync(x,ct);}catch{ x.Fail("adapter_unavailable");await repository.AddLogAsync(new(x.OrganizationId,x.Id,"Connect","Error","adapter_unavailable"),ct);await repository.AddEventAsync(new(x.OrganizationId,x.Id,null,ProfessionalCameraEventType.CameraError,"{\"code\":\"adapter_unavailable\"}"),ct);await unit.SaveChangesAsync(ct);throw;}}
 async Task<ProfessionalCamera>Load(Guid id,bool write,CancellationToken ct){var x=await repository.GetAsync(id,ct)??throw new NotFoundException("Professional camera was not found.");await Authorize(x.OrganizationId,write,ct);return x;}
}
public sealed class CameraHealthService(IProfessionalCameraRepository repository,IOrganizationRepository organizations,ICurrentUserService current,ICameraAdapterFactory factory):BoothTenantService(organizations,current),ICameraHealthService
{public async Task<CameraConnectionDto>CheckAsync(Guid id,CancellationToken ct){var x=await repository.GetAsync(id,ct)??throw new NotFoundException("Professional camera was not found.");await Authorize(x.OrganizationId,false,ct);var status=await factory.Create(x.ProviderType).GetStatusAsync(x,ct);return status with{Healthy=status.Healthy&&(!x.LastCommunicationAt.HasValue||DateTime.UtcNow-x.LastCommunicationAt<TimeSpan.FromMinutes(2))};}}
