using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Booth;
public sealed record ProfessionalCameraDto(Guid Id,Guid OrganizationId,string Name,CameraProviderType ProviderType,string Model,string ConnectionType,ProfessionalCameraStatus Status,string?FirmwareVersion,DateTime?LastConnectedAt,DateTime?LastCommunicationAt,string?LastErrorCode);
public sealed record CameraProviderDto(CameraProviderType Provider,string Name,bool Available,string Requirement);
public sealed record CameraCapabilityProfileDto(Guid CameraId,string Resolution,IReadOnlyList<string>SupportedModes,int?MaxISO,IReadOnlyList<string>ShutterSpeeds,IReadOnlyList<string>Apertures,IReadOnlyList<string>FocusModes,bool FlashSupport,bool VideoSupport);
public sealed record CameraConnectionDto(Guid CameraId,ProfessionalCameraStatus Status,bool Healthy,DateTime?LastCommunication,string?ErrorCode,string Recovery);
public sealed record RegisterProfessionalCameraRequest(Guid OrganizationId,string Name,CameraProviderType ProviderType,string Model,string SerialNumber,string ConnectionType,string?FirmwareVersion);
public sealed record ProfessionalCameraSettings(string ISO,string Aperture,string ShutterSpeed,string FocusMode,string WhiteBalance,double ExposureCompensation,string FlashMode);
public interface ICameraProvider{CameraProviderType ProviderType{get;}bool Available{get;}Task ConnectAsync(ProfessionalCamera camera,CancellationToken ct);Task DisconnectAsync(ProfessionalCamera camera,CancellationToken ct);Task<CameraConnectionDto>GetStatusAsync(ProfessionalCamera camera,CancellationToken ct);Task<string>CaptureImageAsync(ProfessionalCamera camera,CancellationToken ct);Task<string>CaptureVideoAsync(ProfessionalCamera camera,CancellationToken ct);Task<CameraCapabilityProfileDto>GetCapabilitiesAsync(ProfessionalCamera camera,CancellationToken ct);Task ApplySettingsAsync(ProfessionalCamera camera,ProfessionalCameraSettings settings,CancellationToken ct);}
public interface ICameraAdapter:ICameraProvider{}
public interface ICameraAdapterFactory{ICameraAdapter Create(CameraProviderType provider);}
public interface ICameraHealthService{Task<CameraConnectionDto>CheckAsync(Guid id,CancellationToken ct);}
public interface IProfessionalCameraService{IReadOnlyList<CameraProviderDto>Providers();Task<IReadOnlyList<ProfessionalCameraDto>>ListAsync(Guid organizationId,CancellationToken ct);Task<ProfessionalCameraDto>RegisterAsync(RegisterProfessionalCameraRequest request,CancellationToken ct);Task<CameraConnectionDto>ConnectAsync(Guid id,CancellationToken ct);Task<CameraConnectionDto>DisconnectAsync(Guid id,CancellationToken ct);Task<CameraConnectionDto>StatusAsync(Guid id,CancellationToken ct);Task<CameraCapabilityProfileDto>CapabilitiesAsync(Guid id,CancellationToken ct);}
public interface IProfessionalCameraRepository{Task<ProfessionalCamera?>GetAsync(Guid id,CancellationToken ct);Task<IReadOnlyList<ProfessionalCamera>>ListAsync(Guid organizationId,CancellationToken ct);Task AddAsync(ProfessionalCamera value,CancellationToken ct);Task AddAdapterAsync(CameraAdapter value,CancellationToken ct);Task AddLogAsync(CameraConnectionLog value,CancellationToken ct);Task<CameraCapabilityProfile?>GetCapabilitiesAsync(Guid id,CancellationToken ct);Task AddCapabilitiesAsync(CameraCapabilityProfile value,CancellationToken ct);Task AddEventAsync(ProfessionalCameraEvent value,CancellationToken ct);}
