using EventLensAI.Application.Exceptions;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;
namespace EventLensAI.Application.Features.Booth;
public sealed class BrowserCameraAdapter:ICameraAdapter
{
 public CameraProviderType ProviderType=>CameraProviderType.Browser;public bool Available=>true;public Task ConnectAsync(ProfessionalCamera c,CancellationToken ct){c.Connect();return Task.CompletedTask;}public Task DisconnectAsync(ProfessionalCamera c,CancellationToken ct){c.Disconnect();return Task.CompletedTask;}public Task<CameraConnectionDto>GetStatusAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromResult(new CameraConnectionDto(c.Id,c.Status,c.Status is ProfessionalCameraStatus.Connected or ProfessionalCameraStatus.Available,c.LastCommunicationAt,c.LastErrorCode,"Check browser permission and reconnect the active camera."));
 public Task<string>CaptureImageAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromResult("browser-capture-delegated");public Task<string>CaptureVideoAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromResult("browser-recording-delegated");public Task<CameraCapabilityProfileDto>GetCapabilitiesAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromResult(new CameraCapabilityProfileDto(c.Id,"Runtime browser capability",["Photo","GIF","Boomerang","Video","Burst","TimeLapse","LivePhoto"],null,[],[],["continuous","manual"],false,true));public Task ApplySettingsAsync(ProfessionalCamera c,ProfessionalCameraSettings s,CancellationToken ct)=>Task.CompletedTask;
}
public abstract class DSLRAdapterBase(CameraProviderType provider):ICameraAdapter{public CameraProviderType ProviderType=>provider;public bool Available=>false;protected Exception Missing()=>new ConflictException($"{provider} adapter bridge is not installed.");public Task ConnectAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromException(Missing());public Task DisconnectAsync(ProfessionalCamera c,CancellationToken ct)=>Task.CompletedTask;public Task<CameraConnectionDto>GetStatusAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromResult(new CameraConnectionDto(c.Id,ProfessionalCameraStatus.Disconnected,false,c.LastCommunicationAt,"adapter_unavailable","Install the signed vendor bridge on the operator workstation."));public Task<string>CaptureImageAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromException<string>(Missing());public Task<string>CaptureVideoAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromException<string>(Missing());public Task<CameraCapabilityProfileDto>GetCapabilitiesAsync(ProfessionalCamera c,CancellationToken ct)=>Task.FromResult(new CameraCapabilityProfileDto(c.Id,"Adapter required",[],null,[],[],[],false,false));public Task ApplySettingsAsync(ProfessionalCamera c,ProfessionalCameraSettings s,CancellationToken ct)=>Task.FromException(Missing());}
public abstract class MirrorlessAdapterBase(CameraProviderType provider):DSLRAdapterBase(provider);
sealed class UnavailableDslrAdapter(CameraProviderType provider):DSLRAdapterBase(provider);sealed class UnavailableMirrorlessAdapter(CameraProviderType provider):MirrorlessAdapterBase(provider);
public sealed class CameraAdapterFactory(BrowserCameraAdapter browser):ICameraAdapterFactory{public ICameraAdapter Create(CameraProviderType p)=>p switch{CameraProviderType.Browser=>browser,CameraProviderType.Sony or CameraProviderType.GenericMirrorless=>new UnavailableMirrorlessAdapter(p),_=>new UnavailableDslrAdapter(p)};}
