import type{CameraSettings,RuntimeCapability}from"./types";
type AdvancedCapabilities=MediaTrackCapabilities&Record<string,number|boolean|string[]|undefined>;
export interface ICameraControlAdapter{detect(track:MediaStreamTrack):RuntimeCapability[];apply(track:MediaStreamTrack,settings:CameraSettings):Promise<void>;reset(track:MediaStreamTrack):Promise<void>}
const numeric=(name:string,value:unknown,current:MediaTrackSettings):RuntimeCapability=>{const x=value as {min?:number;max?:number;step?:number}|undefined;return{name,supported:!!x,currentValue:Number((current as Record<string,unknown>)[name]??0),minimum:x?.min,maximum:x?.max,step:x?.step,values:[]}};
export class BrowserCameraControlAdapter implements ICameraControlAdapter{
 detect(track:MediaStreamTrack){const c=track.getCapabilities()as AdvancedCapabilities,s=track.getSettings();return["zoom","focusDistance","exposureCompensation","brightness","contrast","frameRate","width","height"].map(n=>numeric(n,c[n],s)).concat([{name:"focusMode",supported:!!c.focusMode,values:(c.focusMode as string[])??[]},{name:"exposureMode",supported:!!c.exposureMode,values:(c.exposureMode as string[])??[]},{name:"whiteBalanceMode",supported:!!c.whiteBalanceMode,values:(c.whiteBalanceMode as string[])??[]},{name:"torch",supported:c.torch===true,values:[]}])}
 async apply(track:MediaStreamTrack,x:CameraSettings){const advanced:Record<string,unknown>={};if(x.zoom!=null)advanced.zoom=x.zoom;if(x.focusMode)advanced.focusMode=x.focusMode;if(x.focus!=null)advanced.focusDistance=x.focus;if(x.exposure!=null)advanced.exposureCompensation=x.exposure;if(x.brightness!=null)advanced.brightness=x.brightness;if(x.torchMode!=="Auto")advanced.torch=x.torchMode==="On";await track.applyConstraints({width:{ideal:Number(x.resolution.split("x")[0])},height:{ideal:Number(x.resolution.split("x")[1])},frameRate:x.frameRate?{ideal:x.frameRate}:undefined,advanced:[advanced]})}
 async reset(track:MediaStreamTrack){await track.applyConstraints({advanced:[{torch:false}as MediaTrackConstraintSet]})}
}
export class FutureDslrCameraControlAdapter implements ICameraControlAdapter{detect(){return[]}async apply(){throw new Error("Professional camera adapter is not installed.")}async reset(){}}
