using System.Security.Cryptography;
using System.Text;
using EventLensAI.Application.Common;
using EventLensAI.Application.Exceptions;
using EventLensAI.Application.Features.Analytics;
using EventLensAI.Application.Interfaces.Identity;
using EventLensAI.Domain.Entities;
using EventLensAI.Domain.Enums;
using EventLensAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
namespace EventLensAI.Infrastructure.Services;
public sealed class AnalyticsService(EventLensDbContext db,ICurrentUserService current,IMemoryCache cache,IAnalyticsNotifier notifier):IAnalyticsService
{
 async Task Authorize(Guid org,CancellationToken ct){var uid=current.UserId??throw new UnauthorizedException("Authentication is required.");if(current.Roles.Contains("SuperAdmin"))return;if(!await db.OrganizationMembers.AnyAsync(x=>x.OrganizationId==org&&x.UserId==uid&&!x.IsDeleted,ct))throw new UnauthorizedException("You cannot access analytics for this organization.");}
 static (DateTime from,DateTime to) Range(DateTime? from,DateTime? to)=>(from?.ToUniversalTime()??DateTime.UtcNow.AddDays(-30),to?.ToUniversalTime()??DateTime.UtcNow);
 IQueryable<AnalyticsRecord> Query(AnalyticsFilter f){var(from,to)=Range(f.From,f.To);var q=db.AnalyticsRecords.AsNoTracking().Where(x=>x.OrganizationId==f.OrganizationId&&x.OccurredAt>=from&&x.OccurredAt<=to);if(f.EventId.HasValue)q=q.Where(x=>x.EventId==f.EventId);if(f.TemplateId.HasValue)q=q.Where(x=>x.TemplateId==f.TemplateId);if(f.PhotographerId.HasValue)q=q.Where(x=>x.PhotographerId==f.PhotographerId);if(Enum.TryParse<EventType>(f.EventType,true,out var eventType))q=q.Where(x=>x.EventId!=null&&db.Events.Any(e=>e.Id==x.EventId&&e.EventType==eventType));return q;}
 public async Task TrackAsync(TrackAnalyticsRequest r,CancellationToken ct){await Authorize(r.OrganizationId,ct);if(r.EventId.HasValue&&!await db.Events.AnyAsync(x=>x.Id==r.EventId&&x.OrganizationId==r.OrganizationId,ct))throw new NotFoundException("Event not found.");var x=new AnalyticsRecord(r.OrganizationId,r.Metric,DateTime.UtcNow,r.EventId,r.GuestId,r.PhotoId,r.TemplateId,r.PhotographerId,Math.Max(1,r.Value));var hash=string.IsNullOrWhiteSpace(r.SessionKey)?null:Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(r.SessionKey)));x.AddContext(hash,r.DeviceType,r.Browser,r.OperatingSystem,r.Country,r.City,r.DimensionsJson);db.Add(x);await db.SaveChangesAsync(ct);cache.Remove($"analytics:{r.OrganizationId}");await notifier.MetricRecordedAsync(r.OrganizationId,r.EventId,r.Metric,r.Value,ct);}
 public async Task<AnalyticsDashboardDto> DashboardAsync(AnalyticsFilter f,CancellationToken ct){await Authorize(f.OrganizationId,ct);var key=$"analytics:{f.OrganizationId}:{f.EventId}:{f.From:O}:{f.To:O}:{f.TemplateId}:{f.PhotographerId}";if(cache.TryGetValue(key,out AnalyticsDashboardDto? found)&&found is not null)return found;var q=Query(f);var metrics=await q.GroupBy(x=>x.Metric).Select(g=>new{Metric=g.Key,Total=g.Sum(x=>x.Value),Unique=g.Where(x=>x.SessionKeyHash!=null).Select(x=>x.SessionKeyHash).Distinct().Count()}).ToListAsync(ct);int M(AnalyticsMetric m)=>metrics.FirstOrDefault(x=>x.Metric==m)?.Total??0;int U(AnalyticsMetric m)=>metrics.FirstOrDefault(x=>x.Metric==m)?.Unique??0;var events=db.Events.AsNoTracking().Where(x=>x.OrganizationId==f.OrganizationId);if(f.EventId.HasValue)events=events.Where(x=>x.Id==f.EventId);var eventIds=events.Select(x=>x.Id);var storage=await db.Organizations.Where(x=>x.Id==f.OrganizationId).Select(x=>x.StorageUsed).SingleAsync(ct);var result=new AnalyticsDashboardDto(await events.CountAsync(ct),await events.CountAsync(x=>x.Status==EventStatus.Published,ct),await db.Guests.CountAsync(x=>x.OrganizationId==f.OrganizationId,ct),await db.BoothSessions.CountAsync(x=>eventIds.Contains(x.EventId),ct),await db.Photos.CountAsync(x=>eventIds.Contains(x.EventId),ct),M(AnalyticsMetric.AIPhotoGenerated),M(AnalyticsMetric.GalleryView),U(AnalyticsMetric.GalleryVisitor),M(AnalyticsMetric.Download),M(AnalyticsMetric.Share),M(AnalyticsMetric.QrScan),M(AnalyticsMetric.LeadCollected),null,storage);cache.Set(key,result,TimeSpan.FromMinutes(2));return result;}
 public async Task<EventAnalyticsDto> EventAsync(Guid id,DateTime? from,DateTime? to,CancellationToken ct){var e=await db.Events.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Event not found.");await Authorize(e.OrganizationId,ct);var f=new AnalyticsFilter(e.OrganizationId,id,from,to);var q=Query(f);var hourly=await q.GroupBy(x=>x.OccurredAt.Hour).Select(g=>new ChartPoint(g.Key.ToString("00")+":00",g.Sum(x=>x.Value))).ToListAsync(ct);var timeline=await q.GroupBy(x=>x.OccurredAt.Date).Select(g=>new ChartPoint(g.Key.ToString("yyyy-MM-dd"),g.Sum(x=>x.Value))).ToListAsync(ct);var templates=await q.Where(x=>x.TemplateId!=null).GroupBy(x=>x.TemplateId).OrderByDescending(g=>g.Sum(x=>x.Value)).Take(10).Select(g=>new ChartPoint(g.Key!.Value.ToString(),g.Sum(x=>x.Value))).ToListAsync(ct);var sessions=await db.BoothSessions.AsNoTracking().Where(x=>x.EventId==id&&x.CompletedAt!=null).ToListAsync(ct);var avgMinutes=sessions.Count==0?0:sessions.Average(x=>(x.CompletedAt!.Value-x.StartedAt).TotalMinutes);var guests=await q.Where(x=>x.GuestId!=null).Select(x=>x.GuestId).Distinct().CountAsync(ct);var photos=await db.Photos.CountAsync(x=>x.EventId==id,ct);return new(id,e.Name,await DashboardAsync(f,ct),avgMinutes,guests==0?0:(double)photos/guests,hourly,timeline,templates);}
 public async Task<IReadOnlyList<AnalyticsChartDto>> ChartsAsync(AnalyticsFilter f,CancellationToken ct){await Authorize(f.OrganizationId,ct);var q=Query(f);var timeline=await q.GroupBy(x=>x.OccurredAt.Date).OrderBy(g=>g.Key).Select(g=>new ChartPoint(g.Key.ToString("MMM dd"),g.Sum(x=>x.Value))).ToListAsync(ct);var actions=await q.GroupBy(x=>x.Metric).OrderByDescending(g=>g.Sum(x=>x.Value)).Select(g=>new ChartPoint(g.Key.ToString(),g.Sum(x=>x.Value))).ToListAsync(ct);var devices=await q.GroupBy(x=>x.DeviceType).Select(g=>new ChartPoint(g.Key.ToString(),g.Sum(x=>x.Value))).ToListAsync(ct);return[new("area","Activity over time",timeline),new("bar","Engagement",actions),new("pie","Devices",devices)];}
 public async Task<PagedResult<ActivityFeedItem>> ActivityAsync(AnalyticsFilter f,int page,int size,CancellationToken ct){await Authorize(f.OrganizationId,ct);page=Math.Max(1,page);size=Math.Clamp(size,1,100);var q=Query(f);var count=await q.CountAsync(ct);var rows=await q.OrderByDescending(x=>x.OccurredAt).ThenByDescending(x=>x.Id).Skip((page-1)*size).Take(size).Select(x=>new ActivityFeedItem(x.Id,x.Metric,x.EventId,x.GuestId,x.PhotoId,x.OccurredAt,x.Value)).ToListAsync(ct);return new(rows,page,size,count);}
 public async Task<ExportedReport> ExportAsync(ReportRequest r,CancellationToken ct){var f=new AnalyticsFilter(r.OrganizationId,r.EventId,r.From,r.To);var data=await DashboardAsync(f,ct);var rows=new[]{("Total Events",data.TotalEvents),("Active Events",data.ActiveEvents),("Guests",data.TotalGuests),("Sessions",data.TotalBoothSessions),("Photos",data.PhotosCaptured),("AI Photos",data.AIPhotosGenerated),("Gallery Views",data.GalleryViews),("Downloads",data.Downloads),("Shares",data.Shares),("QR Scans",data.QrScans),("Leads",data.LeadsCollected)};var stamp=$"{r.From:yyyyMMdd}-{r.To:yyyyMMdd}";return r.Format switch{AnalyticsExportFormat.Csv=>new($"eventlens-{stamp}.csv","text/csv",Encoding.UTF8.GetBytes("Metric,Value\r\n"+string.Join("\r\n",rows.Select(x=>$"\"{x.Item1}\",{x.Item2}")))),AnalyticsExportFormat.Excel=>new($"eventlens-{stamp}.xls","application/vnd.ms-excel",Encoding.UTF8.GetBytes(Excel(rows))),_=>new($"eventlens-{stamp}.pdf","application/pdf",Pdf(rows,r.From,r.To))};}
 static string Excel(IEnumerable<(string,int)> rows)=>"<?xml version=\"1.0\"?><Workbook xmlns=\"urn:schemas-microsoft-com:office:spreadsheet\" xmlns:ss=\"urn:schemas-microsoft-com:office:spreadsheet\"><Worksheet ss:Name=\"Analytics\"><Table><Row><Cell><Data ss:Type=\"String\">Metric</Data></Cell><Cell><Data ss:Type=\"String\">Value</Data></Cell></Row>"+string.Join("",rows.Select(x=>$"<Row><Cell><Data ss:Type=\"String\">{System.Security.SecurityElement.Escape(x.Item1)}</Data></Cell><Cell><Data ss:Type=\"Number\">{x.Item2}</Data></Cell></Row>"))+"</Table></Worksheet></Workbook>";
 static byte[] Pdf(IEnumerable<(string,int)> rows,DateTime from,DateTime to){var lines=new[]{"EventLens AI Analytics Report",$"{from:yyyy-MM-dd} to {to:yyyy-MM-dd}"}.Concat(rows.Select(x=>$"{x.Item1}: {x.Item2}")).ToArray();var stream="BT /F1 12 Tf 50 780 Td "+string.Join(" Tj 0 -22 Td ",lines.Select(x=>$"({x.Replace("\\","\\\\").Replace("(","\\(").Replace(")","\\)")})"))+" Tj ET";var objects=new[]{"1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj","2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj","3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj","4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",$"5 0 obj << /Length {Encoding.ASCII.GetByteCount(stream)} >> stream\n{stream}\nendstream endobj"};var sb=new StringBuilder("%PDF-1.4\n");var offsets=new List<int>{0};foreach(var o in objects){offsets.Add(Encoding.ASCII.GetByteCount(sb.ToString()));sb.Append(o).Append('\n');}var xref=Encoding.ASCII.GetByteCount(sb.ToString());sb.Append($"xref\n0 {objects.Length+1}\n0000000000 65535 f \n");foreach(var o in offsets.Skip(1))sb.Append(o.ToString("0000000000")).Append(" 00000 n \n");sb.Append($"trailer << /Size {objects.Length+1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF");return Encoding.ASCII.GetBytes(sb.ToString());}
}
