using System.Security.Cryptography;
using System.Text;
using EventLensAI.Application.Common;
using EventLensAI.Application.Exceptions;
using EventLensAI.Application.Features.Billing;
using EventLensAI.Application.Interfaces.Identity;
using EventLensAI.Domain.Entities;
using EventLensAI.Domain.Enums;
using EventLensAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
namespace EventLensAI.Infrastructure.Services;
public sealed class BillingService(EventLensDbContext db,ICurrentUserService current,IPaymentProviderResolver providers):IBillingService
{
 Guid UserId=>current.UserId??throw new UnauthorizedException("Authentication is required.");
 bool SuperAdmin=>current.Roles.Contains("SuperAdmin");
 async Task<Organization>Authorize(Guid orgId,CancellationToken ct,bool admin=false){var org=await db.Organizations.SingleOrDefaultAsync(x=>x.Id==orgId,ct)??throw new NotFoundException("Organization not found.");if(SuperAdmin)return org;if(admin||!await db.OrganizationMembers.AnyAsync(x=>x.OrganizationId==orgId&&x.UserId==UserId&&(x.Role.Name=="Owner"||x.Role.Name=="Manager"),ct))throw new UnauthorizedException("Billing owner access is required.");return org;}
 static PlanDto Map(PlanDefinition x)=>new(x.Plan,x.Name,x.MonthlyPrice,x.YearlyPrice,x.Currency,x.MaximumOrganizations,x.MaximumEvents,x.MaximumTeamMembers,x.MonthlyAICredits,x.StorageLimit,x.GalleryLimit,x.TemplateAccess,x.CustomBranding,x.WhiteLabel,x.ApiAccess,x.CustomDomains,x.PrioritySupport);
 static SubscriptionDto Map(Subscription x)=>new(x.Id,x.OrganizationId,x.Plan,x.Status,x.BillingInterval,x.StartDate,x.EndDate,x.TrialEndsAt,x.GracePeriodEndsAt,x.CancelAtPeriodEnd,x.Provider);
 static InvoiceDto Map(Invoice x)=>new(x.Id,x.InvoiceNumber,x.Customer,x.Plan,x.Amount,x.Tax,x.Discount,x.Currency,x.Status,x.IssueDate,x.DueDate);
 static PaymentDto Map(PaymentTransaction x)=>new(x.Id,x.Provider,x.ProviderReference,x.Amount,x.Currency,x.Status,x.RefundedAmount,x.CreatedAt);
 public async Task<IReadOnlyList<PlanDto>>PlansAsync(CancellationToken ct)=>await db.PlanDefinitions.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.MonthlyPrice).Select(x=>Map(x)).ToListAsync(ct);
 async Task<Subscription>Current(Guid org,CancellationToken ct){var s=await db.Subscriptions.OrderByDescending(x=>x.CreatedAt).FirstOrDefaultAsync(x=>x.OrganizationId==org&&(x.Status==SubscriptionStatus.Active||x.Status==SubscriptionStatus.Trialing||x.Status==SubscriptionStatus.GracePeriod||x.Status==SubscriptionStatus.Paused),ct);if(s is not null)return s;s=new Subscription(org,SubscriptionPlan.Free,DateTime.UtcNow,DateTime.UtcNow.AddYears(10));db.Add(s);await db.SaveChangesAsync(ct);return s;}
 public async Task<SubscriptionDto>SubscriptionAsync(Guid org,CancellationToken ct){await Authorize(org,ct);return Map(await Current(org,ct));}
 public async Task<CheckoutDto>ChangeSubscriptionAsync(Guid orgId,ChangeSubscriptionRequest r,CancellationToken ct){var org=await Authorize(orgId,ct);var plan=await db.PlanDefinitions.AsNoTracking().SingleAsync(x=>x.Plan==r.Plan&&x.IsActive,ct);if(r.Plan==SubscriptionPlan.Free){var currentSub=await Current(orgId,ct);currentSub.ChangePlan(r.Plan);org.ApplyPlan(r.Plan,plan.StorageLimit);await Audit(orgId,AuditAction.SubscriptionChange,ct);await db.SaveChangesAsync(ct);return new("Internal","free-plan",null);}if(string.IsNullOrWhiteSpace(r.Provider))throw new ConflictException("A configured payment provider is required.");var provider=providers.Resolve(r.Provider);var amount=r.Interval==BillingInterval.Yearly?plan.YearlyPrice:plan.MonthlyPrice;if(!string.IsNullOrWhiteSpace(r.CouponCode)){var coupon=await db.BillingCoupons.SingleOrDefaultAsync(x=>x.Code==r.CouponCode.ToUpper(),ct)??throw new NotFoundException("Coupon not found.");if(!coupon.CanUse(orgId))throw new ConflictException("Coupon is invalid or expired.");amount-=coupon.Discount(amount);}var checkout=await provider.CreateCheckoutAsync(new(orgId,r.Plan,r.Interval,Math.Max(0,amount),plan.Currency,org.Email??current.Email??"",r.CouponCode),ct);db.Add(new PaymentTransaction(orgId,null,provider.Name,checkout.Reference,Math.Max(0,amount),plan.Currency));await Audit(orgId,AuditAction.SubscriptionChange,ct);await db.SaveChangesAsync(ct);return new(provider.Name,checkout.Reference,checkout.CheckoutUrl);}
 public async Task<SubscriptionDto>CancelAsync(Guid org,bool atPeriodEnd,CancellationToken ct){await Authorize(org,ct);var s=await Current(org,ct);if(s.Provider is not null&&s.ProviderSubscriptionId is not null)await providers.Resolve(s.Provider).CancelSubscriptionAsync(s.ProviderSubscriptionId,atPeriodEnd,ct);s.Cancel(atPeriodEnd);await Audit(org,AuditAction.SubscriptionChange,ct);await db.SaveChangesAsync(ct);return Map(s);}
 public async Task<SubscriptionDto>PauseAsync(Guid org,CancellationToken ct){await Authorize(org,ct);var s=await Current(org,ct);if(s.Provider is not null&&s.ProviderSubscriptionId is not null)await providers.Resolve(s.Provider).PauseSubscriptionAsync(s.ProviderSubscriptionId,ct);s.Pause();await Audit(org,AuditAction.SubscriptionChange,ct);await db.SaveChangesAsync(ct);return Map(s);}
 public async Task<SubscriptionDto>ResumeAsync(Guid org,CancellationToken ct){await Authorize(org,ct);var s=await Current(org,ct);if(s.Provider is not null&&s.ProviderSubscriptionId is not null)await providers.Resolve(s.Provider).ResumeSubscriptionAsync(s.ProviderSubscriptionId,ct);s.Resume();await Audit(org,AuditAction.SubscriptionChange,ct);await db.SaveChangesAsync(ct);return Map(s);}
 public async Task<UsageDto>UsageAsync(Guid org,CancellationToken ct){await Authorize(org,ct);var start=new DateOnly(DateTime.UtcNow.Year,DateTime.UtcNow.Month,1);var usage=await db.UsageCounters.AsNoTracking().Where(x=>x.OrganizationId==org&&x.PeriodStart==start).ToDictionaryAsync(x=>x.Metric,x=>x.Quantity,ct);var p=await db.PlanDefinitions.AsNoTracking().SingleAsync(x=>x.Plan==db.Organizations.Where(o=>o.Id==org).Select(o=>o.Plan).Single(),ct);var limits=new Dictionary<UsageMetric,long>{{UsageMetric.EventsCreated,p.MaximumEvents},{UsageMetric.AIGenerations,p.MonthlyAICredits},{UsageMetric.StorageConsumed,p.StorageLimit},{UsageMetric.Users,p.MaximumTeamMembers}};return new(org,start,usage,limits);}
 public async Task<PagedResult<InvoiceDto>>InvoicesAsync(Guid org,int page,int size,CancellationToken ct){await Authorize(org,ct);page=Math.Max(1,page);size=Math.Clamp(size,1,100);var q=db.Invoices.AsNoTracking().Where(x=>x.OrganizationId==org).OrderByDescending(x=>x.IssueDate);var count=await q.CountAsync(ct);return new((await q.Skip((page-1)*size).Take(size).ToListAsync(ct)).Select(Map).ToList(),page,size,count);}
 public async Task<InvoiceDto>InvoiceAsync(Guid id,CancellationToken ct){var x=await db.Invoices.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Invoice not found.");await Authorize(x.OrganizationId,ct);return Map(x);}
 public async Task<PagedResult<PaymentDto>>PaymentsAsync(Guid org,int page,int size,CancellationToken ct){await Authorize(org,ct);page=Math.Max(1,page);size=Math.Clamp(size,1,100);var q=db.PaymentTransactions.AsNoTracking().Where(x=>x.OrganizationId==org).OrderByDescending(x=>x.CreatedAt);var count=await q.CountAsync(ct);return new((await q.Skip((page-1)*size).Take(size).ToListAsync(ct)).Select(Map).ToList(),page,size,count);}
 public async Task HandleWebhookAsync(string providerName,WebhookRequest request,CancellationToken ct){var provider=providers.Resolve(providerName);if(await db.BillingWebhooks.AnyAsync(x=>x.Provider==providerName&&x.ExternalId==request.ExternalId,ct))return;var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(request.Payload)));var hook=new BillingWebhook(providerName,request.ExternalId,request.Type,hash);db.Add(hook);try{var parsed=await provider.ParseWebhookAsync(request.Payload,request.Signature,ct);var payment=await db.PaymentTransactions.SingleOrDefaultAsync(x=>x.Provider==providerName&&x.ProviderReference==parsed.ProviderReference,ct);if(parsed.Type==BillingWebhookType.PaymentSucceeded){payment?.Succeed();var org=await db.Organizations.SingleAsync(x=>x.Id==parsed.OrganizationId,ct);var plan=await db.PlanDefinitions.SingleAsync(x=>x.Plan==parsed.Plan,ct);var sub=await Current(org.Id,ct);sub.ChangePlan(parsed.Plan);sub.AttachProvider(providerName,parsed.ProviderReference);sub.Renew(DateTime.UtcNow.Add(parsed.Interval==BillingInterval.Yearly?TimeSpan.FromDays(365):TimeSpan.FromDays(30)));org.ApplyPlan(parsed.Plan,plan.StorageLimit);var invoice=new Invoice(org.Id,sub.Id,$"EL-{DateTime.UtcNow:yyyyMMdd}-{Guid.NewGuid():N}"[..24],org.Name,parsed.Plan,parsed.Amount,0,0,parsed.Currency,DateTime.UtcNow,DateTime.UtcNow);invoice.MarkPaid();db.Add(invoice);}else if(parsed.Type==BillingWebhookType.PaymentFailed){payment?.Fail();(await Current(parsed.OrganizationId,ct)).StartGracePeriod(DateTime.UtcNow.AddDays(7));}else if(parsed.Type==BillingWebhookType.SubscriptionCancelled)(await Current(parsed.OrganizationId,ct)).Cancel(false);hook.Complete();await db.SaveChangesAsync(ct);}catch(Exception ex){hook.Fail(ex.Message);await db.SaveChangesAsync(ct);throw;}}
 public async Task<IReadOnlyList<string>>PaymentMethodsAsync(Guid org,CancellationToken ct){await Authorize(org,ct);return providers.AvailableProviders;}
 public async Task<PagedResult<SubscriptionDto>>AdminSubscriptionsAsync(int page,int size,CancellationToken ct){if(!SuperAdmin)throw new UnauthorizedException("SuperAdmin access required.");page=Math.Max(1,page);size=Math.Clamp(size,1,100);var q=db.Subscriptions.AsNoTracking().OrderByDescending(x=>x.CreatedAt);var count=await q.CountAsync(ct);return new((await q.Skip((page-1)*size).Take(size).ToListAsync(ct)).Select(Map).ToList(),page,size,count);}
 public async Task RefundAsync(Guid paymentId,RefundRequest r,CancellationToken ct){if(!SuperAdmin)throw new UnauthorizedException("SuperAdmin access required.");var p=await db.PaymentTransactions.SingleOrDefaultAsync(x=>x.Id==paymentId,ct)??throw new NotFoundException("Payment not found.");var provider=providers.Resolve(p.Provider);await provider.RefundAsync(p.ProviderReference,r.Amount,r.Reason,ct);p.Refund(r.Amount);if(p.InvoiceId.HasValue)(await db.Invoices.FindAsync([p.InvoiceId.Value],ct))?.Refund();await Audit(p.OrganizationId,AuditAction.Refund,ct);await db.SaveChangesAsync(ct);}
 public async Task GrantCreditsAsync(Guid org,GrantCreditsRequest r,CancellationToken ct){if(!SuperAdmin)throw new UnauthorizedException("SuperAdmin access required.");var start=new DateOnly(DateTime.UtcNow.Year,DateTime.UtcNow.Month,1);var row=await db.UsageCounters.SingleOrDefaultAsync(x=>x.OrganizationId==org&&x.PeriodStart==start&&x.Metric==UsageMetric.AIGenerations,ct);if(row is null)db.Add(new UsageCounter(org,UsageMetric.AIGenerations,start,-Math.Abs(r.Credits)));else row.Add(-Math.Abs(r.Credits));await Audit(org,AuditAction.GrantCredits,ct);await db.SaveChangesAsync(ct);}
 public async Task SuspendAsync(Guid org,bool suspended,CancellationToken ct){if(!SuperAdmin)throw new UnauthorizedException("SuperAdmin access required.");(await Authorize(org,ct,true)).SetActive(!suspended);await Audit(org,AuditAction.Suspend,ct);await db.SaveChangesAsync(ct);}
 public async Task CreateCouponAsync(CouponRequest r,CancellationToken ct){if(!SuperAdmin)throw new UnauthorizedException("SuperAdmin access required.");db.Add(new BillingCoupon(r.Code,r.DiscountType,r.Value,r.Expiry,r.UsageLimit,r.OrganizationId,r.IsReferral));await db.SaveChangesAsync(ct);}
 async Task Audit(Guid resource,AuditAction action,CancellationToken ct)=>await db.AuditLogs.AddAsync(new AuditLog(UserId,"Billing",resource,action,current.IPAddress),ct);
}
