using System.Text.Json;
using EventLensAI.Application.Common;
using EventLensAI.Application.Exceptions;
using EventLensAI.Application.Features.CRM;
using EventLensAI.Application.Interfaces.Identity;
using EventLensAI.Domain.Entities;
using EventLensAI.Domain.Enums;
using EventLensAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using FluentValidation;

namespace EventLensAI.Infrastructure.Services;

public sealed class CrmService(EventLensDbContext db,ICurrentUserService current):ICrmService
{
 async Task Authorize(Guid org,CancellationToken ct){var uid=current.UserId??throw new UnauthorizedException("Authentication is required.");if(!await db.OrganizationMembers.AnyAsync(x=>x.OrganizationId==org&&x.UserId==uid&&!x.IsDeleted,ct))throw new UnauthorizedException("You cannot access this organization.");}
 static GuestDto Map(Guest x)=>new(x.Id,x.OrganizationId,x.FirstName,x.LastName,x.Email,x.Phone,x.Company,x.JobTitle,x.Country,x.City,x.BirthDate,x.Gender,x.CustomFieldsJson,x.MarketingConsent,x.PrivacyPolicyAccepted,x.LastVisit,x.TotalEvents,x.GuestTags.Select(t=>t.Tag.Name).ToList());
 public async Task<PagedResult<GuestDto>> SearchGuestsAsync(GuestSearch r,CancellationToken ct){await Authorize(r.OrganizationId,ct);var q=db.Guests.AsNoTracking().Include(x=>x.GuestTags).ThenInclude(x=>x.Tag).Where(x=>x.OrganizationId==r.OrganizationId);if(!string.IsNullOrWhiteSpace(r.Search)){var s=r.Search.Trim();q=q.Where(x=>x.FirstName.Contains(s)||x.LastName.Contains(s)||(x.Email!=null&&x.Email.Contains(s))||(x.Phone!=null&&x.Phone.Contains(s)));}if(r.MarketingConsent.HasValue)q=q.Where(x=>x.MarketingConsent==r.MarketingConsent);if(!string.IsNullOrWhiteSpace(r.Tag))q=q.Where(x=>x.GuestTags.Any(t=>t.Tag.Name==r.Tag));var page=Math.Max(1,r.Page);var size=Math.Clamp(r.PageSize,1,100);var count=await q.CountAsync(ct);var items=await q.OrderByDescending(x=>x.CreatedAt).Skip((page-1)*size).Take(size).ToListAsync(ct);return new(items.Select(Map).ToList(),page,size,count);}
 public async Task<GuestDto> GetGuestAsync(Guid id,CancellationToken ct){var x=await db.Guests.Include(g=>g.GuestTags).ThenInclude(t=>t.Tag).SingleOrDefaultAsync(g=>g.Id==id,ct)??throw new NotFoundException("Guest not found.");await Authorize(x.OrganizationId,ct);return Map(x);}
 public async Task<GuestDto> CreateGuestAsync(UpsertGuestRequest r,string? ip,CancellationToken ct){await Authorize(r.OrganizationId,ct);Validate(r);var x=new Guest(r.OrganizationId,r.FirstName.Trim(),r.LastName.Trim(),r.Email?.Trim(),r.Phone?.Trim());x.Update(r.FirstName,r.LastName,r.Email,r.Phone,r.Company,r.JobTitle,r.Country,r.City,r.BirthDate,r.Gender,r.CustomFieldsJson);x.RecordConsent(r.MarketingConsent,r.PrivacyPolicyAccepted,r.ConsentVersion,ip);db.Add(x);db.Add(new GuestActivity(x.Id,null,CrmActivityType.Registered));await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<GuestDto> UpdateGuestAsync(Guid id,UpsertGuestRequest r,string? ip,CancellationToken ct){var x=await db.Guests.Include(g=>g.GuestTags).ThenInclude(t=>t.Tag).SingleOrDefaultAsync(g=>g.Id==id,ct)??throw new NotFoundException("Guest not found.");await Authorize(x.OrganizationId,ct);if(x.OrganizationId!=r.OrganizationId)throw new UnauthorizedAccessException();Validate(r);x.Update(r.FirstName,r.LastName,r.Email,r.Phone,r.Company,r.JobTitle,r.Country,r.City,r.BirthDate,r.Gender,r.CustomFieldsJson);x.RecordConsent(r.MarketingConsent,r.PrivacyPolicyAccepted,r.ConsentVersion,ip);await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<IReadOnlyList<ActivityDto>> TimelineAsync(Guid id,CancellationToken ct){var g=await db.Guests.FindAsync([id],ct)??throw new NotFoundException("Guest not found.");await Authorize(g.OrganizationId,ct);return await db.GuestActivities.Where(x=>x.GuestId==id).OrderByDescending(x=>x.CreatedAt).Select(x=>new ActivityDto(x.Id,x.Type,x.EventId,x.DataJson,x.CreatedAt)).ToListAsync(ct);}
 public async Task CheckInAsync(CheckInRequest r,CancellationToken ct){var g=await db.Guests.FindAsync([r.GuestId],ct)??throw new NotFoundException("Guest not found.");await Authorize(g.OrganizationId,ct);if(await db.GuestCheckIns.AnyAsync(x=>x.GuestId==r.GuestId&&x.EventId==r.EventId,ct))return;db.Add(new GuestCheckIn(r.GuestId,r.EventId,r.Method));db.Add(new GuestActivity(r.GuestId,r.EventId,CrmActivityType.CheckedIn));g.RecordVisit();await db.SaveChangesAsync(ct);}
 public async Task<IReadOnlyList<LeadFormDto>> FormsAsync(Guid org,CancellationToken ct){await Authorize(org,ct);return await db.LeadForms.Where(x=>x.OrganizationId==org).Select(x=>new LeadFormDto(x.Id,x.OrganizationId,x.EventId,x.Name,x.SchemaJson,x.Language,x.IsActive)).ToListAsync(ct);}
 public async Task<LeadFormDto> CreateFormAsync(CreateLeadFormRequest r,CancellationToken ct){await Authorize(r.OrganizationId,ct);JsonDocument.Parse(r.SchemaJson);var x=new LeadForm(r.OrganizationId,r.EventId,r.Name,r.SchemaJson,r.Language);db.Add(x);await db.SaveChangesAsync(ct);return new(x.Id,x.OrganizationId,x.EventId,x.Name,x.SchemaJson,x.Language,x.IsActive);}
 public async Task SubmitFormAsync(Guid formId,SubmitLeadResponseRequest r,CancellationToken ct){var f=await db.LeadForms.FindAsync([formId],ct)??throw new NotFoundException("Form not found.");await Authorize(f.OrganizationId,ct);JsonDocument.Parse(r.ValuesJson);db.Add(new LeadResponse(formId,r.GuestId,r.ValuesJson));await db.SaveChangesAsync(ct);}
 public async Task<CrmDashboardDto> DashboardAsync(Guid org,DateTime? from,DateTime? to,CancellationToken ct){await Authorize(org,ct);var start=from??DateTime.UtcNow.AddDays(-30);var end=to??DateTime.UtcNow;var guests=db.Guests.Where(x=>x.OrganizationId==org);var ids=guests.Select(x=>x.Id);var acts=db.GuestActivities.Where(x=>ids.Contains(x.GuestId)&&x.CreatedAt>=start&&x.CreatedAt<=end);return new(await guests.CountAsync(x=>x.CreatedAt>=start&&x.CreatedAt<=end,ct),await guests.CountAsync(x=>x.TotalEvents>1,ct),await acts.CountAsync(x=>x.Type==CrmActivityType.PhotoDownloaded,ct),await acts.CountAsync(x=>x.Type==CrmActivityType.GalleryViewed,ct),await db.GuestCheckIns.CountAsync(x=>ids.Contains(x.GuestId)&&x.CheckedInAt>=start&&x.CheckedInAt<=end,ct),await db.Campaigns.CountAsync(x=>x.OrganizationId==org,ct),await acts.CountAsync(x=>x.Type==CrmActivityType.EmailSent||x.Type==CrmActivityType.SmsSent||x.Type==CrmActivityType.WhatsAppSent,ct),[],[]);}
 public async Task<SegmentDto> CreateSegmentAsync(CreateSegmentRequest r,CancellationToken ct){await Authorize(r.OrganizationId,ct);JsonDocument.Parse(r.RulesJson);var x=new Segment(r.OrganizationId,r.Name,r.RulesJson);db.Add(x);await db.SaveChangesAsync(ct);return new(x.Id,x.Name,x.RulesJson,x.IsDynamic);}
 public async Task<CampaignDto> CreateCampaignAsync(CreateCampaignRequest r,CancellationToken ct){await Authorize(r.OrganizationId,ct);JsonDocument.Parse(r.ContentJson);var x=new Campaign(r.OrganizationId,r.Name,r.Channel,r.SegmentId,r.ContentJson);db.Add(x);await db.SaveChangesAsync(ct);return new(x.Id,x.Name,x.Channel,x.Status,x.ScheduledAt);}
 static void Validate(UpsertGuestRequest r){if(string.IsNullOrWhiteSpace(r.FirstName)||string.IsNullOrWhiteSpace(r.LastName))throw new ValidationException("First and last name are required.");JsonDocument.Parse(r.CustomFieldsJson);if(r.MarketingConsent&&!r.PrivacyPolicyAccepted)throw new ValidationException("Privacy policy acceptance is required for marketing consent.");}
}
