#pragma warning disable CS9107
using EventLensAI.Application.Exceptions;using EventLensAI.Application.Features.Entitlements;using EventLensAI.Application.Interfaces.Identity;using EventLensAI.Domain.Entities;using EventLensAI.Domain.Enums;using EventLensAI.Infrastructure.Persistence;using Microsoft.EntityFrameworkCore;
namespace EventLensAI.Infrastructure.Services;
public sealed class EntitlementService(EventLensDbContext db,ICurrentUserService current):ISubscriptionService,IEntitlementService,IUsageTrackingService
{
 Guid UserId=>current.UserId??throw new UnauthorizedException("Authentication required.");bool Admin=>current.Roles.Contains(SystemRoles.SuperAdmin);static DateTime Month=>new(DateTime.UtcNow.Year,DateTime.UtcNow.Month,1,0,0,0,DateTimeKind.Utc);
 async Task Authorize(Guid o,CancellationToken ct,bool owner=false){if(Admin)return;var m=await db.OrganizationMembers.Include(x=>x.Role).SingleOrDefaultAsync(x=>x.OrganizationId==o&&x.UserId==UserId,ct)??throw new UnauthorizedException("Organization access denied.");if(owner&&m.Role.Name is not(SystemRoles.Owner or SystemRoles.Manager))throw new UnauthorizedException("Organization Owner or Manager permission required.");}
 void RequireAdmin(){if(!Admin)throw new UnauthorizedException("Platform Admin access required.");}
 public async Task<IReadOnlyList<EntitlementPlanDto>>PlansAsync(bool archived,CancellationToken ct)=>(await db.EntitlementPlans.IgnoreQueryFilters().AsNoTracking().Include(x=>x.Features).ThenInclude(x=>x.Feature).Where(x=>archived||x.IsActive&&!x.IsDeleted).OrderBy(x=>x.DisplayOrder).ToListAsync(ct)).Select(Map).ToArray();
 public async Task<EntitlementPlanDto>PlanAsync(Guid id,CancellationToken ct)=>Map(await db.EntitlementPlans.AsNoTracking().Include(x=>x.Features).ThenInclude(x=>x.Feature).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Plan not found."));
 public async Task<EntitlementPlanDto>CreatePlanAsync(SaveEntitlementPlanRequest r,CancellationToken ct){RequireAdmin();if(await db.EntitlementPlans.AnyAsync(x=>x.Code==r.Code,ct))throw new ConflictException("Plan code already exists.");var x=new EntitlementPlan(Guid.NewGuid(),r.Code,r.Name,r.MonthlyPrice,r.YearlyPrice,r.Description,r.DisplayOrder);x.SetLimits(r.MaximumEvents,r.MaximumTeamMembers,r.MaximumStorage,r.MaximumGalleries,r.MaximumAIJobs,r.MaximumTemplates,r.MaximumUploads,r.MaximumMonthlyCaptures,r.MaximumApiRequests);db.Add(x);await SetFeatures(x,r.Features,ct);await Audit(x.Id,ct);await db.SaveChangesAsync(ct);return await PlanAsync(x.Id,ct);}
 public async Task<EntitlementPlanDto>UpdatePlanAsync(Guid id,SaveEntitlementPlanRequest r,CancellationToken ct){RequireAdmin();var x=await db.EntitlementPlans.Include(x=>x.Features).ThenInclude(x=>x.Feature).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new NotFoundException("Plan not found.");x.Update(r.Name,r.MonthlyPrice,r.YearlyPrice,r.Description,r.DisplayOrder);x.SetLimits(r.MaximumEvents,r.MaximumTeamMembers,r.MaximumStorage,r.MaximumGalleries,r.MaximumAIJobs,r.MaximumTemplates,r.MaximumUploads,r.MaximumMonthlyCaptures,r.MaximumApiRequests);await SetFeatures(x,r.Features,ct);await Audit(id,ct);await db.SaveChangesAsync(ct);return await PlanAsync(id,ct);}
 public async Task ArchivePlanAsync(Guid id,CancellationToken ct){RequireAdmin();var x=await db.EntitlementPlans.FindAsync([id],ct)??throw new NotFoundException("Plan not found.");if(await db.OrganizationSubscriptions.AnyAsync(s=>s.PlanId==id&&(s.Status==EntitlementSubscriptionStatus.Active||s.Status==EntitlementSubscriptionStatus.Trial),ct))throw new ConflictException("Plan is assigned to active organizations.");x.Archive();x.SoftDelete(UserId);await Audit(id,ct);await db.SaveChangesAsync(ct);}
 public async Task<OrganizationSubscriptionDto>CurrentAsync(Guid o,CancellationToken ct){await Authorize(o,ct);return Map(await Current(o,true,ct));}
 public Task<OrganizationSubscriptionDto>ChangePlanAsync(Guid o,ChangeEntitlementPlanRequest r,CancellationToken ct)=>Change(o,r,false,ct);public Task<OrganizationSubscriptionDto>AssignPlanAsync(Guid o,ChangeEntitlementPlanRequest r,CancellationToken ct)=>Change(o,r,true,ct);
 async Task<OrganizationSubscriptionDto>Change(Guid o,ChangeEntitlementPlanRequest r,bool admin,CancellationToken ct){if(admin)RequireAdmin();else await Authorize(o,ct,true);var plan=await db.EntitlementPlans.SingleOrDefaultAsync(x=>x.Id==r.PlanId&&x.IsActive,ct)??throw new NotFoundException("Plan not found.");var sub=await Current(o,true,ct);if(r.StartTrial)sub.StartTrial(plan.Id,Math.Clamp(r.TrialDays??14,1,365));else sub.ChangePlan(plan.Id,DateTime.UtcNow.AddMonths(1));var org=await db.Organizations.SingleAsync(x=>x.Id==o,ct);org.ApplyPlan(plan.Code,plan.MaximumStorage<0?long.MaxValue:plan.MaximumStorage);await Audit(o,ct);await db.SaveChangesAsync(ct);return Map(sub);}
 public async Task<EntitlementCheckDto>CheckAsync(Guid o,string feature,CancellationToken ct){await Authorize(o,ct);var sub=await Current(o,true,ct);sub.Evaluate(DateTime.UtcNow);if(sub.Status is EntitlementSubscriptionStatus.Expired or EntitlementSubscriptionStatus.Cancelled or EntitlementSubscriptionStatus.Suspended or EntitlementSubscriptionStatus.Pending)return new(feature,false,null,null,$"Subscription is {sub.Status}.");var row=sub.Plan.Features.FirstOrDefault(x=>x.Feature.Key==feature);return new(feature,row?.Enabled==true,null,null,row?.Enabled==true?null:"Feature is not included in the current plan.");}
 public async Task EnsureAsync(Guid o,string feature,CancellationToken ct){var x=await CheckAsync(o,feature,ct);if(!x.Allowed)throw new ConflictException(x.Reason??"Feature is unavailable.");}
 public async Task EnsureUsageAsync(Guid o,UsageMetric metric,long amount,CancellationToken ct){await Authorize(o,ct);var sub=await Current(o,true,ct);var used=await Used(o,metric,ct);var limit=Limit(sub.Plan,metric);if(limit>=0&&used+amount>limit)throw new ConflictException($"{metric} limit has been reached.");}
 public async Task TrackAsync(Guid o,TrackUsageRequest r,CancellationToken ct){await Authorize(o,ct);if(r.Quantity<=0)throw new ConflictException("Usage quantity must be positive.");await EnsureUsageAsync(o,r.Metric,r.Quantity,ct);if(!string.IsNullOrWhiteSpace(r.Reference)&&await db.EntitlementUsageRecords.AnyAsync(x=>x.OrganizationId==o&&x.Reference==r.Reference,ct))return;db.Add(new UsageRecord(o,r.Metric,r.Quantity,DateTime.UtcNow,r.Reference));await db.SaveChangesAsync(ct);}
 public async Task<UsageSummaryDto>SummaryAsync(Guid o,CancellationToken ct){await Authorize(o,ct);var sub=await Current(o,true,ct);var end=Month.AddMonths(1);var rows=await db.EntitlementUsageRecords.AsNoTracking().Where(x=>x.OrganizationId==o&&x.OccurredAt>=Month&&x.OccurredAt<end).GroupBy(x=>x.Metric).Select(x=>new{x.Key,Value=x.Sum(y=>y.Quantity)}).ToListAsync(ct);var usage=Enum.GetValues<UsageMetric>().ToDictionary(x=>x,x=>rows.FirstOrDefault(y=>y.Key==x)?.Value??0);var limits=Enum.GetValues<UsageMetric>().ToDictionary(x=>x,x=>Limit(sub.Plan,x));return new(o,Month,end,usage,limits);}
 async Task<OrganizationSubscription>Current(Guid o,bool create,CancellationToken ct){var x=await db.OrganizationSubscriptions.Include(x=>x.Plan).ThenInclude(x=>x.Features).ThenInclude(x=>x.Feature).OrderByDescending(x=>x.CreatedAt).FirstOrDefaultAsync(x=>x.OrganizationId==o&&x.Status!=EntitlementSubscriptionStatus.Cancelled&&x.Status!=EntitlementSubscriptionStatus.Expired,ct);if(x is not null)return x;if(!create)throw new NotFoundException("Subscription not found.");var free=await db.EntitlementPlans.Include(x=>x.Features).ThenInclude(x=>x.Feature).SingleAsync(x=>x.Code==SubscriptionPlan.Free,ct);x=new OrganizationSubscription(o,free.Id,DateTime.UtcNow);db.Add(x);await db.SaveChangesAsync(ct);return x;}
 async Task SetFeatures(EntitlementPlan p,IReadOnlyDictionary<string,bool> values,CancellationToken ct){var defs=await db.FeatureDefinitions.ToListAsync(ct);foreach(var d in defs){var enabled=values.TryGetValue(d.Key,out var v)&&v;var row=p.Features.FirstOrDefault(x=>x.FeatureId==d.Id);if(row is null){row=new PlanFeature(p.Id,d.Id,enabled);db.Add(row);}else row.Set(enabled);}}
 async Task<long>Used(Guid o,UsageMetric m,CancellationToken ct)=>await db.EntitlementUsageRecords.Where(x=>x.OrganizationId==o&&x.Metric==m&&x.OccurredAt>=Month&&x.OccurredAt<Month.AddMonths(1)).SumAsync(x=>(long?)x.Quantity,ct)??0;
 static long Limit(EntitlementPlan p,UsageMetric m)=>m switch{UsageMetric.EventsCreated=>p.MaximumEvents,UsageMetric.Users=>p.MaximumTeamMembers,UsageMetric.StorageConsumed=>p.MaximumStorage,UsageMetric.AIGenerations=>p.MaximumAIJobs,UsageMetric.Templates=>p.MaximumTemplates,UsageMetric.Uploads=>p.MaximumUploads,UsageMetric.PhotosCaptured=>p.MaximumMonthlyCaptures,UsageMetric.ApiRequests=>p.MaximumApiRequests,_=>-1};
 Task Audit(Guid id,CancellationToken ct)=>db.AuditLogs.AddAsync(new AuditLog(UserId,"Entitlement",id,AuditAction.SubscriptionChange,current.IPAddress),ct).AsTask();
 static EntitlementPlanDto Map(EntitlementPlan x)=>new(x.Id,x.Code,x.Name,x.MonthlyPrice,x.YearlyPrice,x.Description,x.IsActive,x.DisplayOrder,x.Features.ToDictionary(f=>f.Feature.Key,f=>f.Enabled),new Dictionary<string,long>{{"events",x.MaximumEvents},{"teamMembers",x.MaximumTeamMembers},{"storage",x.MaximumStorage},{"galleries",x.MaximumGalleries},{"aiJobs",x.MaximumAIJobs},{"templates",x.MaximumTemplates},{"uploads",x.MaximumUploads},{"monthlyCaptures",x.MaximumMonthlyCaptures},{"apiRequests",x.MaximumApiRequests}});
 static OrganizationSubscriptionDto Map(OrganizationSubscription x)=>new(x.Id,x.OrganizationId,x.PlanId,x.Plan.Name,x.Plan.Code,x.Status,x.StartDate,x.ExpiryDate,x.TrialEnd,x.RenewalDate);
}
