"use client";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {Link,useNavigate} from "react-router-dom";
import {getAIJobs,queueAI} from "./api";
import {backgrounds,props,styles,type AIJob} from "./types";
import {useAIStudioStore} from "./useAIStudioStore";
import {useAIJobsSignalR} from "./useAIJobsSignalR";
import {useBoothStore} from "../../booth/store/useBoothStore";

type View="dashboard"|"editor"|"backgrounds"|"styles"|"jobs"|"history";
const nav:[View,string][]=[["dashboard","Overview"],["editor","AI Editor"],["backgrounds","Backgrounds"],["styles","Styles"],["jobs","Job Queue"],["history","History"]];
export default function AIStudio({view}: {view:View}){
 const navigate=useNavigate(),queryClient=useQueryClient(),booth=useBoothStore(),store=useAIStudioStore();
 const eventId=booth.session?.eventId,jobs=useQuery({queryKey:["ai-jobs",eventId],queryFn:()=>getAIJobs(eventId),refetchInterval:10_000});
 useAIJobsSignalR(eventId);
 const mutation=useMutation({mutationFn:({action,payload}:{action:string;payload:object})=>queueAI(action,payload),onSuccess:()=>queryClient.invalidateQueries({queryKey:["ai-jobs"]})});
 const input=booth.photos[0]?.previewUrl??booth.stripUrl??"";
 const submit=(action:string,extra:object={})=>{if(!eventId||!input)return;mutation.mutate({action,payload:{eventId,sessionId:booth.session?.sessionId,photoId:null,inputImage:input,prompt:store.edit.prompt||null,negativePrompt:null,...extra}});};
 return <main className="ai-studio"><aside><Link to="/dashboard" className="ai-brand">EVENTLENS <b>AI</b></Link><nav>{nav.map(([key,label])=><Link className={view===key?"active":""} to={`/ai${key==="dashboard"?"":`/${key}`}`} key={key}>{label}</Link>)}</nav><div className="ai-usage"><span>Monthly AI usage</span><strong>{jobs.data?.length??0} jobs</strong><i><b style={{width:`${Math.min(100,(jobs.data?.length??0))}%`}}/></i></div></aside>
  <section className="ai-main"><header><div><span>PROVIDER-INDEPENDENT AI</span><h1>{nav.find(x=>x[0]===view)?.[1]}</h1></div><button onClick={()=>navigate("/photo-processing/editor")}>Design Studio</button></header>
   {view==="dashboard"&&<Dashboard jobs={jobs.data??[]} onOpen={()=>navigate("/ai/editor")}/>}
   {view==="editor"&&<Editor input={input} store={store} busy={mutation.isPending} submit={submit}/>}
   {view==="backgrounds"&&<ChoiceGallery title="Background library" items={backgrounds} selected={store.edit.background} choose={background=>{store.set({background});navigate("/ai/editor");}}/>}
   {view==="styles"&&<ChoiceGallery title="Style gallery" items={styles} selected={store.edit.style} choose={style=>{store.set({style});navigate("/ai/editor");}}/>}
   {(view==="jobs"||view==="history")&&<Jobs jobs={(jobs.data??[]).filter(j=>view==="jobs"?j.status!=="Completed":j.status==="Completed")} loading={jobs.isLoading}/>}
  </section></main>;
}
function Dashboard({jobs,onOpen}:{jobs:AIJob[];onOpen:()=>void}){const running=jobs.filter(j=>j.status==="Running"||j.status==="Queued").length,done=jobs.filter(j=>j.status==="Completed").length;return <div className="ai-dashboard"><article className="ai-hero"><div><span>CREATIVE PIPELINE</span><h2>Transform moments.<br/>Keep the magic.</h2><p>Backgrounds, studio styles, enhancement, upscale, props, and event storytelling—all through your configured provider.</p><button onClick={onOpen}>Open AI Editor →</button></div><div className="ai-orb"><i/><b>12</b><small>AI capabilities</small></div></article><div className="ai-stats"><article><span>In queue</span><strong>{running}</strong></article><article><span>Completed</span><strong>{done}</strong></article><article><span>Success rate</span><strong>{jobs.length?Math.round(done/jobs.length*100):100}%</strong></article></div><h3>Popular workflows</h3><div className="ai-workflows">{["Remove background","Studio portrait","4× upscale","Memory book"].map(x=><button onClick={onOpen} key={x}><i>✦</i><b>{x}</b><span>Configure →</span></button>)}</div></div>}
function Editor({input,store,busy,submit}:{input:string;store:ReturnType<typeof useAIStudioStore>;busy:boolean;submit:(a:string,e?:object)=>void}){return <div className="ai-editor"><section className="ai-preview"><div className={store.compare?"compare":""}>{input?<><img src={input} alt="AI input preview"/>{store.compare&&<span>BEFORE</span>}</>:<p>Capture or select a photo to begin.</p>}</div><footer><button onClick={store.undo}>↶ Undo</button><button onClick={store.redo}>↷ Redo</button><button onClick={store.toggleCompare}>Before / After</button></footer></section><aside className="ai-controls"><label>Style<button onClick={()=>location.assign("/ai/styles")}>{store.edit.style??"Choose a style"} <span>›</span></button></label><label>Background<button onClick={()=>location.assign("/ai/backgrounds")}>{store.edit.background??"Keep original"} <span>›</span></button></label><label>Prompt<textarea value={store.edit.prompt} onChange={e=>store.set({prompt:e.target.value})} placeholder="Describe the transformation…"/></label><label>Upscale<div className="ai-pills">{([2,4,8] as const).map(x=><button className={store.edit.upscale===x?"active":""} onClick={()=>store.set({upscale:x})} key={x}>{x}×</button>)}</div></label><label>Props<div className="ai-props">{props.slice(0,4).map(x=><button className={store.edit.props.includes(x)?"active":""} onClick={()=>store.set({props:store.edit.props.includes(x)?store.edit.props.filter(p=>p!==x):[...store.edit.props,x]})} key={x}>{x}</button>)}</div></label><div className="ai-run"><button disabled={busy||!input} onClick={()=>submit(store.edit.background?"background":store.edit.style?"style":"enhance",{style:store.edit.style,background:store.edit.background,upscaleFactor:store.edit.upscale,props:store.edit.props})}>{busy?"Queuing…":"Generate preview"} <span>✦</span></button><button disabled={!input} onClick={()=>submit("upscale",{upscaleFactor:store.edit.upscale})}>Upscale only</button></div></aside></div>}
function ChoiceGallery({title,items,selected,choose}:{title:string;items:readonly string[];selected?:string;choose:(x:string)=>void}){return <div className="ai-gallery"><div><h2>{title}</h2><p>Provider-ready presets. Prompts stay editable in configuration.</p></div><section>{items.map((item,index)=><button className={selected===item?"active":""} onClick={()=>choose(item)} key={item}><i className={`ai-swatch s${index%6}`}/><b>{item}</b><span>Apply preset</span></button>)}</section></div>}
function Jobs({jobs,loading}:{jobs:AIJob[];loading:boolean}){return <div className="ai-jobs"><header><h2>{loading?"Loading jobs…":`${jobs.length} jobs`}</h2><span>Live updates enabled</span></header>{jobs.map(job=><article key={job.id}><i className={job.status.toLowerCase()}/><div><b>{job.jobType.replace(/([A-Z])/g," $1")}</b><small>{job.provider} · {job.status}</small></div><progress max="100" value={job.progress}/><strong>{job.progress}%</strong></article>)}{!loading&&!jobs.length&&<p>No jobs in this view.</p>}</div>}
